### ISSUE TITLE
Add support for rST

### ISSUE THREAD

**Issue by bbatsov** [cljdoc/cljdoc#102]
rST (http://docutils.sourceforge.net/rst.html) is one of the most popular doc formats and it'd be nice if it was supported on cljdoc. rST is one of the doc formats supported by GitHub. Hopefully adding support for it would be pretty easy given the fact that cljdoc already support Markdown and Autodoc.

**Comment by martinklepsch** [comment]
We’ll need a Java/Clojure rST library but if such thing exists this will be fairly easy to implement.

**Comment by bbatsov** [comment]
Hmm, surprisingly for me it turned out that the only Java processor (jrst) has been dead for a while. Seems a relatively easy option might be shelling out to the reference implementation http://docutils.sourceforge.net/. Not exactly ideal, though.

**Comment by martinklepsch** [comment]
I will close the issues about rST (#102) and .org (#103) support for now. 
I feel like with Asciidoc and Markdown we cover 99% of users.
