### ISSUE TITLE
Add support for org-mode

### ISSUE THREAD

**Issue by bbatsov** [cljdoc/cljdoc#103]
org-mode (https://orgmode.org/manual/Markup.html) is a very popular doc format (especially with Emacs users, which is something like every 2nd Clojure developer) and it'd be nice if it was supported on cljdoc. org-mode markup is one of the doc formats supported by GitHub. Hopefully adding support for it would be pretty easy given the fact that cljdoc already support Markdown and Autodoc.

**Comment by martinklepsch** [comment]
We’ll need a Clojure/java org-mode renderer but if that exists it should be easy to implement. 

If it doesn’t then we’d need another process/service which might be annoying from an ops perspective.

**Comment by bbatsov** [comment]
I did a quick search and it seems we're out of luck - https://orgmode.org/worg/org-tools/index.html

Plenty of options, but no Java/Clojure.

**Comment by jdhorwitz** [comment]
Would https://github.com/seylerius/organum work?

**Comment by bbatsov** [comment]
I also found https://github.com/orgzly/org-java which seems pretty good.

**Comment by martinklepsch** [comment]
I will close the issues about rST (#102) and .org (#103) support for now. 
I feel like with Asciidoc and Markdown we cover 99% of users.

**Comment by oskarkv** [comment]
Just wanted to say that I would also love org-mode support.
