### ISSUE TITLE
Conflicting UI: "could not find git repo" / "git import completed"

### ISSUE THREAD

**Issue by plexus** [cljdoc/cljdoc#104]
Just came across this when generating some docs, and thought it was quite confusing. Cljdoc tells me it doesn't know the git repo, while also saying it has completed importing the git repo. It's not clear for me if any action should be taken or what difference it would make.

![2018-08-15-113255_659x367_scrot](https://user-images.githubusercontent.com/32212/44142001-158eb632-a07f-11e8-832b-bcd13dfc906c.png)

**Comment by martinklepsch** [comment]
Thanks, I think this might be an edge case with SNAPSHOT releases where we default to using `master` as revision. 

With a non-SNAPSHOT release the hit import would fail if a commit SHA could not be determined.
