### ISSUE TITLE
Don't expand wiki links occurring inside code blocks

### ISSUE THREAD

**Issue by clyfe** [cljdoc/cljdoc#108]
(Note the backticks!)

```
`[[:x]]` is parsed as a link and becomes something weird like `[:x](some/path#x)`
```

The contents of the code block should be interpreted as plain text not as markdown.
To reproduce use the code below and generate documentation as markdown.

```clojure
(def my-five
  "My docstring. Example: `[1 2 [[:foo/bar]]`."
  5)
```

**Comment by martinklepsch** [comment]
Hey @clyfe, thanks for noticing this, good catch! 

The wiki link stuff is handled by some basic regex stuff (see below line 37). Probably we could just fix this by ensuring there's a space before and after the wiki link markers.

If you feel like giving this a shot, here are the [instructions to run cljdoc locally](https://github.com/cljdoc/cljdoc/blob/master/doc/running-cljdoc-locally.md).


https://github.com/cljdoc/cljdoc/blob/4cc801282d3beaa9e0a0d20eb7bc0606358acef8/src/cljdoc/render/api.clj#L34-L50

**Comment by martinklepsch** [comment]
Could you explain why it won’t fix the issue? 

Using flexmark has been considered for another issue so it’s definitely an option and our commonmark usage is fairly light so it might not even be a huge amount of work. 

In any case thanks for reporting 🤗

**Comment by clyfe** [comment]
There can be spaces around brackets in both code and wikilinks: " [[:code]] ", " [[my link]] ".

A regex is not powerful enough to match text outside code blocks, particularly given multiple ways code can be expressed in markdown: indent, inline via 2 backtiks, block via 6 backticks, tildes etc.

We want to apply wikilinkification on markdown text nodes other than Code or Link, with respect to the markdown parse tree. To do that we need to traverse/visit the tree and apply it to text node, which is what the wikilink extension does in flexmark; the hard part there is making sense of the [undocumented apis](https://github.com/vsch/flexmark-java/tree/master/flexmark-ext-wikilink/src/main/java/com/vladsch/flexmark/ext/wikilink) to have a custom link based on namespace/var.

The easy and most feasible easy is to just call into codox, but it's not obvious how to fit the params, someone with understanding of cljdoc inner works should find it a lot easier than me.

Flexmark has a Pegdown compatibility layer that could be used in conjunction to how codox does it, cljdoc knowledge needed as in the prior point.

I followed the code from `cljdoc.render.api/namespace-page` to `html/render` call in pedestal namespaces, and the cache-bundle doesn't quite convey what's inside of it in relation to fitting it with the params in codox. Someone already familiar would fit them much faster than me.

**Comment by martinklepsch** [comment]
The documentation for Flexmark's wiki link extension is here: https://github.com/vsch/flexmark-java/wiki/Extensions#wikilinks

I guess we could tackle this once we migrated to Flexmark and fixed #95 in the process.

**Comment by martinklepsch** [comment]
Looked into this a bit but this just doesn't look like a whole lot of fun: https://github.com/JianhuanZhuo/home/blob/5eb40c661335e7e8c63887cf174ec08fd8e9af45/src/main/java/cn/keepfight/utils/markdown/PegdownCustomLinkResolverOptions.java

**Comment by clyfe** [comment]
https://github.com/cljdoc/cljdoc/pull/110
