### ISSUE TITLE
Some UTF-8 chars seem to break articles

### ISSUE THREAD

**Issue by martinklepsch** [cljdoc/cljdoc#113]
[This article](https://cljdoc.xyz/d/lambdaisland/kaocha/0.0-118/doc/01-kaocha-考察) contains some UTF-8 characters that don't seem to go well with our code.

Need to look into it some more but likely the issue is somewhere here: https://github.com/cljdoc/cljdoc/blob/422f4636167d3534a9b636faf3d5c2ca7fa04eeb/src/cljdoc/renderers/html.clj#L97-L104

(presumably when trying to find the matching article inside the doctree)

**Comment by martinklepsch** [comment]
Seems that this is something with Pedestal. Pedestal reports the following URL for the GET request:

```
io.pedestal.http {:msg "GET /d/lambdaisland/kaocha/0.0-118/doc/01-kaocha-%E8%80%83%E5%AF%9F", :line 80}
```
but to correctly resolve the article we'd need something like this:
```
/d/lambdaisland/kaocha/0.0-118/doc/01-kaocha-考察
```

[Seems](https://stackoverflow.com/questions/11002827/passing-request-parameters-as-utf-8-encoded-strings) there is a thing [`ServletRequest#setCharacterEncoding()`](
http://docs.oracle.com/javaee/6/api/javax/servlet/ServletRequest.html#setCharacterEncoding%28java.lang.String%29) to set the used character encoding for processing requests. Haven't yet confirmed this is the issue but at least Pedestal doesn't seem to be calling this `setCharacterEncoding`.

**Comment by plexus** [comment]
Seems like a regular case of URL percent encoding/decoding

``` clojure
(require '[lambdaisland.uri.normalize :as n])

(n/percent-decode "/d/lambdaisland/kaocha/0.0-118/doc/01-kaocha-%E8%80%83%E5%AF%9F")
;;=> "/d/lambdaisland/kaocha/0.0-118/doc/01-kaocha-考察"
```

`lambdaisland.uri.normalize` is unreleased though but the same functionality should be available in ring/pedestal and I think even in the Java standard libs.

**Comment by martinklepsch** [comment]
Thanks, I was kind of thinking this should be done by Pedestal but regardless of that we probably don't want to wait for an upstream release to get it fixed. 
https://github.com/cljdoc/cljdoc/commit/42c01c3fbb1c44cef303edf6dd9a78c934598b4c introduces a change that manually url-decodes the article slugs.

**Comment by martinklepsch** [comment]
Coming this issue, might bug Pedestal people about this but it's working for now 🚀

**Comment by martinklepsch** [comment]
Seems it is a known issue in Pedestal, introduced in a recent version: https://github.com/pedestal/pedestal/issues/588
