### ISSUE TITLE
Support Gitlab in repo link 

### ISSUE THREAD

**Issue by martinklepsch** [cljdoc/cljdoc#123]
Some projects like [ortata](https://cljdoc.xyz/d/eval/otarta/0.3.0/doc/readme) use GitLab and some code in cljdoc currently is somewhat tied to GitHub. What's great is, is that source links seem to work just fine, i.e. both sites use the same URL pattern.

A thing that's not working great is the icon and link text in the top right. The various function contributing to this assume a GitHub URL. See below for details 

https://github.com/cljdoc/cljdoc/blob/1f2b7d084cb211250a9e2edf57ec73b98f30bf0f/src/cljdoc/render/layout.clj#L105-L110

All the `gh-` prefixed functions below could be renamed to `scm-owner` etc. with a check that either GitLab or GitHub URLs are passed.

https://github.com/cljdoc/cljdoc/blob/1f2b7d084cb211250a9e2edf57ec73b98f30bf0f/modules/shared-utils/src/cljdoc/util.clj#L134-L141

**Comment by eval** [comment]
:+1: 
Another thing: articles contain a link (bottom right) titled "Edit on GitHub". href is fine, title should be different.

**Comment by jsimpson-ovo** [comment]
I'll have a look at this one if that's alright? Should be able to do a PR soon.

**Comment by martinklepsch** [comment]
Totally alright of course :) Looking forward to see what you come up with! 🚀

**Comment by jsimpson-ovo** [comment]
Thanks, here's the PR: https://github.com/cljdoc/cljdoc/pull/138

**Comment by martinklepsch** [comment]
Fixed via #138, see it live here: https://cljdoc.xyz/d/eval/otarta/0.3.1/doc/readme

**Comment by eval** [comment]
Great stuff! Thanks @jsimpson-ovo 👍
