### ISSUE TITLE
Confused by empty package page

### ISSUE THREAD

**Issue by jorinvo** [cljdoc/cljdoc#124]
First, thanks for creating this really amazing tool! As a developer new to Clojure, cljdoc.xyz already became my default choice for looking up documentation of Clojure packages – even before opening their Github page. The docs are really easy to follow!

Now I found a package which seems to be not accessible through cljdoc:

https://cljdoc.xyz/d/org.clojure/tools.logging

Any hints on what I am doing wrong or how I can find out if the package is compatible?

Thank you :)

Edit: Just realized that I have the same issues with other of the "official", non-core packages: java.jdbc, tools.deps.alpha, core.async.

**Comment by martinklepsch** [comment]
For the 2nd point I mentioned we should probably add an issue to do one of the following:

1. Add a note that only artefacts for which documentation has been built are shown. 
2. Somehow include all artefacts and properly indicate if documentation is readily available (i.e. has already been built) or not

**Comment by jorinvo** [comment]
Thanks for your help @martinklepsch! Building docs works great! I did that with other projects before, but those other projects I could find with the search. I think that's because they where on Clojars.

I think this issue might not be too bad once cljdoc is more established.

If package authors feel responsible for building their package, users should also have no issues finding them.

I think your solution 1. would be totally good enough for now. Maybe it is even enough doing something as pragmatic as pointing users to an explanation like this issue here.

**Comment by martinklepsch** [comment]
> but those other projects I could find with the search 

yeah that's the issue with some of the `org.clojure` stuff... until #85 is done anyway :) 

I'll create a new issue about the note that we discussed here and close this one. 

Thanks a lot for raising this in any case, I think there are probably more places like this where a line of text could clear things up considerably.

**Comment by jorinvo** [comment]
Thank you!
