### ISSUE TITLE
Change Quick switcher shortcut to Slack-style CMD+K

### ISSUE THREAD

**Issue by martinklepsch** [cljdoc/cljdoc#126]
Currently the shortcut is just <kbd>k</kbd> but it should be <kbd>Cmd</kbd> + <kbd>k</kbd> like in Slack. (Slack uses the same shortcut for native and browser apps so I assume it's a reasonable choice with few conflicts.)

Windows probably uses <kbd>ctrl</kbd> as modifier. Not sure.

**Comment by avichalp** [comment]
It is `cmd` + `k` on Mac and `ctrl` + `k` on windows. Here is the [reference](https://get.slack.help/hc/en-us/articles/217626598-Get-around-faster-with-keyboard-shortcuts) 

Added a PR for this change https://github.com/cljdoc/cljdoc/pull/132

**Comment by avichalp** [comment]
`keydown` event is dispatched before `keyup` event. In case of this key combination (`Ctrl` + `k`)
we want to trigger action when  `k` is pressed and `Ctrl` is already down. This is why listening to `keyup` won't work here for key combination.

**Comment by martinklepsch** [comment]
Fixed in #132

**Comment by polymeris** [comment]
`Ctrl + k` is used by both Chrome and Firefox on Linux (possibly Windows as well) for "Jump to the search bar". You *could* probably `preventDefault` the event, but maybe it would be better to revert to just `k`.

**Comment by avichalp** [comment]
I think use of `CMD+K`/ `Ctrl+K` is inspired from Slack. I am not sure which is a better choice for users. Personally I would prefer `CMD+K`.

Although we can add a `preventDefault` here:

https://github.com/cljdoc/cljdoc/blob/d5f7c38cf31f2386145ee539008e9dc519c426d4/js/switcher.js#L67-L83

**Comment by martinklepsch** [comment]
@polymeris this probably shouldn’t be the only factor but I’m wondering: could you check what key combination Slack uses for switching chats when opened in the environments you described?

**Comment by polymeris** [comment]
Slack also uses `Ctrl+k` in both chromium and firefox.

**Comment by polymeris** [comment]
Github uses `s` or `/`. I have seen the latter in other place, as well (e.g. https://react.semantic-ui.com)

**Comment by jorinvo** [comment]
`/` is also a Firefox shortcut for opening search (same as `C+F`).  It's hard to find something without conflicts 😄

**Comment by martinklepsch** [comment]
I'm happy to change the key combination. If somebody digs into this and can give a confident recommendation — let's change it. @polymeris if you feel confident that we should use `/` then please open an issue. Thanks :v:
