### ISSUE TITLE
Better copy on 

### ISSUE THREAD

**Issue by martinklepsch** [cljdoc/cljdoc#128]
When no docs for for an artefact have been built the artefact overview page that usually lists versions doesn't list anything. This is confusing and there should be a few lines of copy that indicate that this page only lists versions that documentation has been built for. 

<img width="831" alt="screen shot 2018-10-04 at 20 32 21" src="https://user-images.githubusercontent.com/97496/46495031-a05ab380-c814-11e8-9c21-45f7c2087473.png">

This may also apply to group ID pages like this one: https://cljdoc.xyz/d/org.clojure

via #124

**Comment by jorinvo** [comment]
I can look into this if you don't mind.

**Comment by jorinvo** [comment]
Guess can close this now :)

**Comment by martinklepsch** [comment]
Good idea :)

**Comment by martinklepsch** [comment]
Good idea :)
