### ISSUE TITLE
consider a TLD other than xyz

### ISSUE THREAD

**Issue by rubygeek** [cljdoc/cljdoc#135]
Often .xyz domains are associated with malware site. I work at Cisco Systems and they are automatically blocked :) Not sure if other networks would have similar policies.

**Comment by martinklepsch** [comment]
Thanks Nicola! :)

For context: I initially chose .xyz so I would be forced to reconsider the horrible mouthful that is “cljdoc” — hasn’t worked too well so far. 😅

The domain cljdoc.org currently redirects to cljdoc.xyz. I assume we could switch this around or even pick an entirely new name. 

Happy to hear other people’s opinions on this, I know the .xyz TLD has been a source of confusion...

**Comment by danielcompton** [comment]
I've been doing Google searches for cljdoc [library] and have found that it is frequently not showing up at all or lower than other pages. I'm not sure exactly what the solution is here, but this seems like a reasonable step to take.
