### ISSUE TITLE
Navigate search results using up/down arrow keys

### ISSUE THREAD

**Issue by avichalp** [cljdoc/cljdoc#137]
I think it will be better UX to let users navigate search results with arrow keys (up and down).
Also using `return` key on a result to open its docs.

**Comment by martinklepsch** [comment]
Good catch @avichalp! For the quick switcher that is available via <kbd>CMD</kbd> + <kbd>k</kbd> I did implement the up/down arrow thing. 

https://github.com/cljdoc/cljdoc/blob/63a99b91de40b51ce235c474f3e73b62bc302135/resources/public/switcher.js#L91-L95

I think in general there is a lot of code that could be shared between those two pieces (search & quick switcher) but I didn't want to abstract too much before that emerged more clearly.

**Comment by greg-kargin** [comment]
I tried to tackle this issue, but for some reason search-widget and quick-switcher don't appear on page when i run local instance of clj-doc.

**Comment by martinklepsch** [comment]
Oh and thanks for taking a look at it 🙌

**Comment by martinklepsch** [comment]
@greg-kargin back at a computer now, here are the docs to setup the JS stuff: https://github.com/cljdoc/cljdoc/blob/master/doc/running-cljdoc-locally.md

It would be kind of nice if in development we would render some small error message in place of the JS components if the JS file could not be found. Not sure if it's worth the effort — What do you think?

**Comment by greg-kargin** [comment]
@martinklepsch, thanks for such detailed response! I agree that showing error-plaque in place of missing components is a great idea. I'll try to fix both of this issues 👍
