### ISSUE TITLE
Analyzer doesn't fetch dependencies from repositories defined in the pom

### ISSUE THREAD

**Issue by IamDrowsy** [cljdoc/cljdoc#144]
During code analysis, all dependencies are fetched from clojars or maven central. The pom can define other maven repositories to look for dependencies but the analyzer ignores them and [might fail](https://circleci.com/gh/martinklepsch/cljdoc-builder/5503). 
As this is not that uncommon in java land, the anlalyzer should search the repositories defined in a the pom.

**Comment by martinklepsch** [comment]
#### Some notes for people who would like to help with this: 

There's `cljdoc.util.pom` that extracts some stuff from POM files using jsoup.  You could then require that namespace in `cljdoc.analysis.runner` and change how the `deps.edn` is generated here: 

https://github.com/cljdoc/cljdoc/blob/67fbc69c0f0d78f32c7914dd2761307f46d0f591/modules/analysis-runner/src/cljdoc/analysis/runner.clj#L88-L89

> For background: The `cljdoc.analysis.runner` is the main entry point for running analysis on libraries. To improve dependency isolation that namespace will shell out to launch additional `clojure` processes with appropriate configuration via `-Sdeps`.

I assume it might be enough to customise [`:mvn/repos`](https://clojure.org/reference/deps_and_cli#_procurers) at the top level of the `deps.edn` map. (I assume that map is merged with the default Clojars/Central setup but not 100% sure.)

**Comment by martinklepsch** [comment]
Oh and for testing it might be helpful to just use either:

```sh
./script/cljdoc ingest -p some/project -v 0.1.0
```
or
```sh
# ./script/analyze.sh project version jar_path pom_path
./script/analyze.sh reagent 0.8.1 ~/.m2/repository/reagent/reagent/0.8.1/reagent-0.8.1.jar ~/.m2/repository/reagent/reagent/0.8.1/reagent-0.8.1.pom
```

**Comment by martinklepsch** [comment]
Oh really? Could you point out the spot in the docs where this is? Maybe it’s a typo that could be fixed or is actually valid in some situations...

**Comment by IamDrowsy** [comment]
Oh wow, sorry I just had a third and fourth look and realized I'm bad at counting braces. 😆
