### ISSUE TITLE
Only explicitly pass "provided" dependencies, not regular ones

### ISSUE THREAD

**Issue by martinklepsch** [cljdoc/cljdoc#147]
In order to have "add-on" namespaces with optional dependencies not break the build cljdoc includes all dependencies listed in a project's POM. By doing so we include dependencies with the scope "provided" that would otherwise not be included by the dependency resolution. 

This is the code defining what dependencies will specified explicitly:

https://github.com/cljdoc/cljdoc/blob/a04892814a08d1ceaa55b76dcaa2b821ec060fbd/modules/shared-utils/src/cljdoc/util/deps.clj#L43-L60

The issue here is now that we not only explicitly depend on dependencies with scope provided but also dependencies that would be included by regular resolution. In the process of doing so some information like the `<type>` property of a dependency can get lost.

[clj-boost's POM](http://repo.clojars.org/clj-boost/clj-boost/0.0.2/clj-boost-0.0.2.pom) is a good example for this since it contains a dependency with a `<type>` field:

```xml
<dependency>
  <groupId>ml.dmlc</groupId>
  <artifactId>xgboost4j-example</artifactId>
  <version>0.80</version>
  <type>pom</type>
</dependency>
```

Related to #54 to some extent.

A **possible solution** would be to ensure that `extra-deps` does not return dependencies that have a scope other than `provided`. 

To test this locally this snippet might be handy:

```sh
# at the root of the cljdoc git repo:
./script/analyze.sh clj-boost 0.0.2 ~/.m2/repository/clj-boost/clj-boost/0.0.2/clj-boost-0.0.2.jar ~/.m2/repository/clj-boost/clj-boost/0.0.2/clj-boost-0.0.2.pom
```

**Comment by IamDrowsy** [comment]
I tried to include the `type` as `:extension` in the `deps.edn` which worked for downloading the deps, but somehow the classes did not end up in the enviroment and the analyzer failed with `ClassNotFoundException`. Not sure what went wrong there, but then I went back to the suggested solution.

I tried which scopes end up in the analyzer, and besides `provided`, `test` and `system` also are not included with the usual resolution.
