### ISSUE TITLE
nicer formatting for code in docstrings

### ISSUE THREAD

**Issue by zcaudate** [cljdoc/cljdoc#157]
I really like this project. Thanks for doing this.

I usually have code in my docstrings and they get rendered as text.

Is there a way to format this as code?

<img width="451" alt="screen shot 2018-10-19 at 2 40 02 am" src="https://user-images.githubusercontent.com/1455572/47176919-6d9ed800-d349-11e8-83d7-4904bf65fd59.png">
<img width="439" alt="screen shot 2018-10-19 at 2 36 49 am" src="https://user-images.githubusercontent.com/1455572/47176922-6e376e80-d349-11e8-8dd4-d037ddf4128a.png">

**Comment by martinklepsch** [comment]
Oh and btw, you're a [special citizen in cljdoc](https://github.com/cljdoc/cljdoc/blob/1c8364b84da74e37a1d941b8b934a2118430b15a/src/cljdoc/server/release_monitor.clj#L53) 😄 

I can't entirely remember why I added this but I think it might have been that you just pushed tons of releases. Will remove that tomorrow 🙂

**Comment by zcaudate** [comment]
@martinklepsch: very honoured 🥇to be placed next to `lein-template`

The docs thing makes sense. I'll try it out.
