### ISSUE TITLE
Set rel=canonical URLs

### ISSUE THREAD

**Issue by danielcompton** [cljdoc/cljdoc#159]
cljdoc has many different versions of the same sets of documentation. For the most part, each version of documentation will probably be quite similar to the rest. This raises duplicate content issues for SEO purposes. rel=canonical metadata can tell search engines which is the canonical URL they should use when searching and passing SEO juice around.

For example, on https://cljdoc.xyz/d/bidi/bidi/2.0.0/doc/readme there would be a  tag `<link rel="canonical" href="https://cljdoc.xyz/d/bidi/bidi/2.1.4/doc/readme">` which points to the latest version of documentation.

https://support.google.com/webmasters/answer/139066?hl=en
https://yoast.com/rel-canonical/

**Comment by martinklepsch** [comment]
Fixed via #169
