### ISSUE TITLE
Warn when someone is on an older version of docs

### ISSUE THREAD

**Issue by danielcompton** [cljdoc/cljdoc#161]
If you're on an old version of a library (say https://cljdoc.xyz/d/bidi/bidi/2.1.1/doc/readme), there is no visual indication that this isn't the latest version. It could be good to add something in the header about this. Django has this for unsupported and unstable versions:

https://docs.djangoproject.com/en/1.8/topics/http/views/
https://docs.djangoproject.com/en/dev/topics/http/views/

The note/warning for old versions probably doesn't need to be red. It's not necessarily bad that someone is on an old version, but it should be clear to them when they're reading the docs.

**Comment by martinklepsch** [comment]
Good idea! Currently the rendering code all just uses one large map with all relevant information. This map currently does not include the latest version making this something that has to be addressed first.  This also applies to #159.

**Comment by martinklepsch** [comment]
Opened a PR for this in #168, looks like this:

<img width="1438" alt="screen shot 2018-10-19 at 17 19 58" src="https://user-images.githubusercontent.com/97496/47253754-0b80c880-d458-11e8-860a-130e5087cd2f.png">

Also considered a small yellow-ish dot and black text. Potentially a bit more subtle.
