### ISSUE TITLE
Create a sitemap

### ISSUE THREAD

**Issue by danielcompton** [cljdoc/cljdoc#162]
I have tried searching for some projects on cljdoc which are not indexed by Google, e.g. "site:cljdoc.xyz cuic" returns nothing, even though it is known. It could be good for cljdoc to build and publish a sitemap of projects so that Google can index them.

**Comment by martinklepsch** [comment]
Here's some code that uses Hiccup to create XML sitemaps: https://github.com/hashobject/sitemap/blob/master/src/sitemap/core.clj

I think it might be useful when working on this issue (since most Hiccup documentation focuses on HTML).

**Comment by danielcompton** [comment]
Following on from discussions on Slack, @dawran6 suggested:

> Hi maintainers, I’m working on adding sitemap to cljdoc. What do y’all think should be in the sitemap? I’m think of adding all the `/d/:group-id/:artifact-id` routes. Do you think that’s sufficient? Frankly, I’ve never created a sitemap before so don’t hesitate to let me know if I misunderstood something. Thanks.

I think that's going to be a pretty good start, although you'll want to be linking to the latest version of each artifact, i.e. use https://cljdoc.org/d/bidi/bidi/2.1.4/doc/readme, not https://cljdoc.org/d/bidi/bidi/ which redirects to the versioned URL. This would also be the canonical URL.

This does bring up the issue of having a `/current` version which is a synonym for the latest version and doesn't redirect to a versioned URL. This is going to be easier for Google to index because it is always the same version so search results will never have out of date versions being linked if Google's index is stale. On the other hand, you can indicate when something was changed to Google in the sitemap, so that may lessen the need if Google is able to keep reasonably up-to-date.
