### ISSUE TITLE
Menus for articles

### ISSUE THREAD

**Issue by zcaudate** [cljdoc/cljdoc#167]
It'll be great if an article can have a menu of 1st and 2nd level markdown headers.

<img width="665" alt="screen shot 2018-10-19 at 9 45 55 am" src="https://user-images.githubusercontent.com/1455572/47193119-d73bd800-d383-11e8-9094-fcea515f195a.png">

**Comment by martinklepsch** [comment]
See #20 — which I just reopened after it got closed when a partial implementation got merged.

Closing but feel free to reopen.
