### ISSUE TITLE
Enable GZIP compression

### ISSUE THREAD

**Issue by thheller** [cljdoc/cljdoc#175]
I just noticed that all content is served without gzip compression and that should really be enabled at least.

**Comment by martinklepsch** [comment]
Thanks Thomas, you're totally right. I kind of assumed Nginx just takes care of this. Will need to look into it. Some links for me (or others interested in helping) to read:

- https://www.digitalocean.com/community/tutorials/how-to-add-the-gzip-module-to-nginx-on-ubuntu-14-04
- https://docs.nginx.com/nginx/admin-guide/web-server/compression/

Probably this should wait until #158 got merged (or be done at the same time).
