### ISSUE TITLE
Search with input form and results page

### ISSUE THREAD

**Issue by witek** [cljdoc/cljdoc#186]
The current search on cljdoc.org is not based on web standards. It should be a form with an input field and be backed by a request handler on the server. That way it would be possible to integrate cljdoc searches in browser toolbars.

**Comment by green-coder** [comment]
I found this documentation which seem to cover the intent of having a "custom search engine" in the browser.

https://developer.mozilla.org/en-US/docs/Web/OpenSearch

**Comment by green-coder** [comment]
I am a heavy user of the in-browser search and I am going to take care of this issue.

**Comment by martinklepsch** [comment]
@witek I'll close this issue as I think it mostly addresses your request. Thanks to @green-coder for implementing it 👏
