### ISSUE TITLE
Improve error message for Git error

### ISSUE THREAD

**Issue by jorinvo** [cljdoc/cljdoc#187]
I triggered [a build](https://cljdoc.org/builds/5783).

The results said:
> In this case there was a problem `unknown-revision` importing from Git, but don't worry — **API docs will work regardless**.

There are two things we can improve here:
1. The message is not correct. API docs didn't work regardless. If I clicked on the below link, there were no API docs, but instead the prompt to trigger another build.

2. `unknown-revision` was caused by me deploying to Clojars without pushing the same version also to Github. That might be a common mistake and we could show that as a hint (e.g. _"Maybe you deployed the project without also pushing it to Github?"_).

Edit: Probably related to #111

**Comment by martinklepsch** [comment]
Thanks for opening this issue, took me a while to get back to this but here we go:

1. Analysis succeeded but there are no namespaces or functions in the provided jar. It looks like you uploaded an ahead-of-time compiled uberjar to Clojars in which case all Clojure code will be compiled to Java `.class` files. This is useful for packaging applications (makes them start up faster) but of course makes it impossible for us to analyse the Clojure sources.

     You can check this yourself by using `jar tf` on the jar. A regular "library jar" should only have the `.clj` files from your `src/` directory and a few other packaging related files.

    ```bash
    curl -O https://repo.clojars.org/googlesheets-sql-sync/googlesheets-sql-sync/0.4.2/googlesheets-sql-sync-0.4.2.jar
    jar tf googlesheets-sql-sync-0.4.2.jar
    ```
2. Good catch, the copy could definitely improved there (and what you're describing is a somewhat common situation I guess).

**Comment by jorinvo** [comment]
Thanks for your detailed explanation @martinklepsch!

1. I figured that out pretty quick and got the next build to work. Guess there is no way of detecting this "error" of trying to view documentation for an aot-compiled jar easily, right? Sure others would run into this as well and having an explanation like yours would have saved me a few half an hour of confusion.

If we should fix both, 1. and 2. should we make two separate issues?

**Comment by martinklepsch** [comment]
@jorinvo do you think this makes sense in terms of wording? Let me know if you have any alternative suggestions, happy to take them 🙂 

<img width="667" alt="screenshot 2018-11-08 at 18 32 14" src="https://user-images.githubusercontent.com/97496/48216323-ad734100-e384-11e8-87f8-de9f2f6e240a.png">

**Comment by jorinvo** [comment]
@martinklepsch thanks for your fast action! Looks good to me 👍
