### ISSUE TITLE
Proxying external resources?

### ISSUE THREAD

**Issue by danielcompton** [cljdoc/cljdoc#190]
Not sure how important it is, but it looks like cljdoc loads third party images directly to the users browser. GitHub uses a proxy called Camo to generate anonymous URLs to hide your browser details from the third party site. This could be nice to do, but is probably a bit of work to setup and maintain.

https://help.github.com/articles/about-anonymized-image-urls/

**Comment by martinklepsch** [comment]
I'm inclined to close this (at least for now) since it feels like a fairly "late-game" optimisation and I want to keep the list of open issues somewhat short 😄 Do you think it's ok to close?

**Comment by danielcompton** [comment]
Yeah I think it's probably fine to close for now.
