### ISSUE TITLE
Allow doc/cljdoc.edn to address multiple artifacts

### ISSUE THREAD

**Issue by martinklepsch** [cljdoc/cljdoc#198]
Since having multiple modules in single Git repositories is becoming a thing (see [reitit](https://github.com/metosin/reitit/tree/master/modules) & [muuntaja](https://github.com/metosin/muuntaja/tree/master/modules)) the `cljdoc.edn` configuration file should allow users to supply different configuration<sup>1</sup> for each module/artifact.

<sup>1</sup> Currently the only configuration is doc trees but in the future this may be expanded to analysis configuration like excluding side-effecting files from analysis or inlined dependencies as in `nrepl.inlined-deps.*`

#### Proposal

Currently the map in `doc/cljdoc.edn` is expected to have various keywords at the top level, most notably `:cljdoc.doc/tree`. In order to maintain this we can allow additional symbol keys in the EDN map whose respective values will take precedence if the symbol matches the project currently analysed. An example:

```clj
{:cljdoc.doc/tree [["Overview" {:file "doc/overview.md"}]]
 metosin/reitit {:cljdoc.doc/tree [["Introduction" {:file "intro.md}]]}}
```
With a config like this `Introduction` will only be rendered for `metosin/reitit` while `Overview` will be rendered for every other project that points to the same Git repository. 

This is backwards compatible and keeps the configuration format straightforward for those who don't maintain multiple projects in a single Git repository.

#### Feedback

I would appreciate feedback on this proposal especially from those who maintain multi-module repositories. (:wave: @ikitommi)

Related to #24

**Comment by martinklepsch** [comment]
Maybe there's a misunderstanding here but not sure. I'm not suggesting to split up documentation but rather have one place with all docs rather than duplicating the reitit docs for all individual modules as it is the case with various reitit libs:

- https://cljdoc.org/d/metosin/reitit-http/0.2.7/doc/introduction
- https://cljdoc.org/d/metosin/reitit-ring/0.2.7/doc/introduction

The idea is that using the proposed configuration format above you could have a separate documentation page for these projects, perhaps pointing users to the main reitit docs (which will also have API documentation for module dependencies in the future as discussed in #24).

There are two reasons why I want to avoid this kind of duplication:

- Users may get confused what docs they are viewing if the documentation is looking almost identical
- Search engines won't properly index duplicate content

**Comment by ikitommi** [comment]
Great point, didn't realize the submodules have own pages too! (github-based docs like gitbook don't know anything about deployed modules) As a busy lazy person, not likely having time to manually collect sub-module docs like this. Few ideas:

- somehow enable (maybe default to?)  that the sub-modules don't have any docs => shown on the artefact list, but would redirect to main docs?
- is the module info property of an page or the whole documentation? if it would be a page property, could the syntax be:

```clj
{:cljdoc.doc/modules true ;; generate seprate documentation for modules
 :cljdoc.doc/tree [["Overview" {:file "doc/overview.md"}] ;; no :modules, for all
                   ["Introduction" {:file "intro.md"
                                    :modules #{reitit/ring}}]]} ;; just reitit/ring
```

... this would allow later extracting that info from documentation meta-data?

**Comment by martinklepsch** [comment]
cljdoc builds documentation for artifacts that have been deployed to a Maven repository so that's why things are a bit different compared to other tools like gitbook.

What I had in mind with the example above was that you could provide one "default doctree" and selectively override that doctree for specific artifacts. So for instance you could have one file `modules/README.md` that gives an overview over all existing modules and also points the user to the documentation for `metosin/reitit` where the full reitit docs can be found.

```clj
{
  ;; used for any project except metosin/reitit
  ;; could contain an overview about all modules and a pointer
  ;; to the overarching documentation for metosin/reitit
  :cljdoc.doc/tree [["Overview" {:file "modules/README.md"}]]      
 
  ;; used for metosin/reitit
  metosin/reitit {:cljdoc.doc/tree [["Introduction" {:file "intro.md"}] 
                                    ,,,]}
}
```

As far as I can tell this should allow similar per-module customization as in the config format you shared. 

I'm not 100% sure I fully understand your suggestion though so maybe I'm missing something.
