### ISSUE TITLE
Create list of all Clojure-relevant artifacts on Maven Central

### ISSUE THREAD

**Issue by martinklepsch** [cljdoc/cljdoc#200]
There are a bunch of Clojure based artifacts on Maven Central and it would be nice if we could include those in searches as well as check for recent releases that need building on cljdoc.

I think a reasonable way forward could be a mixture of a hardcoded list and something that crawls Maven Central based on group IDs (e.g. https://repo1.maven.org/maven2/org/clojure/).

This might be a somewhat unexciting task and it's low-ish priority for now but I just wanted to open this issue in case anyone feels like working on this or has alternative suggestions about how to approach this.

Required for #85

**Comment by holyjak** [comment]
@martinklepsch do we still need this? Now that we automatically fetch all M.C. artifacts under org.clojure?

**Comment by martinklepsch** [comment]
Good point, I don’t think we need this anymore. 👍
