### ISSUE TITLE
Make a very clear next action once a build has completed

### ISSUE THREAD

**Issue by danielcompton** [cljdoc/cljdoc#204]
When watching a build happen (e.g. https://cljdoc.org/builds/6561), at the end of the build, there isn't a single clear next action to take. One idea would be to add a button like this:

<img width="1045" alt="screenshot of google chrome 13-11-18 10-33-28 am" src="https://user-images.githubusercontent.com/811954/48376365-912e2600-e72f-11e8-8823-2b5dc04e7cb7.png">

```html
<a class="f6 link dim ph3 pv2 mb2 dib white bg-blue" href="#0">Go to new documentation</a>
```

Styling and copy both need some work, but I've often felt when I'm looking at a build, "Ok, now what?" once it has finished.

Possibly another thing to do would be to include a big green tick/red cross on the last build step so people know that the process has completed.

**Comment by corasaurus-hex** [comment]
What if it just redirected to the documentation after it successfully completes? Does your average user want to stay on the build page?
