### ISSUE TITLE
Figure out what to do with empty namespaces

### ISSUE THREAD

**Issue by martinklepsch** [cljdoc/cljdoc#21]
[Uruk](https://github.com/daveliepmann/uruk) contains some empty namespaces. Codox renders those as every other namespace, just empty. We should probably default to something similar. For now I removed them from the sidebar in https://github.com/martinklepsch/cljdoc/commit/f24ff7cd24210c49ee26258c8206e1727270388e

💡  **Good solution here:** https://github.com/cljdoc/cljdoc/issues/21#issuecomment-554664586

**Comment by borkdude** [comment]
This is an example of a namespace that does have specs, but no public vars:

https://cljdoc.org/d/speculative/speculative/0.0.3-SNAPSHOT/api/speculative.optional

**Comment by seancorfield** [comment]
I was very surprised to see the _default_ behavior was to omit "empty" namespaces from the navigation tree. `next.jdbc` has two namespaces with no public vars: both of them provide implementations of protocols. One of them has a nice, long docstring on `ns` that I want users to be able to see easily from the cljdoc navigation tree, the other could be omitted (it's really just an implementation detail of the library).

My preference would be for cljdoc to recognize metadata on the `ns` that indicates whether to omit the "empty" namespace from the nav tree or to include it. If that was available, the default behavior would be fine, and I could add an annotation in `next.jdbc.date-time` to request cljdoc include it in the nav tree even tho' it has no public vars.

Proposal:
```clojure
(ns ^:cljdoc.doc/include-empty-ns some.name.space
  ,,,)
```

**Comment by martinklepsch** [comment]
This would introduce non-standard metadata aka configuration which I'm always a little wary of, what would you think about the following:

- If an empty namespace has a docstring it is included in the sidebar
- If you want to exclude such namespaces, use `^:no-doc`

As far as I can tell this would cover most use cases with sane defaults, i.e. showing namespaces that have documentation.

**Comment by seancorfield** [comment]
I'd be fine with that too. I just assumed that you might want to keep the current default behavior (exclude empty by default) -- but I'd certainly much rather have _include empty by default_ behavior!

**Comment by lread** [comment]
While you are in there, you might consider excluding or rewording ["No vars found in this namespace"](https://cljdoc.org/d/seancorfield/next.jdbc/1.0.10/api/next.jdbc.transaction).

![image](https://user-images.githubusercontent.com/967328/68974807-98af6180-07bf-11ea-9e83-b77671d88a1c.png)

The phrasing is hinting that maybe something has gone wrong when it has not. I would lean toward removing it, but maybe don't fully understand why it is there.  Visually softening it would also likely work.

I first noticed this while creating some overview docs in [the top namespace for (the yet to be released) rewrite-cljc](https://github.com/lread/rewrite-cljs-playground/blob/89efbd4d3ef98a834b82bccb1f102ece278a805e/src/rewrite_clj.cljc).

**Comment by martinklepsch** [comment]
For this kind of minor UX stuff I'm very much ok with what might be considered a breaking change.

> but I'd certainly much rather have include empty by default behavior!

Do you think there's value in showing empty namespaces even if there will be nothing else for the user to see than the name of the namespace? (In contrast to namespaces where there is more to show like a docstring.)

**Comment by seancorfield** [comment]
Define "empty"...

* ns with vars => not empty
* ns with a docstring but no vars => not empty -- change to include in tree nav, drop "No vars found in this namespace." message (so just show name and docstring)
* ns with no docstring and no vars => still empty -- omit from tree nav, generated file should contain name and "No vars found in this namespace." maybe in italics or a different color (so it doesn't like cljdoc just "broke" generating that namespace)

**Comment by martinklepsch** [comment]
Alright, that's what I was implying :+1: — thanks for your feedback Sean!

**Comment by seancorfield** [comment]
Excellent! Is this live? Do we need to force rebuilds of docs to take advantage of this?

**Comment by martinklepsch** [comment]
Stuff is deployed as it is merged into `master` and the transaction namespace shows up in the sidebar now. 

Thanks to @kloimhardt for his work on this and many other improvements he has shipped in recent days!

**Comment by kloimhardt** [comment]
I opted for keeping the "No vars found in this namespace." message, even if a docstring is present. That is not entirely in line with your second bullet point, @seancorfield. But the blue italic font fits in a consistent manner, I think. Hope everyone is happy with this (?).

**Comment by seancorfield** [comment]
Yes, the blue italic message works: https://cljdoc.org/d/seancorfield/next.jdbc/1.0.6/api/next.jdbc.transaction

I have since marked this ns with `^:no-doc` to remove it from the sidebar until I have more useful documentation to add to that file!
