### ISSUE TITLE
Marginalia style ("literate") compilation option

### ISSUE THREAD

**Issue by metasoarous** [cljdoc/cljdoc#210]
Marginalia has been breaking on Semantic CSV for some time now and preventing me from minting a new release (see metasoarous/semantic-csv#59).

Semantic CSV lends itself quite nicely to the Marginalia/Literate style code/documentation, and I've seen folks point to Semantic CSV as a good illustration of the style for Clojurists; I've also already put a bunch of work put into organizing things this way, and so all in all, I'm somewhat reluctant to switch to a new different style.

That having been said, after having looked into cljdoc a bit, I really love the concept, and am tired of waiting for Marginalia to fix it's weirdo build issues. So I'm wondering if there's a way cljdoc could be extended to support Marginalia style documentation? Is there a way this could be made to work with cljdoc? If there was, I think I would switch in an instant.

Thanks in advance!

**Comment by martinklepsch** [comment]
Hi Christopher 👋 I really lik semantic-csv’s literate docs but I’m afraid there’s no straightforward path for cljdoc to support it.

- Analysis happens in a sandboxed environment and only “API Data” is exported from that environment (~vars + metadata). Comments that aren’t part of the runtime state aren’t really taken into consideration and modifying the analysis code to support both of these concerns would require some refactoring.
- I’m not sure how Marginalia works but if it just transforms a Clojure file (string) without loading it then we won’t need sand boxing making some of this easier. 

That said —

- I believe that part of the proposition of cljdoc is also to provide a unified interface for end users and so even if we get this to work the default will likely remain closer to what’s already there.
- As far as I understand literate style docs would not support showing API information about functions generated by macros or similar. 

If you’d still like to use cljdoc I’d encourge you to move some of the comments into docstrings and what remains into articles. Docstrings are formatted as markdown so you can also format longer texts in a way that they are easy to read for consumers. 

Hope this makes sense and thanks for your interest!

**Comment by martinklepsch** [comment]
@metasoarous I'll close this issue due to inactivity but happy to chat more if there's anything you'd like to discuss. Either here on Slack or via Email. Cheers!
