### ISSUE TITLE
Adding a in-browser "search engine"

### ISSUE THREAD

**Issue by green-coder** [cljdoc/cljdoc#214]
This is a RFE. In firefox, that's on the right side of the URL bar:

![image](https://user-images.githubusercontent.com/598193/48659606-85739400-ea8e-11e8-80d0-2fa20d58e549.png)

**Comment by martinklepsch** [comment]
Can you explain further? Also might this be a duplicate of #186?

**Comment by green-coder** [comment]
Yes, it is a duplicate of issue 186.
