### ISSUE TITLE
Implement the open-search suggestions

### ISSUE THREAD

**Issue by green-coder** [cljdoc/cljdoc#223]
When the user set `cljdoc` as the main search engine of the browser (I tested in Firefox only), s/he has the possibility via a checkbox to turn on a "suggestion" feature where cljdoc receives the search terms being typed, and can reply with a list of completions on the terms.

### Usage

1. Setup in the preference tab

![image](https://user-images.githubusercontent.com/598193/48756247-5437d580-ecd3-11e8-8e5f-5eff38489211.png)

2. Type in the address bar

![image](https://user-images.githubusercontent.com/598193/48755941-2d2cd400-ecd2-11e8-803b-9acf3893313e.png)

### Implementation

1. [x] Implementing the suggestion end point correctly.
2. [x] Base the completion upon a list of the most popular libraries of the Clojure(Script) ecosystem, it should be good enough for most of the users.
3. [ ] Improve on the previous part by fetching the data from Clojars once every hour. The completions could be ordered by popularity if we can get this data as well.

**Comment by holyjak** [comment]
Fixed by #316
