### ISSUE TITLE
Document docstring formatting

### ISSUE THREAD

**Issue by urzds** [cljdoc/cljdoc#234]
It appears that docstrings are formatted as Markdown, but I cannot find documentation on which variant you are using. Would be nice to have that information in https://github.com/cljdoc/cljdoc/blob/master/doc/userguide/for-library-authors.adoc

Additionally, this would help building tools that assist in writing documentation that will render nicely on https://cljdoc.org (cursive-ide/cursive#2090).

**Comment by martinklepsch** [comment]
We're using https://github.com/vsch/flexmark-java for Markdown and AsciiDoctorJ for Asciidoc. 

The specifics can be found in https://github.com/cljdoc/cljdoc/blob/master/src/cljdoc/render/rich_text.clj

A PR adding this to the guides would be very welcome 👍

**Comment by urzds** [comment]
There you go: #238 :)
