### ISSUE TITLE
Allow inclusion of namespaces provided by dependencies in API docs

### ISSUE THREAD

**Issue by martinklepsch** [cljdoc/cljdoc#24]
[Reitit](https://github.com/metosin/reitit), [Yada](https://github.com/juxt/yada/) and others are composed of multiple smaller libraries. Documentation often refers to namespaces within those libraries, which are not part of the actual "main artifact".

It would be nice to better support these projects by allowing them to include API docs for namespaces in their dependencies in some way.

A potential approach could be introducing a configuration option:

```clj
;; doc/cljdoc.edn
{:cljdoc/include-namespaces-from-dependencies [reitit/core reitit/ring ,,,]
```

This information could be used to retrieve namespaces from those dependencies and add them to the list of namespaces in the sidebar. 

Things to watch out for:
1. We'll need to make sure we include the right version of this namespace (i.e. look in the main artifacts `pom.xml`)
2. The UI should indicate that these namespaces come from a different artifact
3. yada provides different bundles, we should only include namespaces that the individual bundle depends upon

**EDIT:** Ring also is this kind of library.

**Comment by martinklepsch** [comment]
> - repo with modules A, B, C and D (bundling A, B and C)
> - D has the edn-file

I'm not sure I fully understand but I assume there would need to be some understanding of "what is a module?" for this to work? 

Can you maybe explain in what ways this is different form the suggestion in the issue? Thanks :raised

**Comment by ikitommi** [comment]
My last comment was total nonsense :)

But here's a stab at reitit docs: https://github.com/metosin/reitit/commit/12dbc74e95533bade4e7f4abe7cb1a1ee5adeceb

**Comment by martinklepsch** [comment]
Immutant is another project that would benefit from this: http://immutant.org/documentation/current/apidoc/ 

They also have some non-api docs and some very in-depth docstrings using markdown.

**Comment by martinklepsch** [comment]
I've been holding off tackling this until I got the recent storage refactoring out of the door (see [ADR #13](https://github.com/cljdoc/cljdoc/blob/master/doc/adr/0013-move-to-sqlite-for-storage.md)) but now it's probably fine to get back to this. Below are a few notes on what should be considered when implementing this:

- Currently the contents of a project's `cljdoc.edn` are not stored anywhere. For this feature we'll need to store it so we can figure out what dependencies' namespaces should be included.
- We're also not storing the list of dependencies. We could store them or read them from a project's POM as needed. Not sure what would be ideal. Without the list we'd only know the artefact name (from the `cljdoc.edn`) but not the version.
- When displaying namespaces from transitive dependencies we should clearly mark them as such. This requires some annotation in the "bundled" (see `bundle-docs`) data.
- Unless a build has been triggered for a transitive dependency docs might be unavailable so we should consider triggering one.
