### ISSUE TITLE
add `offline-bundle` command to ./script/cljdoc

### ISSUE THREAD

**Issue by martinklepsch** [cljdoc/cljdoc#244]
This command should build an offline bundle for the provided `--project` and `--version`. The data can be expected to already be in place via a previous `ingest` invocation.

Take a look at `cljdoc.render.offline/zip-stream` and the comment block in this namespace and `cljdoc.server.pedestal/offline-bundle` for starting points. The `offline-bundle` interceptor won't be needed but should be helpful in understanding how things come together on the server side.

via #236

**Comment by devurandom** [comment]
Should #263 have closed this?

**Comment by martinklepsch** [comment]
@devurandom indeed! Rebased manually and then the merge wasn’t recognized properly 😬

Thanks!
