### ISSUE TITLE
Incorrect parsing of code blocks in markdown?

### ISSUE THREAD

**Issue by residentsummer** [cljdoc/cljdoc#252]
Hi!

First, I'd like to thank you for this incredible project! Documentation always was one of the major pain points of Clojure, but maybe we now have a real chance to change the state of affairs :)

To the other matters. I was reading a doc for `clojure.java-time` and noticed quite strange examples in [local dates section](https://cljdoc.org/d/clojure.java-time/clojure.java-time/0.3.2/doc/readme#local-dates):

---

<img width="786" alt="screen shot 2018-12-15 at 21 40 18" src="https://user-images.githubusercontent.com/813112/50047256-2bc4b080-00b2-11e9-976c-35d2e7a19a6f.png">

---

Viewing [corresponing page](https://github.com/dm3/clojure.java-time/tree/0.3.2#local-dates) on github reveals that it wasn't author's intent to produce nils:

---

<img width="917" alt="screen shot 2018-12-15 at 21 43 13" src="https://user-images.githubusercontent.com/813112/50047285-76dec380-00b2-11e9-9873-33ec1bfffe4a.png">

---

I've observed this bug in Chrome and Firefox (both on MacOS).

**Comment by martinklepsch** [comment]
Oh wow, that’s a great find, thanks 👍

**Comment by martinklepsch** [comment]
I just spent some time looking into this.

- The markdown rendering code works correctly and supplying the README of the library will correctly render those return values that were seemingly replaced with `nil`.
- The database contains the markdown file with `nil` as return values in those code blocks.
- The [build from earlier this year](https://cljdoc.org/builds/2193) correctly identified the `0.3.2` tag to extract files from. 

All that said it's unclear to me how this README with `nil` ever ended up in the cljdoc database. I can only imagine that there was some kind of bug where cljdoc used the wrong revision of a Git repository but also wasn't able to find a revision of the clojure.java time repo at which those sections contained `nil` as return values.

In any case rebuilding the docs fixes the issue: https://cljdoc.org/d/clojure.java-time

I'll close this issue as not reproducible although it sure would've been nice to understand how that happened. 🙃
