### ISSUE TITLE
Broken links in docs

### ISSUE THREAD

**Issue by ikitommi** [cljdoc/cljdoc#254]
* Original/GitHub, links work: https://github.com/metosin/reitit/blob/master/doc/http/pedestal.md. 
* Generated GitBook, links work: https://metosin.github.io/reitit/http/pedestal.html
* cljdoc, links broken :( https://cljdoc.org/d/metosin/reitit/0.2.10-alpha1/doc/http/pedestal

click on the "route syntax" for example.

**Comment by ikitommi** [comment]
Awesome, thanks!

**Comment by martinklepsch** [comment]
@ikitommi should be fixed with 
https://github.com/cljdoc/cljdoc/commit/cffe4d1f90c1ce6ab8c290a74da95693936c7ecf.
