### ISSUE TITLE
Docs built from local maven repo fail to render

### ISSUE THREAD

**Issue by martinklepsch** [cljdoc/cljdoc#258]
Regression of #239 / cc @avichalp 

If a user uses `./script/cljdoc ingest --project bidi --version 25.0.0` and version `25.0.0` is only available on the users machine the documentation will fail to render.

This is due to some changes made in #239 where rendering documentation will now query a remote Maven repository for the project's POM file.

**Comment by avichalp** [comment]
Looks like if the Version is not available on Maven Central then error will be thrown while rendering the Doc. Thanks for pointing out. I will look into it.

**Comment by avichalp** [comment]
Make sense. `analysis-service` can be passed down from `route-resolvers` and then based on service type something like this can be done:

```patch
 (defn get-pom-xml
   "Fetches contents of pom.xml for a particular artifact version."
-  [project version]
-  (-> (artifact-uris project version)
+  [project version {:keys [service-type repos]}]
+  (if (= service-type :local)
+    ;; Todo:
+    ;; find pom in `repos`
+    ;;
+    (-> (artifact-uris project version)
       :pom
       http/get
-      :body))
+      :body)))
```
What do you think?

**Comment by martinklepsch** [comment]
If we explicitly provide `repos` in the `(= service-type :local)` case, wouldn't we just want to do the same in the non `:local` case? 

Maybe a quick and somewhat reasonable fix could be to just check if a .pom exists in the local repo and use it if it does?

```diff
 (defn get-pom-xml
   "Fetches contents of pom.xml for a particular artifact version."
   [project version]
-  (-> (artifact-uris project version)
-      :pom
-      http/get
-      :body))
+  (if-let [local-pom (:pom (local-uris project version))]
+    (slurp local-pom)
+    (-> (artifact-uris project version) :pom http/get :body)))
```

**Comment by martinklepsch** [comment]
Merged, thanks @avichalp! If you have any better ideas how to address this feel free to open another PR 👍
