### ISSUE TITLE
Support viewing tools.deps git libraries

### ISSUE THREAD

**Issue by borkdude** [cljdoc/cljdoc#268]
I think it would be useful if you could view tools.deps libries. E.g.:

https://cljdoc.org/d/Olical/cljs-test-runner/1ecd07dc60bffed04be47a2b21a21d9688cb801f

(maybe with an additional path fragment to indicate github / gitlab, etc).

This would also alleviate the pain of having to deploy a SNAPSHOT to preview doc changes. Often a SNAPSHOT is cached for a while so rebuilding has no effect.

When trying to preview docs locally for speculative I got:

```
$ ./script/cljdoc ingest -p speculative/speculative -v 0.0.3-SNAPSHOT --git /Users/Borkdude/Dropbox/dev/clojure/speculative
INFO [2019-02-07 11:10:08,932] main - cljdoc.server.system Starting :cljdoc/build-tracker
INFO [2019-02-07 11:10:08,935] main - cljdoc.server.system Starting :cljdoc/storage
INFO [2019-02-07 11:10:08,936] main - cljdoc.server.system Starting :cljdoc/analysis-service nil
ERROR [2019-02-07 11:10:09,046] clojure-agent-send-off-pool-0 - cljdoc.server.api Exception while processing speculative/speculative 0.0.3-SNAPSHOT (build 2)
java.lang.NullPointerException: null
    at clojure.core$name.invokeStatic(core.clj:1587)
```

When supporting tools.deps git libraries, I would not even have to do this locally, but can already preview my branch online where I try new configuration for CLJDOC in my lib.

**Comment by martinklepsch** [comment]
The issue with building straight from Git is that there needs to be some understanding of how to build a jar and/or source paths. With tools.deps this might be reasonably easy but at this point I'd prefer to focus on making local builds easier (maybe stripped down like offline bundle). I think with docker we could end up at some script that like `./script/cljdoc` but without requiring the entire directory structure around that script. 

Does that sound reasonable to you?

**Comment by borkdude** [comment]
Docker image sounds very reasonable!

Still maybe we're excluding a new wave of libraries that do not publish to a maven repo, simply because with tools.deps there is no real need anymore. E.g. https://github.com/cognitect-labs/test-runner has been around for a while and has never seen a release on Clojars or Maven Central.

**Comment by borkdude** [comment]
Another thought: not all README updates are tied to a release. E.g. when the author want to add examples or warnings related to the previous release, it would be nice to be able to view them in CLJDOC without creating a Maven Artifact.

**Comment by martinklepsch** [comment]
Yeah, that use case also came up before, unfortunately I haven't yet found a good way to "get this right". More discussion to be found in: https://github.com/cljdoc/cljdoc/issues/31.

**Comment by martinklepsch** [comment]
I'll close this for now as supporting Git "artifacts" isn't something that will likely be tackled in the immediate future.

In the meantime we can support updates to documentation via #31 and improve the feedback cycle by addressing #236.
