### ISSUE TITLE
Don't show articles help text if user provides a `cljdoc.edn`

### ISSUE THREAD

**Issue by martinklepsch** [cljdoc/cljdoc#270]
If a repo contains a `cljdoc.edn` file we can assume the user knows about articles and don't need this helptext:

<img width="413" alt="screenshot 2019-02-07 at 15 34 20" src="https://user-images.githubusercontent.com/97496/52418209-d7581300-2aed-11e9-8a9b-2cf3e6aaa29d.png">

**Comment by kloimhardt** [comment]
As I see it, in the current version, the help text is suppressed as intended. Is there a reason this issue its still open?

**Comment by lread** [comment]
Just checked, and the text can remain even when `cljdoc.edn` is present.

As a side-observation, I see this text as helpful for the library author but it is prominently presented for all.
