### ISSUE TITLE
Local JARs and classpath

### ISSUE THREAD

**Issue by residentsummer** [cljdoc/cljdoc#273]
I was trying to ingest a locally-built jar with a custom version string into cljdoc storage and encountered a bug (as I think).

I've found out that local jar isn't used for building the classpath. Instead, a maven dep is added to the deps map (https://github.com/cljdoc/cljdoc/blob/master/modules/analysis-runner/src/cljdoc/analysis/deps.clj#L92), pointing to project@version. So, after all manipulations the analysis impl got project classes on CP and an unpacked jar via command-line args. Both groups of files _may_ be of different versions.

I've tried a few approaches to overcome this issue, with mixed results:

1. First, I thought that jar path gets to runner_ng only if specified via CLI, so I've added a conditional expr to replace :mvn/version with :local/root if jar url is provided. This worked, but required changes seemed too intrusive for me (passing jar-uri through many funcs down to `deps/deps`. Besides, I wasn't sure, that including a project itself in the output of `(deps pom)` is conceptually right. And, as I known later, jar path is always there...
2. Second, I've removed `(assoc ... project {:mvn/version version})` from `deps/deps` and added a path to unpacked jar to the CP in `runner/analyze-impl`. Surprisingly, this didn't worked. I've found the root cause to be the way how `deps/deps` and `deps/extra-deps` work - only provided, test and system dependencies are included without explicit project dependency. I was curious about it and found this - https://github.com/cljdoc/cljdoc/issues/147. Since there us no equivalent of `<type>pom</type>` in tools.deps, this is a dead-end.
3. With all this knowledge, I've merged (1) and (2) successfully. The only issue that remained is whether to 1) leave project jar on CP and analyze unpacked files from different location 2) source both from one place. I went with the second option.

By the way, why do we need project files on CP? Is this a requirement for codox?

I've made a preliminary patch for this - could you please take a look? Or, maybe, I've got something terribly wrong with the whole situation :)

**Comment by residentsummer** [comment]
```
diff --git a/modules/analysis-runner/src/cljdoc/analysis/deps.clj b/modules/analysis-runner/src/cljdoc/analysis/deps.clj
index 56c9451..d88cabb 100644
--- a/modules/analysis-runner/src/cljdoc/analysis/deps.clj
+++ b/modules/analysis-runner/src/cljdoc/analysis/deps.clj
@@ -88,8 +88,7 @@
         (merge (get hardcoded-deps project))
         (ensure-required-deps)
         (ensure-recent-ish)
-        (merge cljdoc-codox)
-        (assoc project {:mvn/version version}))))
+        (merge cljdoc-codox))))
 
 (def ^:private default-repos
   {"central" {:url "https://repo1.maven.org/maven2/"},
@@ -103,17 +102,21 @@
 
 (defn resolved-and-cp
   "Build a classpath for the project specified by `pom-url`."
-  [pom-url repos]
+  [jar-url pom-url repos]
   {:pre [(string? pom-url)]}
   (println pom-url repos)
   (let [pom (pom/parse (slurp pom-url))
+        {:keys [group-id artifact-id version]} (pom/artifact-info pom)
+        project (symbol group-id artifact-id)
         resolved (tdeps/resolve-deps {:deps (deps pom),
                                       :mvn/repos (merge default-repos
                                                         (extra-repos pom)
                                                         repos)}
-                                     {:verbose false})]
-    {:resolved-deps resolved
-     :classpath (tdeps/make-classpath resolved [] nil)}))
+                                     {:extra-deps {project {:local/root jar-url}}
+                                      :verbose false})
+        clean (dissoc resolved project)]
+    {:resolved-deps clean
+     :classpath (tdeps/make-classpath clean [] nil)}))
 
 (defn print-tree [resolved-deps]
   (tdeps/print-tree resolved-deps))
diff --git a/modules/analysis-runner/src/cljdoc/analysis/runner.clj b/modules/analysis-runner/src/cljdoc/analysis/runner.clj
index 41b406b..cae8627 100644
--- a/modules/analysis-runner/src/cljdoc/analysis/runner.clj
+++ b/modules/analysis-runner/src/cljdoc/analysis/runner.clj
@@ -119,7 +119,9 @@
                              (util/infer-platforms-from-src-dir jar-contents))
         namespaces   (get-in @util/hardcoded-config
                              [(util/normalize-project project) :cljdoc.api/namespaces])
-        classpath*   (str (.getAbsolutePath impl-src-dir) ":" classpath)
+        classpath*   (string/join ":" [(.getAbsolutePath impl-src-dir)
+                                       (.getAbsolutePath jar-contents)
+                                       classpath])
         build-cdx      (fn build-cdx [jar-contents-path platf]
                          ;; TODO in theory we don't need to start this clojure process twice
                          ;; and could just modify the code in `impl.clj` to immediately run analysis
@@ -159,7 +161,7 @@
   "Analyze the provided "
   [project version jarpath pompath]
   (try
-    (let [{:keys [classpath resolved-deps]} (deps/resolved-and-cp pompath nil)]
+    (let [{:keys [classpath resolved-deps]} (deps/resolved-and-cp jarpath pompath nil)]
       (println "Used dependencies for analysis:")
       (deps/print-tree resolved-deps)
       (println "---------------------------------------------------------------------------")
diff --git a/modules/analysis-runner/src/cljdoc/analysis/runner_ng.clj b/modules/analysis-runner/src/cljdoc/analysis/runner_ng.clj
index c867c83..d22edd5 100644
--- a/modules/analysis-runner/src/cljdoc/analysis/runner_ng.clj
+++ b/modules/analysis-runner/src/cljdoc/analysis/runner_ng.clj
@@ -18,7 +18,7 @@
   (try
     (pp/pprint (edn/read-string arg))
     (let [{:keys [project version jarpath pompath repos] :as args} (edn/read-string arg)
-          {:keys [classpath resolved-deps]} (deps/resolved-and-cp pompath repos)]
+          {:keys [classpath resolved-deps]} (deps/resolved-and-cp jarpath pompath repos)]
       (println "Used dependencies for analysis:")
       (deps/print-tree resolved-deps)
       (println "---------------------------------------------------------------------------")
```

**Comment by martinklepsch** [comment]
Hey Anton, thanks for the issue, your observations are correct. When providing a jar multiple copies of the source files may end up on the classpath.

I'll try to answer some points right now, but will skip over some others for now.

> By the way, why do we need project files on CP? Is this a requirement for codox?

Codox uses the directory into which we unpack the jar to generate a list of namespaces that we need to extract information for. It then uses `ns-publics` and similar utilities to inspect the Clojure runtime and fetch docstrings etc. For this second step the namespaces need to be on the classpath. It might be possible to implement a namespace discovery mechanism that does not require a directory and instead operates on a jar. In fact I have some vague memories that Codox already supports this.

####  Supplying just a jar via `:local/root` or by adding it to the classpath 

Without additional steps this will likely cause issues with transitive dependencies. I.e. if we add a jar to the classpath without it's package file (`.pom`) being considered during dependency resolution we might end up with insufficient dependencies. 

#### Precedence

Generally classpath conflicts are OK (e.g. a path in a jar and a directory) as long as we understand precedence. It [seems that](https://stackoverflow.com/questions/6644440/java-which-of-multiple-resources-on-classpath-jvm-takes) items in the classpath string appearing earlier will take precedence over items appearing later. So if we make sure the `jar-contents-dir` always appears first we should not run into any problems. (?)


---

These are just some thoughts that came to mind, I haven't yet had the time to have a proper think about this and probably I've missed something. Still I hope it's at least a tiny bit helpful in moving this forward for now.

**Comment by martinklepsch** [comment]
@residentsummer Hey Anton, should we close this issue since #276 has been merged now?

**Comment by residentsummer** [comment]
Sure :)
