### ISSUE TITLE
Firefox blocks CORS requests

### ISSUE THREAD

**Issue by erasmas** [cljdoc/cljdoc#277]
It's not possible to use search UI in Firefox 65.0 on MacOS. Firefox blocks CORS request to `https://clojars.org/search?q=cats&format=json`

In debug console Firefox points to https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSDidNotSucceed for description of the root cause.

Search works fine in Safari.

**Comment by danielcompton** [comment]
> The HTTP request which makes use of CORS failed because the HTTP connection failed at either the network or protocol level. The error is not directly related to CORS, but is a fundamental network error of some kind.

Not sure if this is a CORS issue?

**Comment by erasmas** [comment]
You're right. I checked search on another machine using Firefox and the same set of plugins and it worked fine. Apology for raising this as an issue.

**Comment by martinklepsch** [comment]
No worries! 😊
