### ISSUE TITLE
Improve relevance of search results in Dash

### ISSUE THREAD

**Issue by nblumoe** [cljdoc/cljdoc#278]
While searching for the `re-frame` library, I realised that the results that for the search term `re-frame` don't include the library itself in the search results. It can be found by searching for `day8` though.

For the search term `re-frame` this might be due to a limitation on the number of results, combined with the ordering of the result items.

Ideally, the search would return `re-frame` as a highly relevant item.

## Searches on Dash:

![cleanshot 2019-02-24 at 07 44 35](https://user-images.githubusercontent.com/995628/53298284-d6ccb580-382b-11e9-8902-f6e45bff003d.gif)

![cleanshot 2019-02-24 at 07 45 09](https://user-images.githubusercontent.com/995628/53298288-e946ef00-382b-11e9-97c0-59ee58e3eb7a.gif)

## Same searches on the cljdoc website:

![cleanshot 2019-02-24 at 12 07 09](https://user-images.githubusercontent.com/995628/53298351-e1d41580-382c-11e9-93ef-3363e8dc1f5e.gif)

![cleanshot 2019-02-24 at 12 07 45](https://user-images.githubusercontent.com/995628/53298353-ea2c5080-382c-11e9-8c1d-73669c3eb9f8.gif)

**Comment by holyjak** [comment]
Likely will be fixed by https://github.com/cljdoc/cljdoc/issues/85

**Comment by holyjak** [comment]
@nblumoe can you please confirm that it is fixed now and close this issue? Thanks!

**Comment by nblumoe** [comment]
@holyjak thanks for improving this! I can confirm that it is resolved on the website now! 👍 

It isn't on the Dash app though. Even worse: I cannot find re-frame with "re-frame" search term, nor "day8" anymore. Can this by addressed from cljdoc too or is it a Dash issue?

**Comment by martinklepsch** [comment]
Dash will migrate to cljdoc’s own search endpoint with it’s next release.

**Comment by nblumoe** [comment]
Great! Thanks for improving the search and the work on cljdoc in general! ❤️
