### ISSUE TITLE
Support keyboard navigation like in Gitbook

### ISSUE THREAD

**Issue by ikitommi** [cljdoc/cljdoc#28]
Gitbook allows keyboard navigation between the (article) pages. Would be awesome to support that too. Example: https://metosin.github.io/reitit/

**Comment by martinklepsch** [comment]
@ikitommi just looking at the page you linked I'm not sure what keyboard shortcuts are supported. Could you give a few examples what you're primarily interested in?

**Comment by ikitommi** [comment]
Sure: the arrows left and right change the page.
