### ISSUE TITLE
Only show docstring label if more than one exists

### ISSUE THREAD

**Issue by mhuebert** [cljdoc/cljdoc#280]
It would be nice if we could elide the "ClojureScript Docstring" label (see below) when only one docstring exists. 

It looks to me like the `ignore-nil?`-related logic here: https://github.com/cljdoc/cljdoc/blob/master/src/cljdoc/platforms.clj#L25
could be copied to the implementation of `varies?` here: https://github.com/cljdoc/cljdoc/blob/master/src/cljdoc/platforms.clj#L47

![image](https://user-images.githubusercontent.com/165223/53529027-b6cb1980-3aeb-11e9-8055-5d659282c80d.png)

**Comment by martinklepsch** [comment]
Hey Matt & thanks for the issue!

I'm inclined to say that things are working as intended. On cljdoc the basic assumption is that whenever you have `some.thing/get` in Clojure and ClojureScript that both are fulfilling the same purpose on different platforms. It seems that in your case JVM [`get`](https://github.com/appliedsciencestudio/js-interop/blob/0f1f5b9858f0052dc18967023193ec4bb53e2c5d/src/main/applied_science/js_interop.clj#L90-L94) is an implementation detail of ClojureScript [`get`](https://github.com/appliedsciencestudio/js-interop/blob/0f1f5b9858f0052dc18967023193ec4bb53e2c5d/src/main/applied_science/js_interop.cljs#L30-L40) and not trying to replicate the behaviour on two different platforms?

I understand that this assumption is... an assumption — and may not always be correct 🙃

The [docs for js-interop](https://cljdoc.org/d/appliedscience/js-interop/0.1.11/api/applied-science.js-interop#get) currently indicate that most forms are cljc — which as far as I understood is not really the case, at least at this stage?

A solution to this could be to move more of the Clojure helpers into `impl` namespaces and thus properly arrive at a version of the code where `applied-science.js-interop/get` only exists on the ClojureScript side.

If you want to hide namespaces or vars from the documentation you can use `^:no-doc` metadata btw. Thinking about it this may also work to achieve the outcome described in the previous paragraph.

Hope this helps!

**Comment by mhuebert** [comment]
Hm, i think that might be a different issue than what I mean to raise here. I'm not wanting to hide any vars or macros - everything is showing up as intended - except that the label "CLOJURESCRIPT DOCSTRING" seems superfluous. There is both a macro and a cljs var, and only one of them has a docstring, so we could just show that docstring without any platform label. The behaviour for arglists feels correct: since the cljs and macros both have the same arglists, they are not repeated and no labels are necessary (we do not need to see a label like "CLOJURESCRIPT & CLOJURE ARGLISTS:" there)

To your other points - I think the fact that all the public clj entries are _macros_ is significant. They are intended not to serve any purpose for the JVM at all, but rather are consumed from cljs and compile to cljs. (I expect they also work on self-hosted cljs because they don't use any JVM-specific features.) I can't move them into `impl` because they are part of the public api, which is consumed from the `js-interop` namespace. They need to be macros because stuff is happening at compile time, they also need to be functions because they can be applied as fns. Similar to `+` (background: http://blog.fikesfarm.com/posts/2015-12-12-clojurescript-macro-functions.html).

**Comment by mhuebert** [comment]
Thinking a bit more about this. Maybe a question to ask is, "If the same name exists for multiple platforms and/or compilation contexts (eg. macro-time), and only one platform contains a docstring, is it safe to consider this to be the 'canonical' docstring for all usages of the name?"

Clojurescript's `+` macro doesn't have a docstring, but its behaviour is described by the docstring for the function. see [macro-source](https://github.com/clojure/clojurescript/blob/master/src/main/clojure/cljs/core.cljc#L1064), [function-source](https://github.com/clojure/clojurescript/blob/master/src/main/cljs/cljs/core.cljs#L2598)

**Comment by martinklepsch** [comment]
> Maybe a question to ask is, "If the same name exists for multiple platforms and/or compilation contexts (eg. macro-time), and only one platform contains a docstring, is it safe to consider this to be the 'canonical' docstring for all usages of the name?"

This. I'm not sure what the answer is myself. 

Thanks for all the macro info, I assumed you could use different names and that the clj `get` is more of an implementation detail but sounds like it isn't 🙂

**Comment by mhuebert** [comment]
another possibility, grazing into the design pasture, would be to move the platform labels into the margin, eg. something like:

![image](https://user-images.githubusercontent.com/165223/53884083-05f8d900-401b-11e9-8fe6-ec10863fbec8.png)

**Comment by martinklepsch** [comment]
That’s a nice idea!

**Comment by mhuebert** [comment]
Great, I can work on a PR if you like

**Comment by martinklepsch** [comment]
Sounds great, would be very welcome if you think it’s something worth doing :) 

In your screenshot you also have some darker colors left of the details etc. currently everything is white - would be interesting to explore adding a bit more visual hierarchy to that with colors/shadows or through other means. Not something that should be part of this ticket but if you have ideas I’d be happy to hear them. 

(I assume it’s just the background of something like Sketch.app but the thought came up and so I just wanted to mention this.)

**Comment by mhuebert** [comment]
Ah - that darker part, which I thought was intended, was actually just a scrollbar that's visible for the nav column because it has `overflow-y-scroll` (could be `overflow-y-auto`). Not all browsers show that scrollbar by default, and I didn't think too much about it while I was working on this.

Once I have cljdoc running locally to work on this PR I will play around and let you know if I have any other ideas.
