### ISSUE TITLE
Show list of last viewed projects on homepage

### ISSUE THREAD

**Issue by martinklepsch** [cljdoc/cljdoc#282]
We track last viewed docs in localstorage and allow users to access those via `CMD-K`/`CTRL-K`:

<img width="820" alt="screenshot 2019-03-01 at 11 36 46" src="https://user-images.githubusercontent.com/97496/53632876-4ec52200-3c16-11e9-8038-db745fcf5046.png">

This information could also be useful to show on the homepage to allow users to quickly navigate to documentation they recently used without typing/searching much.

Take a look at [`trackProjectOpened`](https://github.com/cljdoc/cljdoc/blob/01102870d1ecb05c577ef593621bd8c396c8baee/js/switcher.js#L21-L39) in `switcher.js` to understand how this information is stored and could be used.

**Comment by kolharsam** [comment]
@martinklepsch is/has anyone worked on this issue? If not, then I'd like to help.

**Comment by martinklepsch** [comment]
@kolharsam I don't think anyone has started to work on this. Please go for it & let me know if you need any help  👍

**Comment by kolharsam** [comment]
@martinklepsch where on the homepage would you want place this information?

**Comment by martinklepsch** [comment]
I'm thinking in the context of this it might also be nice to consolidate this with the examples (rum, kaocha, reitit) shown on the homepage, i.e. if you haven't viewed any docs, we show the examples and if you've viewed some we show links to those. 

Thanks for taking a look at this, I think this will be a pretty nice improvement! 🙂

**Comment by martinklepsch** [comment]
And we can probably remove the search feedback notice too, it's been there long enough I think :)

**Comment by kolharsam** [comment]
@martinklepsch I had a question on local development. 
So, is there I can get faster previews of the changes I make on the clj files? Right now, every time I make changes to the source I restart the server each of those times. 
And also `cider` doesn't seem to connect properly as well. How do you connect with `cider`? This is the first time I'm working with`CLJS`

**Comment by martinklepsch** [comment]
Usually I just "jack in" and then run the following Clojure code in the resulting REPL:
```clj
(require '[cljdoc.server.system])
(in-ns 'cljdoc.server.system)
(require '[integrant.repl])
(integrant.repl/set-prep! #(system-config (cfg/config)))
(integrant.repl/go)
```
And then I just evaluate code through that connection updating the server behavior. After changing some parts of the code (like the routing table) you sometimes need to run `(integrant.repl/reset)`  but I think that doesn't apply for this particular issue. 

I think Cider should be able to start an nREPL server for you but I'm not 100% sure. You can also start one by adding an alias like this and then connecting to the port:
```clj
    :nrepl-server {:extra-deps {nrepl {:mvn/version "0.6.0"} cider/cider-nrepl {:mvn/version "0.22.4"}}
                   :main-opts ["-m" "nrepl.cmdline" "--middleware" "[cider.nrepl/cider-middleware]"]}
```

Hope this helps!

**Comment by kolharsam** [comment]
@martinklepsch to access `localstorage` in `clj` I can make a new utility for that right?

**Comment by kolharsam** [comment]
@martinklepsch have added a draft PR with what I've done so far. I just need some help in figuring out to get the localstorage data into the clojure env.

**Comment by martinklepsch** [comment]
>  I just need some help in figuring out to get the localstorage data into the clojure env.

Since this is all stored in the client we cannot render that information on the server and instead need to use JS to show it. The [`switcher.js`](https://github.com/cljdoc/cljdoc/blob/master/js/switcher.js) file is what shows up when you hit CMD+K and uses the same data from localstorage. 

I think essentially we could implement something like the `Switcher` component in that file bit minus the interactivity for changing results

https://github.com/cljdoc/cljdoc/blob/3ab0001040ae41f4ded4d42eb4286558d367e83f/js/switcher.js#L81-L225

#### To render a component into a div with a specific ID 

https://github.com/cljdoc/cljdoc/blob/3ab0001040ae41f4ded4d42eb4286558d367e83f/js/index.js#L18
