### ISSUE TITLE
Make use of new MrAnderson metadata to exclude "vendor namespaces"

### ISSUE THREAD

**Issue by martinklepsch** [cljdoc/cljdoc#287]
Some projects like `cider/cider-nrepl` include namespaces from other dependencies as copied files, to avoid dependency conflicts. These projects often use [MrAnderson](https://github.com/benedekfazekas/mranderson) to copy those files into their source tree. Since v0.5.1 MrAnderson now adds some additional metadata that will allow us to identify files that have been included by it: https://github.com/benedekfazekas/mranderson/commit/aec6b202a5d37d4e2c1e1d1d6018301c12d6a633

Because those files are usually not relevant to the user of a library we should not show them.

This will require some minor tweaks to our Codox fork here: 

1. https://github.com/cljdoc/codox/blob/cljs-proper/codox/src/codox/reader/clojure.clj#L154 
2. https://github.com/cljdoc/codox/blob/cljs-proper/codox/src/codox/reader/clojurescript.clj#L138

Note that the branch in this repo is `cljs-proper`. Docstrings of the affected functions should also be updated.

Related to #195 but a bit more specific.

**Comment by martinklepsch** [comment]
@lread I just realized that this is probably an easy addition to the analyzer stuff you've been working on. Which reminds me that we should really get it merged 🙈

**Comment by lread** [comment]
Ah yes, awesome idea @martinklepsch !  I'll add it as a todo by adding an issue to cljdoc-analyzer, thanks.

**Comment by lread** [comment]
Transferred to https://github.com/lread/cljdoc-analyzer/issues/4
