### ISSUE TITLE
Handle requires of foreign-libs / npm-deps in CLJS

### ISSUE THREAD

**Issue by Lokeh** [cljdoc/cljdoc#289]
Currently, cljdoc throws an error when analyzing CLJS code that has string requires in the `ns` form, like:

```clojure
(ns foo.bar
  (:require ["baz" :as baz]))
```

Ideally we would not process these requires as they are usually provided by some external package manage like npm.

**Comment by martinklepsch** [comment]
Thomas Heller mentioned on Slack that he previously created an example that showed how to deal with this. So if we sift through the history of the #cljdoc channel maybe we can find that :)

**Comment by mfikes** [comment]
Note that it is probably more accurate to characterize the issue as specifically relating to NPM dependencies, and unrelated to the use of strings. (In other words, it is probably best couched as an NPM-specific variation of #297).

More detail:

Strings can be used for any namespace, and the failure is likely not related to strings _per se_. For example, you can do the following in ClojureScript and analysis of a namespace that required `"clojure.set"` would likely succeed without issue:

```
cljs.user=> (require '["clojure.set" :as my-set-alias])
nil
cljs.user=> (my-set-alias/union #{:a :b} #{:b :c})
#{:b :a :c}
```

**Comment by martinklepsch** [comment]
This has been solved by https://github.com/cljdoc/cljdoc-analyzer/issues/18 and is now live. 

👏 Huge thanks to @frozar who took initiative and figured this all out! 🎉 

Here are the docs for Helix: https://cljdoc.org/d/lilactown/helix/0.0.10
