### ISSUE TITLE
SCM info missing -- when cljdoc.edn has a bad path!

### ISSUE THREAD

**Issue by seancorfield** [cljdoc/cljdoc#290]
https://cljdoc.org/builds/12771 (and previous builds)

I've compared the `pom.xml` `<scm>` tags to two other projects that have been successfully imported on cljdoc and I can't see what's different/wrong. Please advise!

**Comment by seancorfield** [comment]
See this commit and several parents where I tried to satisfy cljdoc...

https://github.com/seancorfield/next-jdbc/commit/74308aa085de0d776a389ea86d10889615f36f1e#diff-600376dffeb79835ede4a0b285078036

**Comment by seancorfield** [comment]
Here's the latest that still fails:
```
  <scm>
    <url>https://github.com/seancorfield/next-jdbc</url>
    <connection>scm:git:git://github.com/seancorfield/next-jdbc.git</connection>
    <developerConnection>scm:git:ssh://git@github.com/seancorfield/next-jdbc.git</developerConnection>
    <tag>c2c798770a8473d5f10b9dddeeafdff6be90f79a</tag>
  </scm>
```
For comparison, here's the section from HoneySQL's pom which seems to have imported just fine:
```
  <scm>
    <url>https://github.com/jkk/honeysql</url>
    <connection>scm:git:git://github.com/jkk/honeysql.git</connection>
    <developerConnection>scm:git:ssh://git@github.com/jkk/honeysql.git</developerConnection>
    <tag>8e3b0073f7282ce2738f16606e42845196a5bcf3</tag>
  </scm>
```

**Comment by seancorfield** [comment]
So it turns out it was nothing to do with the `scm` tag in `pom.xml` -- the problem was that I had a bad filename in my `doc/cljdoc.edn` file (I had `-` instead of `_`) and it was the import of that file that failed the build.

It would be nice if cljdoc reported that failure correctly.

**Comment by martinklepsch** [comment]
Hey Sean, glad you worked it out! There's #111 that is about surfacing those errors better and there is a very basic little script thing you can throw into your CI to catch the "file doesn't exist" situation. It's mentioned at the end of this section here: https://cljdoc.org/d/cljdoc/cljdoc/0.0.1315-c9e9a7e/doc/userguide/for-library-authors#_configuring_articles 

Other issues like the map having the wrong shape are not caught by that script unfortunately, some more discussion/exploration around that has happened in #145 but I ended up not merging that yet. If you want to give it a try and provide feedback that would be very welcome.

**Comment by seancorfield** [comment]
OK, then this feels like a duplicate or at least irrelevant ticket now! :) 

Yeah, I ran that script, which was how I (_eventually_!) figured it out. Very happy with cljdoc now that I'm fully up and running!
