### ISSUE TITLE
Autocomplete in search function in cljdoc website blocked by adblocker (Privacy badger)

### ISSUE THREAD

**Issue by JulienRouse** [cljdoc/cljdoc#291]
[Privacy badger](https://www.eff.org/privacybadger) blocks [clojars](clojars.org) because it detects that is track users on the websites. This breaks the website autocomplete for the search functionality. 

You can whitelist the clojars.org domain in Privacy Badger and reload the page to make the functionality works again but it took me some time to figure it out, and potentially other users might have the same problem (maybe with other adblockers too).

I guess my question is: is there anything that can be done to avoid that functionality being blacklisted by Privacy Badger?

**Comment by danielcompton** [comment]
Do you have any more info on why Privacy Badger is blocking Clojars? There is a Google Analytics tag on the site, but that shouldn't be relevant for the autocomplete searching?

**Comment by JulienRouse** [comment]
I am not really, from what I see it seems when you enter a letters in the search bar, it fires up a request to clojars.org, and that is that request that is blocked by Privacy Badger. Maybe because it is some kind of request to a third party, it is seen at potentially bad/dangerous?

**Comment by martinklepsch** [comment]
Should get fixed by #306.

**Comment by martinklepsch** [comment]
Fixed by #306
