### ISSUE TITLE
/doc/some-file.md links not rewritten consistently

### ISSUE THREAD

**Issue by seancorfield** [cljdoc/cljdoc#292]
I use the same `/doc/friendly-sql-functions.md` link in the `README.md`, the getting started page, the result set builder page, and the `cljdoc.edn` file:

https://github.com/seancorfield/next-jdbc/search?q=friendly-sql-functions.md&unscoped_q=friendly-sql-functions.md

It is correctly rewritten to `/doc/getting-started/friendly-sql-functions` in the `README.md` and result set builder pages, but in getting started, it becomes `/doc/friendly-sql-functions` as you can see at the bottom of:

https://cljdoc.org/d/seancorfield/next.jdbc/1.0.0-alpha12/doc/getting-started

**Comment by martinklepsch** [comment]
@seancorfield thanks for the issue! I revisited that part of code and noticed that all the relativization of paths was really only necessary for offline docs but in return mostly impacted the live environment negatively. I changed to code to always use absolute (`/d/seancorfield/...`) style links in the live environment now and handle the offline case explicitly. 

The links in https://cljdoc.org/d/seancorfield/next.jdbc/1.0.0-alpha12 all work for me now.
