### ISSUE TITLE
Cannot search for projects that aren't on the first page of Clojars's search results

### ISSUE THREAD

**Issue by KingMob** [cljdoc/cljdoc#294]
cljdoc's search uses the first page of Clojars's search results. Unfortunately, it appears major packages like re-frame and com.stuartsierra/component aren't on the first page of Clojars when searching for "re-frame" and "component", respectively.

While this is not great on Clojars's part, at least you can page through the search results. You can't do that at the moment with cljdoc, which means it's currently not possible to look up re-frame's docs by searching.

**Comment by martinklepsch** [comment]
Hey and thanks for the issue @KingMob! There's a variety of issues with search currently which we haven't gotten around to fixing yet — but we'll get there eventually! Take a look at #85 for some further discussion about this. 

In the meantime use the `cljdoc.org/d/{project}` URL pattern to jump to documentation directly.

**Comment by KingMob** [comment]
Ahhh, thanks, I didn't see that issue.
