### ISSUE TITLE
False positive in detecting build failure

### ISSUE THREAD

**Issue by martinklepsch** [cljdoc/cljdoc#299]
https://cljdoc.org/builds/13942 this page says the build failed but there's no exception in the logs and the CircleCI build ran through successfully.

```
INFO [2019-05-22 22:01:27,062] - cljdoc.analysis.service CircleCI: Polling build 5314
INFO [2019-05-22 22:01:28,567] - cljdoc.server.ingest Verifying cljdoc-edn contents against spec
INFO [2019-05-22 22:01:28,567] - cljdoc.server.ingest Importing API into database metosin/reitit-core 0.3.5
INFO [2019-05-22 22:01:28,574] - cljdoc.storage.sqlite-impl version-id 11290
```
The [build artifact](https://5297-162196335-gh.circle-artifacts.com/0/cljdoc-edn/metosin/reitit/0.3.5/cljdoc.edn) for the build contains no namespaces. There are no source files in the artefact so that is correct but maybe this is what hasn't been considered here.

**Comment by victorb** [comment]
Seeing the same.

https://cljdoc.org/builds/13599 says "analysis-job-failed" but CircleCI job is green: https://circleci.com/gh/cljdoc/builder/4960

But, seems that the build job actually wasn't successful, as `We couldn't find any namespaces in this artifact. Most often the reason for this is that the analysis failed or that the artifact has been mispackaged and does not contain any Clojure source files. The latter might be on purpose for uber-module style artifacts. Please open an issue and we'll be happy to look into it.` is visible on the left-hand side when going to https://cljdoc.org/d/open-services/ipfs-api/1.1.0/doc/readme

**Comment by martinklepsch** [comment]
I uploaded a [cljdoc backup here](https://send.firefox.com/download/776595c7e7fec22b/#wfM7_vNG-EhcKrxF_-wjQQ) that should contain both of these builds. Interested contributors can download it and restore it with 

```
tar -xf backup-2019-06-03.tar.gz -C data/
```
And then follow the instructions [here](https://github.com/cljdoc/cljdoc/blob/master/doc/running-cljdoc-locally.md#running-cljdoc-locally) to run cljdoc locally. The [`build_log.clj`](https://github.com/cljdoc/cljdoc/blob/master/src/cljdoc/render/build_log.clj) file would be a good starting point to drop in a couple of `println` or similar :)

**Comment by lins05** [comment]
> https://cljdoc.org/builds/13942 this page says the build failed but there's no exception in the logs and the CircleCI build ran through successfully.

I tried to reproduce the same build locally, but it succeeds here and correctly displays "no namespaces found"

![Screen Shot 2019-11-08 at 6 59 24 PM](https://user-images.githubusercontent.com/717363/68471856-0e647c00-025a-11ea-998f-52bf056048a0.png)
