### ISSUE TITLE
create a cljdoc exerciser project

### ISSUE THREAD

**Issue by lread** [cljdoc/cljdoc#320]
A dedicated project whose sole purpose is to exercise cljdoc features and formatting would be of value.  

I've started [such a project](https://github.com/lread/cljdoc-exerciser) and @martinklepsch mentioned an interest to transfer it over to cljdoc. I am happy to oblige.

I created this git issue to discuss any tasks related to this transfer.

Todos:
- [x] Decide if` cljdoc-exerciser` a good name for this project.  For example `cljdoc-testbed` is another name I thought of.
- [x] Update build/versioning/deploy to conform to cljdoc - no need
- [x] Document build/versioning/deploy in readme
- [x] Transfer to cljdoc github org
- [ ] Test build/deploy from cljdoc

**Comment by martinklepsch** [comment]
Thanks for getting this discussion going Lee!

The name isn't too important, testbed, exerciser etc all convey the core idea sufficiently I think :)

Versioning, deployment etc doesn't have to be streamlined for now as long as it's documented in the readme 🙂 

> Test build/deploy from cljdoc

Not sure what you mean here?

:v:

**Comment by lread** [comment]
Thanks for the response!  By "Test build/deploy from cljdoc" might be reworded to "Verify deploy to clojars after the transfer"

**Comment by lread** [comment]
I have deferred the last todo item to here: https://github.com/cljdoc/cljdoc-exerciser/issues/1
This completes this issue.
