### ISSUE TITLE
Render AsciiDoc code callouts

### ISSUE THREAD

**Issue by lread** [cljdoc/cljdoc#321]
**Current behaviour**
cljdoc renders the following asciidoc callouts:

```asciidoc
[source,clojure]
----
;; some sweet clojure code

(defn hello-earthling
  "Greet an earthling in a believable way."  ;; <1>
  [name]
  (println "Hello earthling " (uppercase name))) ;; <2>
----
<1> a docstring comes before the arguments
<2> check with an earthling if uppercasing is soothing
```
like so:
![image](https://user-images.githubusercontent.com/967328/61217002-bf0fa400-a6dc-11e9-9c52-3fe685e4a0de.png)

As you can see the callouts rendered as (1) and (2) in the code do not catch the eye very well.

**Desired behavior**
The asciidoctor user manual shows callouts  rendered as icons, and so does the browser extension renderer:
![image](https://user-images.githubusercontent.com/967328/61217558-f0d53a80-a6dd-11e9-94c0-0a0159c5b62a.png)

The callouts rendered as icons are much easier to see.
(Ignore the fact that clojure code is not syntax highlighted here, cljdoc will continue to syntax highlight)

**Comment by lread** [comment]
This looks like an easy one, if we specify `:icons:` attribute callouts are rendered as icons.  But... this also switches admonitions to use icons - see #327.

**Comment by lread** [comment]
The docs are misleading, when requesting icon fonts, it seems asciidoctor uses a css only solution - which should be fine for offline viewing.

**Comment by lread** [comment]
Here's a current sample:
![image](https://user-images.githubusercontent.com/967328/61483653-4a9e6480-a96b-11e9-9f0c-aee04cb72e8c.png)

**Comment by martinklepsch** [comment]
Nice, that looks a lot better 👏 🙂

**Comment by martinklepsch** [comment]
Hey Lee! In your work on this have you stumbled upon any way to only use the icon style for these code markers and not for admonitions? I'd be curious if those two things could be addressed/decided on separately.

**Comment by lread** [comment]
Yup, my PR retains but improves upon current cljdoc admonition styling without showing icons.  

Also, like you, I assumed icons are used for code callout markers. They are not.
