### ISSUE TITLE
Give asciidoc table of contents title some oomph

### ISSUE THREAD

**Issue by lread** [cljdoc/cljdoc#322]
**Current behavior**
An asciidoc can optionally automatically include a table of contents via `:toc:`.  cljdoc currently renders an asciidoc toc like so:
![image](https://user-images.githubusercontent.com/967328/61217342-75738900-a6dd-11e9-9f24-5b29ad446ca1.png)

I feel the toc title is not getting the formatting it deserves.

**Desired behavior**
Compare this to formatting from the asciidoc browser plugin (which matches the asciidoc user guide):
![image](https://user-images.githubusercontent.com/967328/61217900-ba4bef80-a6de-11e9-9965-255e912de5ec.png)

**Comment by martinklepsch** [comment]
Yeah that would also be nice. Although we'll have to balance it with the TOC in the sidebar. But I guess we'll manage :)

**Comment by lread** [comment]
Here's my current work in progress. Nothing drastic at all, just respecting that the toc title is a header:
![image](https://user-images.githubusercontent.com/967328/61478421-787dac00-a95f-11e9-8a3d-d072269fb8f6.png)

**Comment by lread** [comment]
Ok not to bore you, but just in case anybody doth want to protest, my latest asciidoc toc styling looks like so:
![image](https://user-images.githubusercontent.com/967328/61919545-1fe07d00-af24-11e9-80a3-d879ecf37715.png)
