### ISSUE TITLE
Asciidoc tables need some formatting love.

### ISSUE THREAD

**Issue by lread** [cljdoc/cljdoc#324]
**Current behavior**
Given the following asciidoc 
```asciidoc
Asciidoc tables are quite full featured, here's a simple one:

|===
| Heading 1 | Heading 2

| col1, row1
| col2, row1

| col1, row2
| col2, row2

| col1, row3
| col2, row3

| col1, row4
| col2, row4
|===

Here's the same table with a title

.This time with a title
|===
| Heading 1 | Heading 2

| col1, row1
| col2, row1

| col1, row2
| col2, row2
|===

And here's a nested table example from asciidoctor user manual:

[cols="1,2a"]
|===
| Col 1 | Col 2

| Cell 1.1
| Cell 1.2

| Cell 2.1
| Cell 2.2

[cols="2,1"]
!===
! Col1 ! Col2

! C11
! C12

!===

|===
```

We currently get:
![image](https://user-images.githubusercontent.com/967328/61218495-2418c900-a6e0-11e9-96ec-2e8aa0618ce1.png)

**Desired behavior**

Let's compare this to the asciidoc browser extension rendering (which matches asciidoctor user guide renderings):
![image](https://user-images.githubusercontent.com/967328/61218582-5e826600-a6e0-11e9-8835-669f28722cf0.png)

And also compare to rendering of tables form CommonMark in a docstring:
![image](https://user-images.githubusercontent.com/967328/61218668-82de4280-a6e0-11e9-9e82-48dfbd928068.png)

A consistent (or at least similar) rendering of tables from CommonMark and asciidoc would be desirable.

**Comment by martinklepsch** [comment]
Absolutely agree, wasn't aware that that was missing 😲

**Comment by lread** [comment]
asciidoc tables are full featured and require quite a bit of css which I am bringing in from [asciidoctor default styles](https://github.com/asciidoctor/asciidoctor/blob/master/data/stylesheets/asciidoctor-default.css#L3).  

This is on the painstaking side and we will want to figure out how to streamline this.  

An issue is that the asciidoc style sheet not only brings in a general look and feel, but also supports asciidoc features that authors will use in their documents.

Perhaps bringing in the default asciidoc stylesheet, then programatically tweaking (and css scoping) it to become cljdocified would be a worthy experiment - unless I run into real trouble, I will leave this out of scope for this issue.

**Comment by lread** [comment]
Here's some sample renderings:
![image](https://user-images.githubusercontent.com/967328/61483392-b3d1a800-a96a-11e9-8285-31c818df753f.png)

By default asciidoctor does not stripe rows anymore, I've enabled striping to match striping we currently do for commonmark.

**Comment by lread** [comment]
I fear bringing in asciidoc css formatting piecemeal each time we see a malformatted or unformatted asciidoc element is going to be nitpicky work.

So I am going ahead with the experiment I mentioned above.

I noticed that [asciidoc uses sass to generate its default css](https://github.com/asciidoctor/asciidoctor-stylesheet-factory/tree/master/sass). Sass allows me to easily generate asciidoc css scoped to our `asciidoc` css class and customize to cljdoc look and feel.

This is nice, but has a trade-off is this solution is over-riding some of our tachyon styles in the asciidoc div.  These tachyon styles must be restored to an acceptable level through sass config.  

I notice also that [tachyon has sass support](https://github.com/tachyons-css/tachyons-sass), I'll see if it will help in anyway to merge our two worlds.

**Comment by lread** [comment]
Coming back to this now.

For posterity: I did an experiment with an AsciiDoc custom renderer that used Tachyons for all styling. This looked interesting until I realized that a user can include inline HTML in their AsciiDoc - at which point I abandoned the experiment.
