### ISSUE TITLE
Images not rendered properly when testing locally

### ISSUE THREAD

**Issue by lread** [cljdoc/cljdoc#325]
**Current behavior**
When testing [locally with cljdoc (non docker method)](https://github.com/cljdoc/cljdoc/blob/master/doc/running-cljdoc-locally.md#running-cljdoc-locally), I am finding that images are not showing up.

Note that `test-image-1.png` exists under `doc/`.

For the following markdown
```markdown
Images
--------
When bringing in a README.md for with `cljdoc.edn`, its will be referenced by `doc/README.md`. Are image links automatically fixed up?

Let's link to an image in a subdir with markdown syntax:
![alt for test image 1](doc/test-image-1.png "test image 1 text")

And again with html syntax:
<img src="doc/test-image-1.png" alt="alt for html test image 1"/>

```
Testing locally, I get:
![image](https://user-images.githubusercontent.com/967328/61219439-398ef280-a6e2-11e9-8471-be21e0e73bf1.png)

For the following asciidoc
```asciidoc
This local image should work on github and cljdoc.  According to asciidoctor, images are resolved relative to the document.

Current value of imagesdir:

[subs=attributes+]
----
{imagesdir}
----

image:test-image-1.png[A local test image should appear here]

How about captions, do we display those nicely?

.Test image caption
image:test-image-1.png[A local test image should appear here]
```
Testing locally, I see:
![image](https://user-images.githubusercontent.com/967328/61219628-9d192000-a6e2-11e9-89e5-b897c607a329.png)

**Desired behavior**
When deployed to cljdoc prod, I see what I expect to see locally.

Markdown:
![image](https://user-images.githubusercontent.com/967328/61219712-cdf95500-a6e2-11e9-9915-3e7169a502dc.png)

asciidoc:
![image](https://user-images.githubusercontent.com/967328/61219736-e23d5200-a6e2-11e9-91e6-04473e4d7042.png)

For full context see: https://github.com/lread/cljdoc-exerciser/tree/v1.0.3

**Comment by martinklepsch** [comment]
I think the issue is that when testing locally you provide a git repo as a local path and your web browser can't load the file because it's outside the document root. You could probably verify that by checking the generated HTML and specifically the `<img src>` attribute.

I don't have a clear suggestion on how this could be solved right now.

**Comment by lread** [comment]
For production:
```
<img src="https://raw.githubusercontent.com/lread/cljdoc-exerciser/v1.0.3/doc/test-image-1.png" alt="alt for html test image 1">
```
Local is odd (even without document root problem):
```
<img src="https://raw.githubusercontent.com/Users/lee/v1.0.3/doc/test-image-1.png" alt="alt for html test image 1">
```

I expect we could figure something out?  I can explore options if you like.

**Comment by lread** [comment]
I did a little poking around and found a solution.

[Adobe's git-server](https://github.com/adobe/git-server) allows us to run an github api compatible server locally.  If we fetch our images from this local server instead of github, we are golden.  I think our image fetch is currently hardcoded to `https://raw.githubusercontent.com`, but that could change.

Actually, I suppose we could just talk to our local git-server for everything git when running locally.  Maybe the dockerfile solution for running locally (something I have not yet tried) could startup a local git-server as well.

I'll do a little more exploring.

**Comment by lread** [comment]
As I study the code, it seems to me that raw images are fetched via raw.githubusercontent.com regardless of whether or not the the repo is hosted on github.

A more generic pattern that seems to work across github, bitbucket and gitlab is the insertion of `raw` after `user/project`, examples:
 https://github.com/cljdoc/cljdoc/raw/1e55cf3256b5380ded73da65aeaedd9a56d4fa41/README.md

https://bitbucket.org/atlassian/stash-example-plugin/raw/a6e5e7d797edf751cbd839d6bd4aef86c941eec9/LICENSE

https://gitlab.com/gitlab-examples/julia/raw/24a1cb01275e4eb4fd8d0c97ad1189cc6d6e5c4e/README.md

**Comment by lread** [comment]
Just noticed #269 which is pretty much the same issue as this one.

**Comment by lread** [comment]
A solution is provided by #415.
