### ISSUE TITLE
When using CommonMark in docstrings, docstring can visually dominate

### ISSUE THREAD

**Issue by lread** [cljdoc/cljdoc#326]
**Current Behavior**
When no strong formatting is used in docstrings, things look nice, for example:
https://cljdoc.org/d/reagent/reagent/0.9.0-SNAPSHOT/api/reagent.core

But if we have a look at this test sample with docstrings that use some strong CommonMark formatting: 
https://cljdoc.org/d/lread/cljdoc-exerciser/1.0.3/api/cljdoc-exerciser.core
I find the structure of document which normally stands out is lost to the docstring formatting.

**Ideas**
This one needs discussion, I think.  Here are some initial ideas:
1. Suggest that folks don't use strong formatting in docstrings in cljdoc user guides.
1. Consider strengthening structure of document through styling such as indenting, coloring, etc.
1. Consider weakening the prominence of strong docstring formatting through styling such as coloring, size reduction, etc.

**Comment by martinklepsch** [comment]
When you say "strong" do you refer to `<strong>` or just using lots of formatting features? Note that authors can also use real headings which is even more problematic in this context.

I think we'll probably want to do a mix of 2 and 3 if we decide to address this. Getting people to change their stuff is always an uphill battle 😆

**Comment by lread** [comment]
I am referring to the general "strong" - as in visually dominant.

**Comment by lread** [comment]
We can re-open this if we think we want to something here in the future.
