### ISSUE TITLE
Are we happy with asciidoc admonitions formatting?

### ISSUE THREAD

**Issue by lread** [cljdoc/cljdoc#327]
**Current behavior**
Given the following asciidoc:
```asciidoc
== Admonitions

NOTE: Note that this note is a note.

TIP: Tip the scales with a tip.

IMPORTANT: Important things are said here.

CAUTION: Aren't you a caution?

WARNING: Warning to the wise.
```
cljdoc currently produces:
![image](https://user-images.githubusercontent.com/967328/61221564-c936a000-a6e6-11e9-83cf-e8efe6b7524b.png)

**Behavior to consider**
Let's compare this to the asciidoc browser extension rendering (which matches asciidoctor user guide renderings):
![image](https://user-images.githubusercontent.com/967328/61221576-d3589e80-a6e6-11e9-975f-54311198caec.png)

I don't know if going with text and coloring over icons was a conscious design decision so I bring it up in this issue for discussion.

**Comment by martinklepsch** [comment]
This was a partly conscious decision and the same applies to #321 as you already pointed out.

I find Asciidoctor's standard styles could be more prominent. I'm also not sure if/how the icons will work with offline documentation. Are they loaded from a server or embedded into the document somehow? 

Generally matching Asciidoctor's output exactly hasn't been a goal for me but it is important that most Asciidoc features can be used and are supported as in that they can be used by authors to guide readers.

**Comment by lread** [comment]
It looks like [offline viewing is supported](https://asciidoctor.org/docs/user-manual/#icons)

> If you want icons to display using images, set the icons attribute to an empty value in the document header. This strategy is recommended if you are converting to DocBook or you want an easy way to make HTML for viewing offline. The DocBook toolchain provides images for the admonition and callout icons, which you can replace with your own custom icons. If you use the inline icon macro, you’ll need to provide the images for those icons.

But we'd have to test, of course.

**Comment by lread** [comment]
I think I have found a way to stick with the textual representation while still supporting #321, and I propose, unless there is strong interest in icons, that we do that for now.

I suppose we should style the currently unstyled CAUTION admonition (see screenshot above).

If I look at the spirit of asciidoc admonitions, it seems a bit fuzzy but maybe they were inspired by ansi safety standards [which I found summarized here](https://www.mysafetysign.com/ansi-safety-sign-standards). Here's my thinking on coloring:
1. IMPORTANT (might be = Danger?) - death possible RED (currently yellow)
1. WARNING - serious injury possible ORANGE (currently red)
1. CAUTION - minor injury possible YELLOW (currently white)
1. NOTE - informational not related to safety BLUE (no change)
1. TIP - not on the ansi list - means opportunity to me - GREEN (no change)

If this makes sense, it could become our definition and we could add to cljdoc docs.

**Comment by lread** [comment]
Here's my current color scheme for review by anyone with an opinion.

I stuck with [tachyon colors](https://tachyons.io/docs/themes/skins/) reusing colors where I could.
![image](https://user-images.githubusercontent.com/967328/61478016-a3b3cb80-a95e-11e9-8e84-8969e1c417c4.png)

**Comment by martinklepsch** [comment]
Looks good to me. I'd suggest to remove the italics on the "WARNING", "NOTE" etc because the words, standing alone and being all upper case, already seem emphasised enough. But either is fine. 🙂 

Thank you! 🙏

**Comment by lread** [comment]
Good point, thanks, will do!
In my testing I have found that a bit of whitespace below each admonition helps with readability and will add that too.

**Comment by lread** [comment]
After much testing, I am finding admonitions hard on the eyes, especially when they contain code.
@martinklepsch  (and anyone else who has opinions), I don't know how married you are to current formatting, but I think the following is an improvement.  To the left is current rendering, to the right is proposed rendering:
![image](https://user-images.githubusercontent.com/967328/61594149-28e4ed80-abb6-11e9-817d-fe785bbe4bf7.png)
