### ISSUE TITLE
Consider using clj-kondo

### ISSUE THREAD

**Issue by lread** [cljdoc/cljdoc#332]
I am finding [clj-kondo](https://github.com/borkdude/clj-kondo) a great tool to catch errors and cruft in Clojure source.   

I propose that we set it up for cljdoc.

This would mean adding a clj-kondo config to the project.

Depending on how far we want to go, it might also mean failing the build if clj-kondo finds any problems.

If you agree this is interesting, I should be able to handle this (unless someone else is itching to do this?).

**Comment by martinklepsch** [comment]
That’s interesting and I think it would be a great addition to the tooling provided around working on cljdoc. ☺️

**Comment by lread** [comment]
@martinklepsch, I should probably describe linting somewhere for cljdoc developers.  

I see [CONTRIBUTING.adoc](https://github.com/cljdoc/cljdoc/blob/master/CONTRIBUTING.adoc) and [doc/running-cljdoc-locally.md](https://github.com/cljdoc/cljdoc/blob/master/doc/running-cljdoc-locally.md) but I don't think either are good fits.  Do you?

Should we create a `doc/for-cljdoc-developers.adoc` doc as a place to describe such things?
