### ISSUE TITLE
Build error when processing clindex 0.2.3

### ISSUE THREAD

**Issue by jpmonettas** [cljdoc/cljdoc#365]
Hi! I'm seeing this build fail https://circleci.com/gh/cljdoc/builder/12709 when processing https://github.com/jpmonettas/clindex

Looking at the logs it looks like codox uses `tools.namespace 0.2.11` but clindex uses and needs  a forked version of it `jpmonettas/tools.namespace 0.3.2` which is basically `tools.namespace 0.3.2-SNAPSHOT`

**Comment by jpmonettas** [comment]
@martinklepsch thanks for that and also let me say thanks for cljdoc!
Yeah probably there is some overlap since parts off both projects are trying to accomplish the same thing. Probably cljdoc-analyzer is currently extracting much more information but just open a issue with whatever you would like to see in that index and let me see if I can help.

My idea is to build a general purpose index for projects like cljdoc so will be adding more stuff to it for sure.

**Comment by martinklepsch** [comment]
> My idea is to build a general purpose index for projects like cljdoc so will be adding more stuff to it for sure.

Do you mean "index" as in a publicly available data source or is that a typo and you meant "indexer"? I don't think the cljdoc analyzer gets us that much more. I think you might even have some stuff that we don't like extracting the source etc (https://github.com/cljdoc/cljdoc-analyzer/issues/17). 

Anyway, we just split out the `cljdoc-analyzer` project recently and are still not using it in production so I could imagine that @lread (who led this) and I will probably not invest a lot of time in this area in the near future...

Maybe it would be interesting for clindex to be able pull data from cljdoc? So far we don't really have an API but if we have a good use case maybe that'll change.

**Comment by jpmonettas** [comment]
Yeah sorry, I meant general purpose indexer. 
Haven't read cljdoc-analyzer code yet but it could be an option. Currently clindex is splitted in two, scanner.clj (download all deps, read all files and create a big namespaces map with info) and indexer.clj which walks all that and create datoms. 

When I find some free time I will try to figure out the cljdoc api, probably clindex can grab some more info from there, thx.

I'm also currently working on https://github.com/jpmonettas/clograms, which is a diagram tool for creating diagrams and exploring clojure codebases using this index.
Too soon to say anything but maybe can complement cljdoc somehow.

**Comment by jpmonettas** [comment]
Thanks @lread ! 
Looking at crossclj it looks like it is doing something similar to clindex but over tools.analyzer ast.
I think in the future I'll collect from tools.analyzer ast some of the stuff I'm currently collecting with some hand made form parsing.

**Comment by SevereOverfl0w** [comment]
This is building now! https://cljdoc.org/builds/32182 (not sure what changed, but something did)

**Comment by martinklepsch** [comment]
Great! Closing this then :)
