### ISSUE TITLE
namespace analysis failed on μ/log

### ISSUE THREAD

**Issue by BrunoBonacci** [cljdoc/cljdoc#366]
I got an error during the the source code analysis  of one of my libraries **μ/log**
here is the build report:
https://cljdoc.org/builds/22014

I can't understand the error message, is there a way to see  full report `/tmp/clojure-4722426010063847863.edn` ?

thanks

**Comment by BrunoBonacci** [comment]
that was my issue, my bad.

**Comment by martinklepsch** [comment]
Hey Bruno, great you got things sorted in the end :) Unless it’s super specific it might be helpful for others to document the problem here - only if you think it’s worth it :)
