### ISSUE TITLE
Implement catch-all to avoid Pedestal "stylobate" catch-all

### ISSUE THREAD

**Issue by martinklepsch** [cljdoc/cljdoc#367]
Pedestal's default catch-all interceptor logs the entire content which can get big. Huge log lines seem to impact responsiveness of the server so we should probably implement our own handling of these unhandled exceptions. For now a simple log line with the exception class and message might be enough.

**Comment by Hindol** [comment]
I can take this one. Have a little experience with Pedestal interceptors as well on a hobby project.

**Comment by martinklepsch** [comment]
Sounds great, let me know if you have any questions along the way!

**Comment by Hindol** [comment]
Hi @martinklepsch, I have added an interceptor but not finding the right place to plug this in routes. Can you help?

**Comment by martinklepsch** [comment]
@Hindol sorry it took me so long to get back to this :) I think if we add the error handler here we should be good: 

https://github.com/cljdoc/cljdoc/blob/8b0ab9f233b8efed432011fad2b97c5aefbcac6c/src/cljdoc/server/pedestal.clj#L478

That said I am seeing that the `sentry/interceptor` also already catches errors and returns error pages which makes me think that something else might be wrong 🤔

**Comment by Hindol** [comment]
Oh yeah, I have seen `An exception occurred, sorry about that!` many times myself which means it does catch some of the exceptions.

Under what circumstances did you see uncaught errors?

**Comment by lread** [comment]
Am looking at logs, and yeah, these unhandled exceptions are pretty distracting and... big!
The ones I see seem to be related to broken pipes. 

```
Caused by: java.io.IOException: Broken pipe
```

Is this simply a user clicking on something else before a request is fully served, so the browser cancels the request?

**Comment by lread** [comment]
Yeah, this seems to be at least one cause of the broken pipe error.
I can trigger this error by navigating to amazonica docs, clicking on the first namespace link, then immediately clicking on the Readme link.

![image](https://user-images.githubusercontent.com/967328/152864292-3cec212c-476b-4f2c-bf8d-b2dbb8f4300c.png)

**Comment by lread** [comment]
Ok, the broken pipe case I described seems to be a known pedestal issue.

@tonsky [blogged about it](https://tonsky.me/blog/pedestal/#running-the-app), then [offered a PR to fix](https://github.com/pedestal/pedestal/pull/621), but this was rejected in [favour of adding more generic support](https://github.com/pedestal/pedestal/issues/623), which is, as of this writing still an open issue.

Being practical people, I think we can steal the hack @tonsky came up with in his blog.

**Comment by lread** [comment]
I'll go ahead and try this out and create a PR.

**Comment by tonsky** [comment]
:)
