### ISSUE TITLE
Search: Add `all-docs` variant for group/artifact, remove caching

### ISSUE THREAD

**Issue by holyjak** [cljdoc/cljdoc#369]
Implement suggestions from the comments in #368 (see also the TODO next to `cljdoc.server.search.search/all-docs`).

**Comment by lread** [comment]
Here's the TODO:
https://github.com/cljdoc/cljdoc/blob/5613fd745c3ff00a2ae882cb4250f2dda1326ce7/src/cljdoc/server/search/search.clj#L210-L211

@holyjak do you think this is this still relevant/needed? We seem to be doing ok without doing it?

**Comment by lread** [comment]
Never mind, I see what you meant now, and makes sense! 🙂 

So instead of caching we instead search lucene index directly.

**Comment by lread** [comment]
Was thinking of getting to this todo, and thought I should first determine what relies on it:
## Usages

1. returning all docsets via https://cljdoc.org/versions - I either did not realize this existed or forgot about it. Do we really need this? 
1. returning versions for artifact with a list of other docsets via, ex: https://cljdoc.org/versions/amperity/greenlight
1. returning all docsets for a group via, ex: http://localhost:8000/versions/amperity

Oh I see that maybe Dash relies (or at one point relied) on all of these? https://github.com/cljdoc/cljdoc/issues/350
I know it currently uses 2 and 3, not sure about 1 (need for that might have gone away when Dash started to use our search api).

The oddly (to me) named `?all=true` param seems important for Dash.
Not sure exactly what it means yet.

## WIP...
I'll come back later and dig in more.

**Comment by lread** [comment]
So, I think the `all=true` param is to support Dash, but is available to be rendered as HTML on the cljdoc site. Ex: https://cljdoc.org/versions/com.atomist/api-cljs?all=true

I think we could modify the HTML version descriptive text to be more clear.

It currently always reads:
> Known versions on cljdoc:

I think we could instead say:
> Built versions on cljdoc:

And when `all=true` is specified:
> All available versions, not necessarily yet built by cljdoc.
