### ISSUE TITLE
Badge is broken when build fails

### ISSUE THREAD

**Issue by borkdude** [cljdoc/cljdoc#371]
Build links:
- https://cljdoc.org/builds/23579
- https://circleci.com/gh/cljdoc/builder/14850

Badge:  
<img width="622" alt="Screenshot 2019-12-19 11 32 18" src="https://user-images.githubusercontent.com/284934/71185508-db130500-227b-11ea-9693-0db4776400c1.png">

**Comment by lread** [comment]
@borkdude, what do you think should happen here?  Should we show some sort of cljdoc failed badge?

**Comment by lread** [comment]
I think this was fixed. Example (as of this writing) from [orchard](https://github.com/clojure-emacs/orchard):

![image](https://user-images.githubusercontent.com/967328/156628698-b2961692-29a3-4da3-84bd-1c238498b390.png)
