### ISSUE TITLE
Cannot easily rebuild even for simple failure

### ISSUE THREAD

**Issue by cloojure** [cljdoc/cljdoc#374]
For some reason I got a build error when cljdoc couldn't download joda-time:

    https://circleci.com/gh/cljdoc/builder/15969 

Apparently regular users can't request a re-build.  Is it possible to fix this so I don't have to make a noop commit/deploy to clojars?

Thanks,
Alan

**Comment by martinklepsch** [comment]
<img width="256" alt="Screen Shot 2020-04-13 at 14 13 13" src="https://user-images.githubusercontent.com/97496/79119581-f8bb2b80-7d90-11ea-90e1-454a3edf565c.png">

There's a somewhat hidden rebuild button that only shows on hover on every documentation page. Hope this helps!
