### ISSUE TITLE
README doesn't match version on GitHub

### ISSUE THREAD

**Issue by patrickaroo** [cljdoc/cljdoc#379]
The example code at https://cljdoc.org/d/reaver/reaver/0.1.2/doc/readme does not work as the url in the example code should be for ycombinator not reddit. Clicking the 'edit on github' link takes one to the correct example in the README on GitHub. However, the README displayed on cljdoc does not match the GitHub version.

**Comment by martinklepsch** [comment]
Only on the phone right now but I assume there hasn’t been a new release of the library after the readme has been updated? 

On cljdoc all documentation is tied to a SHA within your repository to make sure it’s „in sync“ with the code released. 

Hope this helps.
