### ISSUE TITLE
"An exception occurred, sorry about that!" when I try to view docs for my lib

### ISSUE THREAD

**Issue by oskarkv** [cljdoc/cljdoc#394]
I went to this page https://cljdoc.org/d/oskarkv/utils/0.1.0/api/oskarkv.utils and got "An exception occurred, sorry about that!". I have no clue what's wrong. Another library of mine that I uploaded to Clojars at about the same time works fine.

**Comment by martinklepsch** [comment]
This seems to be the exception causing this error:
```
Caused by: java.lang.UnsupportedOperationException: count not supported on this type: Symbol
	at clojure.lang.RT.countFrom(RT.java:671)
	at clojure.lang.RT.count(RT.java:643)
	at clojure.core$count.invokeStatic(core.clj:880)
	at clojure.core$count.invoke(core.clj:874)
	at clojure.core$sort_by$fn__5978.invoke(core.clj:3131)
	at clojure.lang.AFunction.compare(AFunction.java:51)
	at java.util.TimSort.countRunAndMakeAscending(TimSort.java:355)
	at java.util.TimSort.sort(TimSort.java:220)
	at java.util.Arrays.sort(Arrays.java:1438)
	at clojure.core$sort.invokeStatic(core.clj:3115)
	at clojure.core$sort_by.invokeStatic(core.clj:3119)
	at clojure.core$sort_by.invokeStatic(core.clj:3119)
	at clojure.core$sort_by.invoke(core.clj:3119)
	at cljdoc.render.api$render_arglists.invokeStatic(api.clj:66)
	at cljdoc.render.api$render_arglists.invoke(api.clj:65)
	at cljdoc.render.api$def_block$iter__24436__24440$fn__24441.invoke(api.clj:89)
```
I unfortunately don't have time to fix it myself right now but if you take a look at [running cljdoc locally](https://github.com/cljdoc/cljdoc/blob/master/doc/running-cljdoc-locally.md) this should probably something easy to fix. 

Thanks for reporting! :)

**Comment by lread** [comment]
@oskarkv, I found some time to take a peek.

From the stack trace that @martinklepsch shared we can see that there is some problem with rendering arglists:
```
      at cljdoc.render.api$render_arglists.invokeStatic(api.clj:66)
```

Cljdoc uses [cljdoc-analyzer](https://github.com/cljdoc/cljdoc-analyzer) to parse source code metadata. I used it to parse your project like so:

```
clojure -m cljdoc-analyzer.main analyze \                                  
  --project oskarkv/utils --version "0.1.0" \
  --output-filename "oskarkv-utils-0.1.0.edn"
```
I used [jet](https://github.com/borkdude/jet#installation) to pretty print the resulting edn like so:
```
cat oskarkv-utils-0.1.0.edn | jet --pretty > oskarkv-utils-0.1.0-pretty.edn
```

I then had a peek.  Some of the `:arglists` look odd, for example under analysis for `cljs` we have:
```Clojure
                               {:name iterate-some-str,
                                :file "oskarkv/utils.cljc",
                                :line 717,
                                :arglists (quote nil),
                                :doc "Like `iterate-some`, but applies `str` to the result.\n",
                                :type :var}
```
This `:arglists` is cause of the failure you reported.

Under analysis for `clj` the same function's `:arglists` looks good:
```Clojure
                              {:name iterate-some-str,
                               :file "oskarkv/utils.cljc",
                               :line 717,
                               :arglists ([f x]),
                               :doc "Like `iterate-some`, but applies `str` to the result.\n",
                               :type :var}
```

I see that the library [does some fancier footwork to bring these functions to life](https://github.com/oskarkv/clojure-utils/blob/6fc51cbc2769560b21b0451d93439123ed279b36/src/oskarkv/utils.cljc#L717), could it be that this is not yet fully working under ClojureScript?

**Comment by lread** [comment]
@martinklepsch, I can't remember if our [spec](https://github.com/cljdoc/cljdoc-analyzer/blob/fc0c60d5242588bfd37feeccd8d632d5fb5807c8/src/cljdoc_analyzer/spec.cljc#L15) should catch this type of issue on analysis/ingest.  Probably?

**Comment by lread** [comment]
Seems to render now.
