### ISSUE TITLE
Support for mixed projects

### ISSUE THREAD

**Issue by dAnjou** [cljdoc/cljdoc#396]
Hi,

I'm working on the docs for my Clojure project that includes Java components: https://gitlab.com/dAnjou/clj-mdc.

Is there a way to include Java docs as well?

Thanks!

**Comment by frozar** [comment]
I'm pretty sure the support of Java docs is not the target of `cljdoc` project but this should be confirmed by @martinklepsch

**Comment by martinklepsch** [comment]
Hi @dAnjou! As @frozar already said, javadocs aren't in scope for cljdoc.

![](https://media1.tenor.com/images/2c9ec222fb909caad79735a4a2c1520e/tenor.gif?itemid=11802085)
