### ISSUE TITLE
Avoid duplicate Google results for the same documentation

### ISSUE THREAD

**Issue by martinklepsch** [cljdoc/cljdoc#397]
<img width="911" alt="Screen Shot 2020-05-29 at 10 56 13" src="https://user-images.githubusercontent.com/97496/83241439-20c4e980-a19b-11ea-8b33-e5eeb22c8fd0.png">

We're already setting `rel="canonical"` to the version of the documentation at the latest version:
```
<link href="https://cljdoc.org/d/clj-kondo/clj-kondo/2020.05.09/doc/configuration" rel="canonical">
```
What else can we do?

**Comment by lread** [comment]
Absolute SEO noob here, so review with a critical eye:

This [article](https://seoasoorm.com/url-canonicalization/#method-2-setting-canonicals-in-sitemaps) suggests that our sitemap should only contain our canonical URLs.

Our `sitemap.xml` currently includes all versions.

Reducing the sitemap to list only the most current release URLs would also help reduce the number of URLs.
50k entries is the limit before a [sitemap needs to be broken down](https://developers.google.com/search/docs/advanced/sitemaps/large-sitemaps).
It think we are currently above 45k entries.
