### ISSUE TITLE
Support ?q=search-term query param on home page

### ISSUE THREAD

**Issue by martinklepsch** [cljdoc/cljdoc#398]
We have support to specify the search term up front on https://cljdoc.org/search?q=abc via the `q` query param. It would be nice to also add support for this query parameter to the homepage. cc @kolharsam

**Comment by vhawk19** [comment]
Has anyone worked/working on this? If it is beginner-friendly I'd really like to try it out!

Also to clarify, this would mean that if somebody visits https://cljdoc/search?q=rei then it should load the results on the homepage right?

**Comment by lread** [comment]
Done a long while ago, it seems! 🙂 Closing!
