### ISSUE TITLE
API analysis for Pathom fails

### ISSUE THREAD

**Issue by cldwalker** [cljdoc/cljdoc#400]
Hi. Thanks for the awesome project.

I noticed the [latest pathom docs](https://cljdoc.org/d/com.wsscode/pathom/2.3.0-alpha9/doc/readme) aren't displaying the namespaces docs. The failing build step exits with 137 which I believe is an out of memory error. Is this related to #46? Any thoughts on what could be going wrong? 

The last version of pathom docs that seems to have namespaces working is [2.2.31](https://cljdoc.org/d/com.wsscode/pathom/2.2.31/doc/readme). 

Cheers

**Comment by martinklepsch** [comment]
Upon re-running this I see the following error:
```
Caused by: clojure.lang.ExceptionInfo: No such namespace: cljsjs.react, could not locate cljsjs/react.cljs, cljsjs/react.cljc, or JavaScript source providing "cljsjs.react" in file file:/home/circleci/.m2/repository/fulcrologic/fulcro/2.6.0/fulcro-2.6.0.jar!/fulcro/client/primitives.cljc {:tag :cljs/analysis-error}
```
I made a change to the analyzer to stub out `cljsjs.react` and upgraded the analyzer in cljdoc. See referenced commits. Should be in prod in a couple of minutes. 

There's a hidden button next to the GitHub link on cljdoc that you can use to trigger rebuilds. 
![CleanShot 2020-06-04 at 11 14 25@2x](https://user-images.githubusercontent.com/97496/83738463-a261bf00-a654-11ea-94cd-2238adfc35a6.png)

**Comment by cldwalker** [comment]
Thanks for the fix and quick turnaround!
