### ISSUE TITLE
Analysis fails when parsing function, can't figure out why

### ISSUE THREAD

**Issue by aaronEberhart** [cljdoc/cljdoc#406]
Hey sorry to be a bother, I'm new at clojuredocs. This could be a bug or could be me.
I have a function that runs fine in multiple devices/environments but seems to crash analysis. It is a big case statement on map keys (case (:key map) ... ) and returns a string. When analysis reads the line with my final default case (key not in map, or not map) it spits out:

class java.lang.String cannot be cast to class clojure.lang.IFn (java.lang.String is in module java.base of loader 'bootstrap'; clojure.lang.IFn is in unnamed module of loader 'app')

This does not happen with lein or clj when I run it. Refactorered the function name in case it was conflicting with something in clojuredocs, no effect. 

Not a big deal honestly, probably I'm just confused

Java version 11.0.8
Clojure version 1.10.1
ClojureScript version 1.10.773
Analyzing for clj

**Comment by SevereOverfl0w** [comment]
Could you link the failing build? That will help us diagnose.

**Comment by aaronEberhart** [comment]
Here is the notice on cljdoc (I tried a few times to debug it so I can send others)
https://cljdoc.org/builds/33208
Here is the circleci
https://app.circleci.com/pipelines/github/cljdoc/builder/8057/workflows/9d9902ae-a4cb-4e28-a327-72a134334200/jobs/24434

**Comment by aaronEberhart** [comment]
Caught it. Works now.

I was messing with the print-method for certain persistent maps. Usually this was working fine on my end, but there must be some conflicts somewhere.

Thanks.
