### ISSUE TITLE
Run analysis failed for zero.one/geni

### ISSUE THREAD

**Issue by anthony-khong** [cljdoc/cljdoc#407]
Here's the failed job:

https://app.circleci.com/pipelines/github/cljdoc/builder/8138/workflows/ecc92520-4684-4131-9c2e-c0300101860c/jobs/24515

Specifically it says "Could not find artifact com.github.fommil.netlib:all:jar:1.1.2", but the build works locally and on Github actions. The project.clj can be found here: https://github.com/zero-one-group/geni/blob/develop/project.clj. I suspect it is due to `[com.github.fommil.netlib/all "1.1.2" :extension "pom"]`? How can I solve the error?

Any help would be greatly appreciated! Thanks!

**Comment by lread** [comment]
I think your guess is correct @anthony-khong. 

The cljdoc analyzer uses [clojure tools.deps](https://github.com/clojure/tools.deps.alpha) to resolve dependencies which does not support maven bill of materials dependencies.

The normal work-around, should you want to try it, is to specify the individual dependencies in [com.github.fommil.netlib/all](https://repo1.maven.org/maven2/com/github/fommil/netlib/all/1.1.2/all-1.1.2.pom) one by one.

But... this bom includes `natives` and I'm thinking that won't work with tools.deps either.

Hmm...
