### ISSUE TITLE
Search UI

### ISSUE THREAD

**Issue by martinklepsch** [cljdoc/cljdoc#41]
For various purposes it would be nice if users (and machines) could search for available documentation on cljdoc. This could be a simple JSON API a la

```
/api/search?q=reagent
```

This will need to query all group and artifact IDs from grimoire (`list-groups`, `list-artifacts`) and return the results in some useful format.

**EDIT** Maybe [Clojar's search API](https://github.com/clojars/clojars-web/wiki/Data#json-search-results) is already sufficient?

**Comment by martinklepsch** [comment]
Given that [Clojars' own search API](https://github.com/clojars/clojars-web/wiki/Data#json-search-results) is probably sufficient I'm renaming this issue to just **Search UI**. 

For now I'm thinking it could be just a simple page `/search` with a single input field. Results should be shown as the user types. Clicking on a result should bring the user to the documentation page for the chosen artifact. (Later on we may automatically trigger a build when users navigate to packages for which we haven't built documentation).

This will involve some JS but I'd like to avoid pulling in any additional build-steps at this point. Plain JS files and pulling in dependencies via unpgk.com or similar would be preferable.

**Comment by martinklepsch** [comment]
I just pushed a v1 of this: https://cljdoc.xyz/ 

Clojars' search isn't all that great for a few reasons:

- There's no ordering based on how much a thing matches, i.e. if I type `reagent` a lot of other things will be returned and the "perfect match" won't be shown first.
- I think in some cases it may even be that the "perfect" match is on the second page of the search results, which [are not retrievable](https://github.com/clojars/clojars-web/pull/697).
- UI could obviously be improved, it's usable though.

**Comment by danielcompton** [comment]
Sorry for the delay on the other PR!

**Comment by martinklepsch** [comment]
@danielcompton no worries! I was mostly able to do what I wanted so no pressure in any way 👍

**Comment by martinklepsch** [comment]
Lets consider this done and open more specific issues for improvements.
