### ISSUE TITLE
find-neighbour-articles unit test sometimes fails

### ISSUE THREAD

**Issue by lread** [cljdoc/cljdoc#411]
Heya cljdoc team! I am working on some cljdoc code so am running tests continuously.

I am noticing that [cljdoc.doc-tree-test/find-neighbour-articles](https://github.com/cljdoc/cljdoc/blob/bd81458d1698b3ffcbbf98f16e711ac7d52ef39e/test/cljdoc/doc_tree_test.clj#L38) is sometimes failing.

So I switched to master and I tried the following from bash:
```shell
for run in {1..100}; do clojure -A:test --focus cljdoc.doc-tree-test/find-neighbour-articles; done
```
And got 96 success and the following 4 failures:
```clojure
unit:   100% [==================================================] 1/1

Randomized with --seed 385646933
FAIL in cljdoc.doc-tree-test/find-neighbour-articles (doc_tree_test.clj:60)
find neighbour entries in doc-tree by slug-path Last element in tree have no next neighbour
expected: (->> example-tree doctree/flatten* reverse first :attrs :slug-path (doctree/get-neighbour-entries example-tree) last nil?)
  actual: false
1 tests, 3 assertions, 1 failures.
```

```clojure
unit:   100% [==================================================] 1/1

Randomized with --seed 765016617
FAIL in cljdoc.doc-tree-test/find-neighbour-articles (doc_tree_test.clj:60)
find neighbour entries in doc-tree by slug-path Last element in tree have no next neighbour
expected: (->> example-tree doctree/flatten* reverse first :attrs :slug-path (doctree/get-neighbour-entries example-tree) last nil?)
  actual: false
1 tests, 3 assertions, 1 failures.
```

```clojure
unit:   100% [==================================================] 1/1

Randomized with --seed 590040495
FAIL in cljdoc.doc-tree-test/find-neighbour-articles (doc_tree_test.clj:53)
find neighbour entries in doc-tree by slug-path Any not first and not last entry in tree have two neighbours
expected: (->> example-tree second :attrs :slug-path (doctree/get-neighbour-entries example-tree) (every? (complement nil?)))
  actual: false
1 tests, 3 assertions, 1 failures.
```

```clojure
unit:   100% [==================================================] 1/1

Randomized with --seed 1083318611
FAIL in cljdoc.doc-tree-test/find-neighbour-articles (doc_tree_test.clj:60)
find neighbour entries in doc-tree by slug-path Last element in tree have no next neighbour
expected: (->> example-tree doctree/flatten* reverse first :attrs :slug-path (doctree/get-neighbour-entries example-tree) last nil?)
  actual: false
1 tests, 3 assertions, 1 failures.
```

I am no test.check expert, but when I look at the test I see it is using [gen/sample](http://clojure.github.io/test.check/clojure.test.check.generators.html#var-sample). This makes it difficult to reproduce the failure as I don't see a facility to provide the seed.  Am I correct in that `sample` is intended for exploration only?

Should we rewrite these tests as [defspec](https://clojure.org/guides/test_check_beginner#_defspec) tests?  This would allow for easier reproduction of failures and would automatically take advantage of test.check shrinking to narrow down to the problematic scenario.

And then, of course, after that, we'd fix whatever bug we have in the test or code.

**Comment by lread** [comment]
Test was added as part of PR #409. 
@moonbrv, what do you think, should we convert to a defspec test?

**Comment by moonbrv** [comment]
@lread Hello, I will try to do that
