### ISSUE TITLE
Support Sourcehut as a SCM provider

### ISSUE THREAD

**Issue by miikka** [cljdoc/cljdoc#421]
[Sourcehut](https://sourcehut.org/) is this new software forge, a bit like GitHub and GitLab. I'm trying it out for some small projects of mine (e.g. [clj-base62](https://git.sr.ht/~miikka/clj-base62)) and thought it'd be nice if cljdoc supported it as well.

What I'm thinking of:

* The "Edit on GitHub" button saying "Edit on sourcehut" (or maybe "View on sourcehut" since you can't edit files in-browser)
* The button going to sourcehut's nicely-rendered [tree view](https://git.sr.ht/~miikka/clj-base62/tree/master/README.md) instead of the raw [blob view](https://git.sr.ht/~miikka/clj-base62/blob/master/README.md) where it goes now.
* The same for the links to source in namespace documentation
* Haven't tried it yet, but looking at the source of `cljdoc.util.fixref`, at least the image ref fixing needs fixing since sourcehut does not have `/raw/` endpoint.
* Maybe having a sourcehut icon next to the top-right corner home page link in cljdoc's documentation view.

Are you open to adding new SCM providers?

**Comment by lread** [comment]
Hi @miikka! Thanks for the interesting issue!

You are right in that cljdoc is GitHub focused. 

The URL scheme works with GitLab and Bitbucket as they use the same scheme as GitHub, but the cljdoc user interface still currently assumes GitHub.

Others might chime in, but I think explicitly supporting viable SCMs that the cljdoc community has a clear interest in makes sense.

**Comment by martinklepsch** [comment]
Definitely open to support more 👍

Sourcehut seems cool, stumbled upon it a few times the last months!
