### ISSUE TITLE
Problem loading devcards.core

### ISSUE THREAD

**Issue by metasoarous** [cljdoc/cljdoc#431]
Hello; Moving this over from #408 (thanks again for the help there).

Trying to build documentation for [Oz](https://github.com/metasoarous/oz), and getting the following:

```
Exception in thread "main" clojure.lang.ExceptionInfo: Could not generate ClojureScript documentation for oz/core_devcards.cljs {}
   ...
Caused by: clojure.lang.ExceptionInfo: No such namespace: devcards.core, could not locate devcards/core.cljs, devcards/core.cljc, or JavaScript source providing "devcards.core" in file /tmp/cljdoc-metasoarous-oz-1.6.0-alpha35-SNAPSHOT12565273646334706832/src/main/clojure/oz/core_devcards.cljs {:tag :cljs/analysis-error}
```

Full stack trace below:

https://app.circleci.com/pipelines/github/cljdoc/builder/12263/workflows/744f81e5-eba7-43db-b1e6-2854901f0179/jobs/28640

This dependency is declared in my `shadow-cljs.edn`, and I am having no problems running this particular namespace. Somewhat frustrating as well, since this is just a dev time artifact.

Please let me know if you have any ideas about how we might fix this.

Thanks!

**Comment by SevereOverfl0w** [comment]
Is this dependency in your pom.xml? It doesn't seem to be based on a cursory look on clojars.

**Comment by metasoarous** [comment]
Hmm... no, it's not. I've just got it in my `shadow-cljs.edn`. I guess I should switch to use `deps.edn` for all my deps and have shadow refer to that. Thanks for the catch.

**Comment by metasoarous** [comment]
Thanks again for your guidance @SevereOverfl0w.

I managed to switch shadow-cljs over to `deps.edn`, and so these dependencies are now ending up in the `pom.xml`, as required.

Moreover (for the sake of posterity), my cider-nrepl + vim-fireplace has been greatly improved as a result. Previously, if I wanted to have REPLS for both clj & cljs sides of Oz, I had to manually switch between then with `:Connect <port>` which was pretty annoying. Now, because the process serving up shadow is the same as the JVM process with Oz loaded up, it will automatically use the right evaluation environment depending on the file type. This may be thanks in part to some recent improvements to vim-fireplace, but it's worth noting I never got this level of flow with lein+figwheel. I realize this is entirely tangential to cljdoc, but again, leaving breakcrumbs for posterity :-)

Thanks again for your help!

**Comment by SevereOverfl0w** [comment]
> Thanks again for your guidance @SevereOverfl0w.

No problem at all

> but it's worth noting I never got this level of flow
> with lein+figwheel.

As a fellow fireplace user, I did get this working with both
lein/figwheel and the newer figwheel-main.  Just so there's never a
belief that this is only achievable with shadow.

**Comment by metasoarous** [comment]
Good to know!
