### ISSUE TITLE
Refine error reporting on analysis failure

### ISSUE THREAD

**Issue by lread** [cljdoc/cljdoc#446]
The current failure message can look like:
![image](https://user-images.githubusercontent.com/967328/114068837-52531a80-986c-11eb-99be-76c3c08c9f01.png)

This is fine when the error is actually related to the CircleCI analysis build job, but it misleads when the error is cljdoc-side.  
For example, when diagnosing sicmutils analysis failure, the error lead us to the CircleCI analysis build logs, but in fact, it looks like cljdoc simply timed out waiting for the job to complete.

It gets truly misleading when we navigate to the build page, we get:
![image](https://user-images.githubusercontent.com/967328/114069777-5b90b700-986d-11eb-81b5-164954643dcd.png)
This is directing the user to look at CircleCI build logs to find the source of the error. 
In this case the CircleCI build logs are not the source.

I'm not proposing that we get super detailed in the error, just give more of a high level hint as to the where/why/what.
And make an attempt to reduce misleading.

**Comment by martinklepsch** [comment]
Yeah properly logging an error code for timeouts would be great 👍
