### ISSUE TITLE
Consider upgrading cljdoc to use JDK17

### ISSUE THREAD

**Issue by lread** [cljdoc/cljdoc#450]
The cljdoc web server currently runs on JDK8.
Probably a good idea to move to JDK11?  
I don't see any issue with doing this.

Note that analysis builder job is already on JDK11.

**Comment by martinklepsch** [comment]
That seems reasonable to me, I think it actually shouldn't require much more than changing the base docker image here:

https://github.com/cljdoc/cljdoc/blob/679d4aea58a6702cf3b558bf65c67e65e426c56a/ops/docker/Dockerfile#L1

**Comment by martinklepsch** [comment]
Only question is which of all those docker images to use? 

https://hub.docker.com/_/openjdk?tab=tags&page=1&ordering=last_updated&name=11

Maybe `openjdk:11.0.11-jre`?

**Comment by lread** [comment]
I just found out I might be terrible at searching docker tags on docker hub. 😢 

I see we are currently using an alpine image, is alpine still of interest?

**Comment by martinklepsch** [comment]
> I just found out I might be terrible at searching docker tags on docker hub. 😢

You are not alone 😅

**Comment by martinklepsch** [comment]
I think alpine just means it's light/stripped down version. It looks like for v11 there are no alpine images however so I'm not sure what that means 😄 

Maybe #docker on Clojurians can save us from getting lost in a sea of docker tags 😆

**Comment by lread** [comment]
It seems that although there are docker images available for alpine, [OpenJDK past v8 don't officially support alpine](https://hub.docker.com/_/openjdk)(?):

> The OpenJDK port for Alpine is not in a supported release by OpenJDK, since it is not in the mainline code base. It is only available as early access builds of OpenJDK Project Portola. See also this [comment](https://github.com/docker-library/openjdk/pull/235#issuecomment-424599754). So this image follows what is available from the OpenJDK project's maintainers.

But Eclipse Temurin offers no such warning, at least on their [docker image description](https://hub.docker.com/_/eclipse-temurin/). They do warn about potential problems with Alpine though, but since we are already using Alpine, I assume we don't run into these.

> This variant is useful when final image size being as small as possible is your primary concern. The main caveat to note is that it does use <a href="https://musl.libc.org" rel="nofollow noopener">musl libc</a> instead of <a href="https://www.etalabs.net/compare_libcs.html" rel="nofollow noopener">glibc and friends</a>, so software will often run into issues depending on the depth of their libc requirements/assumptions. See <a href="https://news.ycombinator.com/item?id=10782897" rel="nofollow noopener">this Hacker News comment thread</a> for more discussion of the issues that might arise and some pro/con comparisons of using Alpine-based images.

One thing we are interested in is an image that is kept up to date. FWIW, a [trivy](https://github.com/aquasecurity/trivy) security scan on the current alpine temurin docker image reports no known vulnerabilities:

```shell
$ trivy image eclipse-temurin:17-alpine                                                                                                                                                                                                                  
2022-01-14T17:00:04.072-0500	INFO	Detected OS: alpine
2022-01-14T17:00:04.072-0500	INFO	Detecting Alpine vulnerabilities...
2022-01-14T17:00:04.077-0500	INFO	Number of language-specific files: 0

eclipse-temurin:17-alpine (alpine 3.15.0)
=========================================
Total: 0 (UNKNOWN: 0, LOW: 0, MEDIUM: 0, HIGH: 0, CRITICAL: 0)
```

Our current (obsolete) docker base image is openjdk:8-jre-alpine which weighs in at about 85mb. If I understand the current landscape, JREs are not typically an option anymore, but azul seems to offer one.

Here's a smattering of Alpine options with sizes as of this writing:

|Docker image | Size| Alpine Version | Trivy reports security issues?| 
|---|---|---|--|
|azul/zulu-openjdk-alpine:17-jre-headless | 195mb| 3.14.3| no |
|azul/zulu-openjdk-alpine:17| 284mb| 3.14.3| no |
|eclipse-temurin:17-alpine| 335mb| 3.15.0| no |
|openjdk:17-alpine|326mb| 3.14.0 | yes |

The amount of choice/tags/options is a bit overwhelming. I'm sure I might have missed something of interest.

So unless someone pipes in with more info, maybe we should go with temurin? 
The Alpine version is current.

If the size is a concern we could try azul jre.  
The Apline version is almost current and seems to be up to date if trivy is telling us the truth.

**Comment by lread** [comment]
Some notes from experiments with `eclipse-temurin:17-alpine`.
(will update this comment in place as I learn more)

JRuby (which is used by asciidoctorj) seems [to have a small issue with JDK17](https://github.com/jruby/jruby/issues/6721).
We can choose to either follow the advice of the warning, or let JRuby fall back to alternate implementations. For now, I am experimenting with adding the JVM opts the warning suggests.

The current production DigitalOcean droplet we use for cljdoc has 2gb of RAM.

As a local experiment, I tried to limit docker containers running cljdoc to 2gb of RAM via the docker `--memory 2GB` option.

I also temporarily enabled jconsole/visualvm monitoring support so I could get an idea of resource usage. Not sure the best way to do this, but a little googling about led me to add the following JVM opts to the Dockerfile `ENTRYPOINT`.

```
    # Temporarily provide access for JConsole, JVisualVM
    "-J-Dcom.sun.management.jmxremote=true", \
    "-J-Dcom.sun.management.jmxremote.port=9010", \
    "-J-Dcom.sun.management.jmxremote.local.only=false", \
    "-J-Dcom.sun.management.jmxremote.authenticate=false", \
    "-J-Dcom.sun.management.jmxremote.ssl=false", \
    "-J-Dcom.sun.management.jmxremote.rmi.port=9010", \
    "-J-Djava.rmi.server.hostname=localhost", \
```

If I then compare our current cljdoc docker image against a WIP-maintenance update of cljdoc I am working on, we seem to be OK.

The current version of cljdoc heap idles between ~80mb to ~220mb.
The new version of cljdoc on JDK17 heap idles between ~130mb to ~250mb.

Metaspace used for both old and new seems similar at around ~125mb.

I've setup both to reference local backup copies of production cache and cljdoc dbs.

These tests are initial. 
Ideally, I'd like to see how a production-style doc build affects things.
