### ISSUE TITLE
clj-kondo hooks cause documentation build to fail

### ISSUE THREAD

**Issue by IGJoshua** [cljdoc/cljdoc#455]
When building a project which uses [clj-kondo hooks](https://github.com/clj-kondo/clj-kondo/blob/master/doc/hooks.md), there are Clojure files placed on the classpath which are not a part of normal program execution, and which have namespace names which don't line up with their file positions.

For example, in [farolero](https://github.com/IGJoshua/farolero), there is a hook file included in `clj-kondo.exports/org.suskalo/farolero/hooks/farolero.clj`. For any project, it may include files under `clj-kondo.exports/<group-name>/<project-name>` that should not be loaded by cljdocs.

This build is an example of what occurs when this kind of file is included:
https://cljdoc.org/builds/44404

**Comment by martinklepsch** [comment]
@IGJoshua I've read the linked clj-kondo documentation but it doesn't specify the `clj-kondo.exports` path anywhere. Is this something you came up with to package hooks for library consumers to use? Do they need to take any other steps for the hooks to take effect?

The fix in cljdoc would rely on the path being consistent so I just want to make sure `clj-kondo.exports` is something that is defined by clj-kondo.

**Comment by martinklepsch** [comment]
Ah, nevermind, I found the relevant documentation here: https://github.com/clj-kondo/clj-kondo/blob/master/doc/config.md#exporting

**Comment by martinklepsch** [comment]
This is the function that would need to be extended in the `cljdoc-analyzer` project to either delete the `clj-kondo.exports` directory or all the files inside it. This change would mean the files are no longer present when the actual analysis happens.

https://github.com/cljdoc/cljdoc-analyzer/blob/57ddcedf05d73ad6835847576e48f73797834f82/src/cljdoc_analyzer/runner.clj#L40-L75

@IGJoshua would you perhaps be interested in contributing this change? :)

**Comment by martinklepsch** [comment]
The [`cljdoc-analyzer` project](https://github.com/cljdoc/cljdoc-analyzer#testing) has a solid test suite which might make contributing a little less intimidating 😊

**Comment by IGJoshua** [comment]
I'll give it a shot!

**Comment by IGJoshua** [comment]
I've created a PR for the code change, and all the tests pass, but I haven't yet got new tests in for this behavior.
