### ISSUE TITLE
Build "failed" but didn't???

### ISSUE THREAD

**Issue by cloojure** [cljdoc/cljdoc#456]
Hi - I tried to deploy the latest release of my lib and the cljdoc page says "API import failed in build #44815"

https://cljdoc.org/d/tupelo/tupelo/21.05.30b/doc/readme

However, if you look here:   https://cljdoc.org/builds/44815   and click on the "build job" link (aka "View job on CircleCI"), it says each stage was successful:

https://app.circleci.com/pipelines/github/cljdoc/builder/19539/workflows/a1fa3aff-384e-47ce-a6ae-d0fe2989339b/jobs/35914

The API docs seem OK, so I'm mystified as to what problem is occurring.

**Comment by lread** [comment]
Hi @cloojure, thanks for reporting this issue.

The cause might not be the same, but this sounds similar to #446.
