### ISSUE TITLE
Cannot analyze Expectations cljs code

### ISSUE THREAD

**Issue by seancorfield** [cljdoc/cljdoc#457]
See https://github.com/clojure-expectations/clojure-test

The `pom.xml` provides `planck` as a test-scoped dependency, but analysis fails due to a `paredit` namespace being missing. It seems to be something conditional inside Planck itself? https://github.com/planck-repl/planck/search?q=paredit 

It would be nice if cljdoc could at least complete the Clojure analysis of namespaces and build the docs, even if the ClojureScript analysis fails (and vice versa).

**Comment by lread** [comment]
Hi @seancorfield, do you know if this is still an issue for you?

We do [now allow explicit selection of API analysis languages](https://github.com/cljdoc/cljdoc/blob/master/doc/userguide/for-library-authors.adoc#api-language-detection).
Would that help?

**Comment by lread** [comment]
Ah thanks, I see the tweak now: [Martin added an override for you for expectations](https://github.com/cljdoc/cljdoc-analyzer/blob/a0139b72dd9656c011835fd6abaec026df805cf8/resources/config.edn#L12).
FWIW, this type of cljdoc-side override should not be necessary moving forward.
(And no plans to remove said tweak unless you request us to do so in the future).

**Comment by lread** [comment]
Since we seem to be all good, gonna close this one @seancorfield. Please feel free to re-open if you see a reason to.
