### ISSUE TITLE
Consider allowing library author to choose analysis platforms

### ISSUE THREAD

**Issue by lread** [cljdoc/cljdoc#468]
Currently cljdoc will auto-detect the platforms under which to analyze a project based on the types of source files (`.clj`, `.cljs`, `.cljc`) found in the project.

Some libraries include `.cljc` files when their ClojureScript support is still a work in progress and not functional.
For these projects cljdoc ClojureScript API analysis will fail.

We could allow a library author to specify for which platforms cljdoc should attempt analysis via a `:cljdoc/languages` key in `cljdoc.edn`.  If not present, current auto-detect behaviour would apply.  Examples of valid values:

- `:auto-detect`
- `["clj"]`
- `["cljs"]`
- `["clj" "cljs"]`

Or... we could continue to support these types of projects only via support request [and updating hardcoded values in cljdoc-analyzer](https://github.com/cljdoc/cljdoc-analyzer/blob/a8334e4405c3f5657a981ab5189db0038ecd034a/resources/config.edn).

Questions to self:
- [x] do we need any special `:cljdoc/languages` treatment for `:cljdoc/include-namespaces-from-dependencies`? Don't think so...
- [x] do we save any `cljdoc.edn` user config data to the database that thereby limit their lengths?
    Nope, we seem to be good here. All data is either saved to BLOBS or TEXT db columns which are limited to 1gb each in SQLite.

**Comment by lread** [comment]
This came up in Slack for a project that is failing to import because cljs support is a WIP.

Watcha think @martinklepsch?  I think it probably makes sense to expose this knob to library authors.

**Comment by martinklepsch** [comment]
Sounds good to me 👍 🙂

**Comment by lread** [comment]
@martinklepsch, the things you notice when you actually start to work on something... right?

I notice that we use namespaced key `:cljdoc.doc/tree` in `cljdoc.edn`.  
I'm not sure of the design intent of the `cljdoc.doc` qualifier (not the use of a qualifier itself, just the naming).
Would the languages key I am proposing fit under this qualifier:`:cljdoc.doc/languages`? 
Or was the`.doc` part somehow referring to articles and maybe I should use `cljdoc.api/languages`? I dunno, so thought I'd try to jog your memory.

I'm assuming `:cljdoc.doc/languages` is probably what makes sense? Lemme know whatcha think.

**Comment by lread** [comment]
Oh wait... my bad... there is also the optional `:cljdoc/include-namespaces-from-dependencies`.

So maybe I'll just go with... `:cljdoc/languages`.

**Comment by lread** [comment]
Note to self: I think I was thinking we were not validating cljdoc.edn on analysis, but I might have been wrong about that. When I get back to this, need to check.

**Comment by lread** [comment]
Ok, I was kind of right about validation (I think). 
We have a `spec/fdef` on `cljdoc.doc-tree/process-toc`, but it is not active.
I don't see validation on the `cljdoc.edn` edn document as a whole, which is what I'd expect.

So we have some specs defined to validate the `:cljdoc.doc/tree` (which is the brunt of the doc anyway), but I'd rather we have something validate the doc as a whole.  
Including for example the optional `:cljdoc/include-namespaces-from-dependencies`
and the new items I add for this work.

If I remember correctly:
- I was experimenting with using rewrite-clj to validate cljdoc.edn to allow me to provide errors to the user that included line/row offsets.
- I also tried malli. I find it much easier to grok than spec, but its error reporting got a bit confusing to me for the recursive doc tree.

**Comment by lread** [comment]
For completeness: did also consider having the user specify this option in the `pom.xml`.

Pros:
- the pom could be argued to be more about the code

Cons:
- the pom XML is not as familiar/approachable as cljdoc's config edn
- the pom is bundled in the deployed jar which means a new release for any changes
- not forward-thinking for source-based libs, see #459, which will typically not include a pom.xml
