### ISSUE TITLE
Having no public API is not always an error condition

### ISSUE THREAD

**Issue by lread** [cljdoc/cljdoc#474]
Cljdoc currently implies that no public API is problematic:

![image](https://user-images.githubusercontent.com/967328/134777354-50c84ebc-b913-43bd-9fdb-6fc4f8f02ff4.png)

But some libraries on clojars, oddly enough, don't have a public API.
Case in point is [clj-easy/graal-build-time](https://github.com/clj-easy/graal-build-time).

It would be nice if there were some way to indicate to cljdoc that a library has no public API, and when this is the case, cljdoc would simply convey, that there is no public API instead of the above message.

This would likely conveyed through a new option in a project's git repo's`doc/cljdoc.edn`.

**Comment by martinklepsch** [comment]
As an immediate improvement I'm also totally open to revisit/update the copy there, seems a bit too much really 😅

**Comment by lread** [comment]
> As an immediate improvement I'm also totally open to revisit/update the copy there, seems a bit too much really 😅

@martinklepsch, I think we can probably replace the big blurb under the NAMESPACES heading with:

> None found.

My thinking is that folks will reach out if this is not what they are expecting.

**Comment by martinklepsch** [comment]
That sounds good to me. I like "None found." and also showing the error there if there is one :+1:
