### ISSUE TITLE
Tries to import a class from a ns with no-doc in it

### ISSUE THREAD

**Issue by vemv** [cljdoc/cljdoc#487]
https://github.com/clojure-emacs/orchard/blob/v0.9.0/src-jdk8/orchard/java/legacy_parser.clj has no-doc in it but it still triggers:

```
  "Execution error (ClassNotFoundException) at java.net.URLClassLoader/findClass (URLClassLoader.java:476).\ncom.sun.tools.javadoc.DocEnv\n",
```

...DocEnv is only present in JDK8.

It looks like cljdoc's analyzer tries to do something with this ns despite having :no-doc in it?

Hope it helps.

Cheers - V

**Comment by vemv** [comment]
Here is the related build https://app.circleci.com/pipelines/github/cljdoc/builder/27260/workflows/7de1d9a0-4c10-4e97-8bf2-f8944d5da2dc/jobs/43635

**Comment by vemv** [comment]
> ...DocEnv is only present in JDK8.

I think the precise issue was that if you're running JDK8, tools.jar also needs to be in the classpath.

https://github.com/pallet/lein-jdk-tools is one way to accomplish that

**Comment by lread** [comment]
Thanks for raising this issue @vemv.

The cljdoc-analyzer loads all source it finds and then filters.

So this is interesting, last I checked, the cljdoc-analyzer was running on JDK 11. 
And for this project to load properly, it would probably prefer JDK8? Is that your observation?

This might relate to the ability to select a JDK for analysis #275.

**Comment by vemv** [comment]
Hey there 👋

> The cljdoc-analyzer loads all source it finds and then filters.

That might be the problem, if code is actually loaded (specifically running `import`s), then `^:no-doc` isn't being of much use to prevent the issue, which was my expectation.

Running JDK 11, 14, 16, 17 would all be fine as along as code marked with ^:no-doc wasn't evaluated.

Running JDK8 would also be acceptable if tools.jar was in the classpath.

However running JDK8 would have problems of its own for the Orchard project (since _other_ namespaces would start giving problems), so almost certainly it wouldn't be a worthwhile investment as far as we're concerned.

**Comment by lread** [comment]
Yeah, loading the sources is the way cljdoc-analyzer (which is based on codox) is designed.
The advantage of this is that it picks up any APIs generated through load time eval, like potemkin import-vars type strategies.

As for the orchard issues, I think I understand a bit better now. Orchard has moved on from JDK8 but includes an undocumented legacy JDK8 parser for those who need might want to use it.

It seems like this legacy orchard parser that relies on JDK8 tools.jar stands on its own.
I expect that it would not be loaded by some other orchard namespace.
If this is the case, if cljdoc provided some facility to exclude specific sources from being loaded, that might work. 

We'd have to weigh this against the cost of supporting additional knobs to turn.

Perhaps there is another work-around someone else might chime in with.

**Comment by vemv** [comment]
I think it's pretty common to try `read`ing a given .clj file in search of a `ns` form, from which one can read metadata. In fact... Orchard offers that! https://github.com/clojure-emacs/orchard/blob/febf8169675af1b11a8c00cfe1155ed40db8be42/src/orchard/namespace.clj#L19-L36 🌀

Then one could proceed to `pick up any APIs generated through load time eval, like potemkin import-vars type strategies.`, i.e. it is possible to have a "fail-fast" mechanism that doesn't exclude other approaches.

> We'd have to weigh this against the cost of supporting additional knobs to turn.

(I believe this would be a zero-config thing for consumers)

**Comment by lread** [comment]
Interesting, thanks for sharing.

So read the ns, check the meta and only explicitly load if we don't see no-doc.
This would not prevent a no-doc ns from being loaded if it were referenced from another loaded ns, but would likely solve the orchard problem.

Probably worth exploring further.

(Note: There is another issue that explored overriding no-doc for a var #444).

**Comment by vemv** [comment]
> This would not prevent a no-doc ns from being loaded if it were referenced from another loaded ns, but would likely solve the orchard problem.

I agree with both!

(Indeed in Orchard that ns is not required from other namespaces - or if it is, there's a JDK check which would not pass on cljdoc CI)
