### ISSUE TITLE
Upgrade Pedestal and handle new host requirement

### ISSUE THREAD

**Issue by lread** [cljdoc/cljdoc#493]
## Pedestal now defaults to localhost if host not specified
This is a good thing.
It avoids folks accidentally exposing a running server.
But we have to adapt.

## What we are doing now
Cljdoc uses aero for configuration.
The main config source is `./resources/config.edn`.
There is a `:host` entry under `:cljdoc/server` which, as far as I can tell, is currently unused.

## Option 1 [current proposal] - Default to localhost, allow override via Java system property
Like pedestal, we should probably default to `localhost`.
This way devs working on cljdoc won't be exposing a cljdoc server.

So I think we could go `./resources/config.edn` entry of:
```Clojure
{:cljdoc/server {...
                 :host #or [#prop cljdoc.host "localhost"]
                 ...}
```

Binding to `localhost` will not work for our docker container, so it would launch with an effective entry point of something like:
```Shell
clojure -J-Dcljdoc.host=0.0.0.0 -M -m cljdoc.server.system
```

## Option 2 - Hardcode 0.0.0.0
Always bind to `0.0.0.0`.
I'm not a huge fan as this is probably an impolite/unsafe default.

## Option 3 - Default to localhost, allow override via environment variable
Same as option 1, but use environment variable `CLJDOC_HOST`. 
The env var could then be passed in as part of a docker run command.
This might be interesting if folks wanted to bind to different hosts when using the cljdoc container. I don't see a need, but I might just be ignorant of an interesting use case.

## Option 4 - Autodetect environment and choose the appropriate host
We could instead [detect if we are running under docker](https://stackoverflow.com/a/25518345) and, in that case, automatically bind to `0.0.0.0` instead of `localhost`, but I think an explicit config is clearer, more obvious, more flexible, and especially, not magic.

## Next Steps
Barring any feedback, I'll follow up with a PR that matches option 1 above.

This PR will supersede #346.

**Comment by martinklepsch** [comment]
Option 1) & 3) sound good to me. I'm slightly leaning towards the env var since we already use env vars for `CLJDOC_SECRETS` and aren't using system props. So that would feel a bit more consistent. Either way is fine though :)

**Comment by lread** [comment]
Thanks for reviewing @martinklepsch! 

No huge preference here. 
I just thought a system property was more command-line friendly and more focused (less global).
I can do option 3 for consistency.

**Comment by martinklepsch** [comment]
Either is fine honestly :)

**Comment by lread** [comment]
Ok, in that case... I'll stick with option 1. 🙂
