### ISSUE TITLE
Invalid, self-signed certificate

### ISSUE THREAD

**Issue by piotr-yuxuan** [cljdoc/cljdoc#506]
Hey, thanks for your sheer work for the community :-) I've just noticed that cljdoc.org uses an invalid, self-signed security certificate. You're probably aware of it (https://github.com/cljdoc/cljdoc/commit/3cee371d699e394c74a251a48ff7f9d5d3d45bec ?) but it's just to cheer you up. You can close this issue when it's resolved.

``` log
$ curl -v https://cljdoc.org/
*   Trying 167.99.47.190:443...
* Connected to cljdoc.org (167.99.47.190) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (OUT), TLS alert, unknown CA (560):
* SSL certificate problem: self signed certificate
* Closing connection 0
curl: (60) SSL certificate problem: self signed certificate
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

**Comment by martinklepsch** [comment]
@piotr-yuxuan yeah, thanks for the flag. I'm aware of the issue and I'm trying to resolve it but so far I haven't been able to track it down quite yet. Somehow Traefik (our load balancer) fails to renew the certificates with the following error:

```
time="2022-01-31T10:53:28Z" level=error msg="Unable to obtain ACME certificate for domains \"cljdoc.org\" : unable to generate a certificate for the domains [cljdoc.org]: acme: Error -> One or more domains had a problem:\n[cljdoc.org] acme: Error 403 - urn:ietf:params:acme:error:unauthorized - Incorrect validation certificate for tls-alpn-01 challenge. Missing acmeValidationV1 extension.\n"
``` 

So I'm now trying a few different things that I'm finding in GitHub and Stackoverflow issues that seem related.

**Comment by martinklepsch** [comment]
Actually looks like switching to `httpChallenge` seems to have fixed the issue!
