### ISSUE TITLE
Review Sentry logging

### ISSUE THREAD

**Issue by lread** [cljdoc/cljdoc#513]
## Currently 
We send some log entries to Sentry

## Observation
In our production logs I often see lines like:
```
Initiated a temporary lockdown because of exception: Too many requests to Sentry: https://docs.sentry.io/learn/quotas/
```

## Problem
To me these log lines are distracting and noisy.

## Ideas
Review our usage of Sentry:
1. Is it valuable? If so let's adapt. If not, let's turf.
2. What are we logging to Sentry? Would it make sense to log less?
3. Is Sentry still valuable when it has gaps due to quota overruns?

**Comment by martinklepsch** [comment]
My quick thoughts on Sentry: It's helpful when exceptions occur but we would probably do just fine with a more basic logging service that... just logs (e.g. something like https://www.papertrail.com/). If we move onto different infra this might be quite easy to set up as well in which case we could probably just remove Sentry.

**Comment by lread** [comment]
Ok, on your thumbs up, I shall remove Sentry.

No pressure, if Sentry is really useful to you, we can keep. It might be a looong time before we actually move to new infra.

**Comment by lread** [comment]
Chatted with @martinklepsch and he thought we might look at this as part of #505, for now, we'll leave it as is.

**Comment by lread** [comment]
@martinklepsch asked and Sentry gave: free account on Sentry, so this should no longer be an issue.
