### ISSUE TITLE
dev support: Allow static resource cache to be cleared

### ISSUE THREAD

**Issue by lread** [cljdoc/cljdoc#574]
## Currently
As a cljdoc developer, if I run `npm run build`, then `resources-compiled` is rebuilt.

## But...
If I am running a cljdoc server locally, it won't pick up these changes because it has memoized these built assets.

## So...
I'll, at the very least, provide a facility for the developer to clear this memoized server-side cache via the REPL.

## Action
I'll follow up with a fix.

**Comment by corasaurus-hex** [comment]
Couldn't you use `npm run dev`?

**Comment by lread** [comment]
I usually do that @corasaurus-hex, but I'm not confident that watch mode does everything build does. Hence, me running `npm run build` sometimes.

Could be I'm just being naive? (I'm totally ok if I am being naive, lemme know)

I think I might make the wee change anyway, It is nice to not have to restart a server to clear a cache during a REPL session.

**Comment by corasaurus-hex** [comment]
As far as I can tell it's indistinguishable from the build in practice but I also haven't done everything you can do with the frontend. it totally makes sense to be able to clear caches, seems like a worthwhile change
