### ISSUE TITLE
dev: Support testing opensearch more easily

### ISSUE THREAD

**Issue by lread** [cljdoc/cljdoc#580]
### Recently
I didn't know what an `opensearch.xml` file was.

### Currently 
I do now know what this file is for.
It allows our users to use cljdoc as a search engine from their web browsers, and also, in theory, do so with type-ahead suggest support.

### But...
It is a pain to test this locally.
It means tweaking URLs in `opensearch.xml` manually (the URLs cannot be relative, unfortunately).

### Proposal
At the very least, we should add some docs in the developer's guide.
- what OpenSearch is 
- how to test locally from your web browser

We should also entertain somehow getting parcel.js to optionally create a localhost-friendly version of this `opensearch.xml`. If we do this, we should consider:
- running from dev box
- running from docker locally

**Comment by corasaurus-hex** [comment]
How about we add a route on the clojure app that's just `/opensearch.xml` instead of serving a static file? Then we can default to using cljdoc.org as the hostname and allow overrides with an environment variable when developing.

**Comment by lread** [comment]
Yas, thanks @corasaurus-hex, that's a very good idea!
