### ISSUE TITLE
A libraries search by q query-string parameter does not show search text

### ISSUE THREAD

**Issue by lread** [cljdoc/cljdoc#586]
## Problem
Cljdoc supports searching via a `q` query-string parameter.

## Context
This path can be invoked by anyone, but is specifically invoked when a user is using OpenSearch from their browser and selects a suggestion (see #581 for an overview of how OpenSearch works from a web browser).

## Actual Behavior
The query text does not show up in the search box:
![2022-04-15_10-49-50 (1)](https://user-images.githubusercontent.com/967328/163585684-8ffd2214-0def-4361-b836-3c2474d08453.gif)

## Expect Behavior
I would expect to see `rewrite` in the libraries search text box.

**Comment by corasaurus-hex** [comment]
I'm using this parameter for search input on single docset search, too

**Comment by corasaurus-hex** [comment]
I'm trying to replace lunr really quick but it's basically done
