### ISSUE TITLE
Add `npx tsc` check to build checks

### ISSUE THREAD

**Issue by corasaurus-hex** [cljdoc/cljdoc#619]
We should do type checks when doing builds. `npx tsc` works well for that. 😄

**Comment by corasaurus-hex** [comment]
@lread we should add this to the front-end checks

**Comment by lread** [comment]
Thanks, sounds good to me!  

I'll get things teased out first and then come back to add this extra check in.

**Comment by lread** [comment]
Ah... this will be good to have, but `npx tsc` is currently returning an error:

```
js/search.tsx:209:13 - error TS2322: Type '(props: { result: SearchResult; isSelected: boolean; selectResult: () => any; }) => h.JSX.Element' is not assignable to type 'ResultViewComponent'.
  Types of parameters 'props' and 'props' are incompatible.
    Type 'RenderableProps<{ result: CljdocProject; isSelected: boolean; selectResult: () => any; }, any>' is not assignable to type '{ result: SearchResult; isSelected: boolean; selectResult: () => any; }'.
      Types of property 'result' are incompatible.
        Type 'CljdocProject' is missing the following properties from type 'SearchResult': blurb, origin, score

209             resultView={SingleResultView}
                ~~~~~~~~~~

  js/listselect.tsx:41:3
    41   resultView: ResultViewComponent;
         ~~~~~~~~~~
    The expected type comes from property 'resultView' which is declared here on type 'IntrinsicAttributes & ResultsViewProps & Readonly<Attributes & { children?: ComponentChildren; ref?: Ref<any> | undefined; }>'


Found 1 error in js/search.tsx:209
```

Hmmmm... `blurb, origin, score` looks a bit familiar, I think I caused that! 🙂

I had a quick look, and maybe I could quiet the error, but I'm thinking a more experienced hand could do what looks like maybe some necessary cleanup?

**Comment by corasaurus-hex** [comment]
oof :(

I'd add a `// @ts-ignore` on the line above that for now

**Comment by corasaurus-hex** [comment]
I mean, I'm aware of that issue but it's a huuuuuge pain to fix.

**Comment by lread** [comment]
Does it mean a big rewrite?
Is the general design amiss?
(I'm not familiar with code, and not familiar at all with TypeScript).

**Comment by corasaurus-hex** [comment]
Essentially the needs of different search fields have outgrown the abstraction we have there. Teasing it all apart is pretty painful. I wonder if instead of fixing it it isn't the right time to bring in some cljs?

**Comment by lread** [comment]
Yeah maybe. I think cljs would probably be more approachable to more Clojurians.

**Comment by lread** [comment]
Hmm... I'm reading through TypeScript docs.

@corasaurus-hex I can take a crack at cleaning this up properly-ish if you are willing to review my PR. 🙂
