### ISSUE TITLE
Datalevin fails to analyze

### ISSUE THREAD

**Issue by corasaurus-hex** [cljdoc/cljdoc#620]
Womp womp! Datalevin fails to analyze. Seems like a pretty popular project and it'd be nice if we could get it working.

https://app.circleci.com/pipelines/github/cljdoc/builder/31218/workflows/2f4e0bdc-b511-4bc2-803c-849d3985c8ee/jobs/47592

**Comment by lread** [comment]
Hiya @corasaurus-hex, do you know if Datalevin is Clojure only?
The Clojure analysis seems to pass.

Because Datalevin has `.cljc` files our analyzer is assuming it is also ClojureScript and the ClojureScript analysis fails.

**Comment by corasaurus-hex** [comment]
It seems to have some [code that supports cljs](https://github.com/juji-io/datalevin/blob/master/src/datalevin/lru.cljc#L5)...

**Comment by corasaurus-hex** [comment]
Hmmm... I can't find a cljs release anywhere.

**Comment by lread** [comment]
But... it does generate its own API docs with codox, which seems to use [the default platform analysis (Clojure only)](https://github.com/juji-io/datalevin/blob/140e52cc11723152628175167de78a8026480f1f/project.clj#L92-L99).
Note: It uses some codox options we do not currently support.

In the past, I've pinged lib authors to gage interest in getting their docs to build on cljdoc. An easy sell, I would think, with our new docset search feature! 
After they are interested, I sometimes offer to do the PR for them.

**Comment by lread** [comment]
I can reach out on Slack to Datalevin team if you like. Lemme know!

**Comment by lread** [comment]
Reached out: https://github.com/juji-io/datalevin/pull/139

**Comment by lread** [comment]
Done! Next release of datalevin should look beautiful on cljdoc!

**Comment by corasaurus-hex** [comment]
🚀🚀🚀🚀
