### ISSUE TITLE
dev: turf husky

### ISSUE THREAD

**Issue by lread** [cljdoc/cljdoc#622]
## Currently
We use an npm tool called husky to do a git pre-commit check.
This check runs a formatting check on our front-end source.
This check is repeated by CI.

## But...
When things go wrong (for example, I have enabled gpg signing for my commits and I've not quite got it right yet) husky is just another complexity to wonder about.

And when husky's commit check fails, it can be confusing when using git from an IDE. 

## So...
I feel that husky is generally more confusing than helpful and plan to turf it.

**Comment by corasaurus-hex** [comment]
Yes, please! I really dislike husky (and all other forced git hooks). CI is a better place to catch this, for sure. Plus husky checks tent to make WIP commits really difficult to do, too.

**Comment by corasaurus-hex** [comment]
And also they make waaaaay less sense in a multi-language repo. Like why are my Clojure changes triggering a bunch of js/ts checks?

**Comment by lread** [comment]
Cool, glad you agree!
