### ISSUE TITLE
ci: move more lint work to lint job?

### ISSUE THREAD

**Issue by lread** [cljdoc/cljdoc#626]
## Currently 
Our CI workflow has a "prettier" job.
It performs a JavaScript lint on our sources.

## So maybe...
Rename it to "lint" and move all lint-like work from the "build" job to this job?

- clj-kondo linting 
- cljfmt format checks

I think this makes sense. 
- more things can happen at once
- the mysterious "prettier" job gets a more meaningful name.

## Alternatively
We could just move JavaScript linting to our main "build" job.

**Comment by corasaurus-hex** [comment]
I think having it as a separate step is useful in that you instantly know why the build failed.

But also it's not much work to click through and look at the build log and it would speed up CI for us.

I guess I like the idea of just adding it to the build step?

**Comment by lread** [comment]
> I think having it as a separate step is useful in that you instantly know why the build failed.

Oh, good point! Alternative 2: 
- rename "prettier" job to "front-end-checks"
- add new "back-end-checks" job
  - move lint-ish steps from "build" to "back-end-checks"

> I guess I like the idea of just adding it to the build step?

It would be simpler, but shaving a minute off the total elapsed build time, seems attractive to me. I think I'm going to give a go. 

Also has the advantage of failing slower to give more info. 
"Ok, build failed, but it was just `back-end-checks` that barfed," for example.

**Comment by corasaurus-hex** [comment]
Oh, right, you can parallelize the steps!! I was thinking it all had to be sequential in which case it would be faster to not pay the overhead of a separate step. This sounds great, having front-end-checks and back-end-checks. ☺️

**Comment by lread** [comment]
I'm now wondering about CircleCI deps caching maybe being sub-optimal for parallel jobs.
Can always revert if it does not work out.

I'm going to also tease out a "package" job that is currently in "build".
It has thrown me for a loop in the past, so an explicit job might help with clarity.
