### ISSUE TITLE
Docset search not returing babashka.fs/which var

### ISSUE THREAD

**Issue by lread** [cljdoc/cljdoc#630]
## Reproduction

I bring up [babashka.fs in cljdoc](https://cljdoc.org/d/babashka/fs/0.1.6/api/babashka.fs) and type `which` into the the search box.

## Expected Behavior

Search returns `babashka.fs/which`

## Actual Behavior

Search returns no result

## Diagnosis

I guessed that maybe stopwords were at play and [this seems to be the case](https://github.com/weixsong/elasticlunr.js/blob/be7fdaac67cdb3ea1e7bff3cf0bca577b02e8e84/lib/stop_word_filter.js#L185).

**Comment by corasaurus-hex** [comment]
Closed via https://github.com/cljdoc/cljdoc/pull/631
