### ISSUE TITLE
Support for Codeberg repository hosting

### ISSUE THREAD

**Issue by esuomi** [cljdoc/cljdoc#637]
Originally from Clojurians Slack:

> With [Leiningen moving project hosting to Codeberg](https://github.com/technomancy/leiningen/issues/2800), is there anything specific on cljdoc’s side that should be modified/updated to support Codeberg as code hosting site? I’m thinking link generation and that sort of stuff, if anything.

I'm not familiar with cljdoc's internals, so maybe this works out of the box, maybe it won't?

**Comment by lread** [comment]
And so long as URL access to raw/blob formats is the same as GitHub.

I have a little muckabout project I use for this kind of testing.
If nobody beats me to it, I'll give it a whirl sometime soonish.

**Comment by lread** [comment]
Oh... and we might do vendor-specific icons for links back to scm.

**Comment by lread** [comment]
Just tried it out

### Good
general import works

### Ok

#### icon
looks like we default to a generic icon for SCMs we do not have an icon for, we could replace the generic icon with a codeberg icon.

We tend to get icons from: https://github.com/blairanderson/microicon/blob/master/icons.md
Which does not have a codeberg icon.
But maybe we could just use include this little guy in our assets:
https://codeberg.org/Codeberg-Infrastructure/build-deploy-gitea/src/branch/codeberg-1.16/codeberg-white.svg

**Related: sourcehut icon:**
We are also currently missing a sourcehut icon.
But it's a circle. That should be easy.
Yeah, we could use: https://microicon-clone.vercel.app/panorama_fish_eye
or https://microicon-clone.vercel.app/radio_button_unchecked

### Needs work

#### blob links
links back to SCM are a bit different for codeberg.
Linking back to source with tag:
Github: 
ht<blah>tps://github.com/{org}/{project}/**blob**/{tag}/some/path/here/source.clj#L3
Codeberg: 
ht<blah>tps://codeberg.org/{org}/{project}/**src/tag**/{tag}/path/here/source.clj#L3

Linking back to source with sha:
Github: 
ht<blah>tps://github.com/{org}/{project}/**blob**/{sha}/path/here/source.clj#L3
Codeberg:
ht<blah>tps://codeberg.org/{org}/{project}/**src/commit**/{sha}/path/here/source.clj#L3

### raw links
Linking to a raw resource:
Codeberg replaces `src` with `raw` for the raw content:
Last examples as raw:
ht<blah>tps://codeberg.org/{org}/{project}/**raw**/tag/{tag}/path/here/source.clj#L3
ht<blah>tps://codeberg.org/{org}/{project}/**raw**/commit/{sha}/path/here/source.clj#L3

### main branch
iirc, we also look at the main branch sometimes?

In GitHub 
ht<blah>tps://github.com/{org}/{probject}/blob/{branch}/path/source.clj
Codeberg is once again more explicit (which seems like a better design choice actually):
ht<blah>tps://codeberg.org/{org}/{project}/src/**branch**/{branch}/path/source.clj

**Comment by lread** [comment]
I was curious so I grabbed a copy of the current cljdoc production database and reported scm url hosts:

```Clojure
(-> (for [r (sql/query db-spec
                         ["select * from versions"]
                         {:row-fn (fn [{:keys [meta] :as r}]
                                    (if meta
                                      (assoc r :meta (nippy/thaw meta))
                                      r))})
            :let [url (some-> r :meta :scm :url)]]
        (some-> url uri/uri :host))
      frequencies)
  ;; => {nil 14459,
  ;;     "bitbucket.org" 2,
  ;;     "gitlab.com" 81,
  ;;     "git.sr.ht" 26,
  ;;     "www.github.com" 36,
  ;;     "codeberg.org" 1,
  ;;     "gitea.heevyis.ninja" 3,
  ;;     "gitea.lyrion.ch" 1,
  ;;     "github.com" 35233}
```

That 1 codeberg project is my experiment.
- Leiningen team have not made their first lib release after switching to codeberg yet
- Verified against http://clojars.org/repo/feed.clj.gz, it too only has 1 codeberg project


Also interesting is that a few people point to what seems to be their own gitea hosted servers. Codeberg is also based on gitea.

**Comment by lread** [comment]
Ok, so the codeberg icon is designed, as far as I can tell, for a non-white background.
It just does not show up on a white background.
Cljdoc uses a white background.

Perhaps I'll, at least for now, just use the gitea icon for codeberg. We shall see.

**Comment by lread** [comment]
Oh wait, even though I think b&w is better we could use the codeberg favicon.svg instead:

https://codeberg.org/Codeberg-Infrastructure/build-deploy-gitea/src/branch/codeberg-1.16/codeberg-favicon.svg
