### ISSUE TITLE
Analyizer does not fetch deps from repositories of other deps

### ISSUE THREAD

**Issue by IamDrowsy** [cljdoc/cljdoc#642]
One of my projects ([cloudship](https://github.com/iamdrowsy/cloudship)) is now using a dependency ([one-time](https://github.com/suvash/one-time)) that fetches on of its dependencies from another repo ([jitpack](https://jitpack.io)).

As this is mentioned in the [project.clj of one-time](https://github.com/suvash/one-time/blob/main/project.clj), generating the [docs ](https://cljdoc.org/d/one-time/one-time/0.7.0/doc/readme) works.

When using one-time as a dependency, the dependency resolving of lein works, but the cljdoc [build fails](https://app.circleci.com/pipelines/github/cljdoc/builder/34006/workflows/2118ed0f-3582-4734-afa4-15130fb836c1/jobs/50380).

One workaround is, to add the repo in your own [project.clj ](https://github.com/IamDrowsy/cloudship/commit/93ebdf7fdb1f404436ccdb68fafc8cd4f88ab256), resulting in a successful [build](https://app.circleci.com/pipelines/github/cljdoc/builder/34024/workflows/2ea39645-6e58-4aff-881c-e0066b3a8428/jobs/50398).

**Comment by lread** [comment]
Thanks for raising this issue @IamDrowsy!

Cljdoc analyzer uses [clojure.tools.deps.alpha](https://github.com/clojure/tools.deps.alpha) to resolve dependencies.
I think you bumped into [TDEPS-46](https://clojure.atlassian.net/browse/TDEPS-46).

And your workaround is what TDEPS-46 recommends as a workaround.

As for actionable items, I think making some mention of how deps are resolved in our [docs](https://github.com/cljdoc/cljdoc/blob/master/doc/userguide/for-library-authors.adoc) would help. I can follow up with that.

**Comment by IamDrowsy** [comment]
Hi @lread,

thanks for your answer.
Of course it would be nice to have it mentioned in the docs, but I skimmed through them and found no obvious place to add this.
For me, your anwser is sufficient and having this closed issue for reference is fine.

So feel free to close this issue without any further actions, if you want.

**Comment by lread** [comment]
I found a [good place](https://github.com/cljdoc/cljdoc/blob/master/doc/userguide/for-library-authors.adoc#getting-dependencies-right) to add a tip.

I shall follow up and do it. 🙂
