### ISSUE TITLE
Consider not including deftype and defrecord elements in docs

### ISSUE THREAD

**Issue by lread** [cljdoc/cljdoc#645]
## Currently
While looking into #444, I noticed that:

- A `defrecord MyRecord` will be included in API docs as `MyRecord`.
- A `deftype MyType` is included in API docs as `MyType` for ClojureScript only.

## History
I think it was probably me, some time ago, noticing `MyRecord` returned by the ClojureScript analysis, that added some compensation to infer the same for Clojure.

I did not notice `MyType` missing from Clojure, hence the mismatch for ClojureScript.

## Proposal
Always suppress both `MyRecord` and `MyType` elements from all API docs.

I raised the question on Slack if this would be OK with folks and @seancorfield was very helpful with his observations:

> Since you can't attach docstrings to records (or types), nothing shows up in the (ns api) docs except the name which is... of minimal value... and you can't make a record (or type) "private" so there's no way for readers (of cljdoc) to determine whether such a record (or type) is actually useful or even intended to be part of the (public) API. So I'd be perfectly happy with them disappearing from the API docs -- and if they are important to library maintainers, they can add notes to the docs articles and/or the `ns` docstring.

> There are a couple of these in `next.jdbc.result-set` which I would want to suppress if I had the option...

## Next Steps
I shall soon make it so.

**Comment by NoahTheDuke** [comment]
I don't agree with the proposal as I see them as part of the public API (even if they're purely implementation details), but I understand the reasoning and I respect your position as the maintainer. 

My use-case is that I am providing users of my library with a creation/wrapping function `->diagnostic` that creates a Diagnostic, and I want them to know what a Diagnostic is without having to look at the code.

Mirroring the defrecord call in the namespace docstring works but is awkward and requires keeping them in sync. This will be exacerbated if I ever implement any protocols on the record.

**Comment by lread** [comment]
Hi @NoahTheDuke, happy to discuss.

> as I see them as part of the public API (even if they're purely implementation details)

To me, implementation details are not part of public APIs because implementation details are subject to change. But that's probably not what we are discussing.

Because `defrecord` does not support metadata and docstrings, I'm guessing that you'd still describe/reference the record in your namespace or other var docstrings? 

Another idea would be to compensate for the limited syntax of `defrecord` (and `deftype`, I guess, and ?).

Not thought out yet, but maybe something like:

```Clojure
#_{:cljdoc/doc "blah blah blah"}
(defrecord Diagnostic [rule-name form message alt line column filename])
```

**Comment by seancorfield** [comment]
@NoahTheDuke I think my recommendation here would be either:
* document the records/types in the `ns` docstring, and/or
* add an explicit "constructor" function that wraps the generated record constructor and document it there (in the docstring)

Having a record as part of your API without a protocol seems strange to me, since records are really an implementation detail or a performance optimization (over a plain hash map). They're concretions and it should be the underlying abstraction that should be part of the API.

**Comment by lread** [comment]
@seancorfield, thanks for chiming in!

I'm now guessing the reason that `defrecord` does not support a docstring might be deliberate rather than an oversight.

The idea being that these are implementation details that therefore do not require API docs.
Does that make sense?

**Comment by seancorfield** [comment]
`defrecord` and `deftype` map directly to Java classes, so there's nowhere to hang metadata and therefore nowhere for a docstring. So it's "deliberate" in that respect. So you "can't" document them at their source -- you can only document them indirectly (in an `ns` docstring or in a wrapper function docstring).

**Comment by lread** [comment]
Ah, makes sense, thanks @seancorfield.

Java JavaDocs are not included in `.class` files and are generated from Java source files.
Clojure is different in that its docs are available as metadata at runtime.

So if cljdoc ever did want to support docs for records and types (not saying that it should) we could compensate with something like [I suggested above](https://github.com/cljdoc/cljdoc/issues/645#issuecomment-1494492104).

But @seancorfield, your [recommendation](https://github.com/cljdoc/cljdoc/issues/645#issuecomment-1494654438) makes sense to me. @NoahTheDuke, after giving this time to percolate in your Clojure-brain, I'm curious to know if your position has changed.

**Comment by NoahTheDuke** [comment]
I think it'll work just fine. I personally would still like having them appear but I won't belabor the point. Thanks so much.

**Comment by lread** [comment]
@NoahTheDuke, thank you for bringing up your issue, I'm glad you are OK with the current state of things, and am happy to have explored/learned while discussing.
