### ISSUE TITLE
Only include latest (canonical) URL in sitemap

### ISSUE THREAD

**Issue by danielcompton** [cljdoc/cljdoc#651]
https://developers.google.com/search/docs/advanced/sitemaps/build-sitemap?hl=en says

> List only [canonical URLs](https://developers.google.com/search/docs/advanced/crawling/consolidate-duplicate-urls) in your sitemaps. If you have two versions of a page, list in the sitemap only the one you prefer to appear in search results. If you have two versions of your site (for example, www and non-www), decide which is your preferred site, and put the sitemap there, and add rel=canonical or redirects on the other site.

This will help with bringing down the size of the sitemap, and perhaps hint to Google about new pages that should be crawled. 

At the moment the top Google result for Malli is v0.2.1:

<img width="805" alt="Screenshot of Safari (22-08-22, 2-01-06 PM)" src="https://user-images.githubusercontent.com/811954/185824931-741ac7c6-45ff-42d4-87f4-0446d00f681e.png">

**Comment by lread** [comment]
Hi @danielcompton thanks for raising this one!

We do have an existing issue #397 with an open question and it seems like maybe you've just given us some guidance here. 

Are you wanting to do a PR here?
If not, I'll get to it sometime soon.

**Comment by danielcompton** [comment]
If I get the chance I will make a PR, but happy for you to do it if you get to it first :)

**Comment by lread** [comment]
I'll take a stab at this one @danielcompton.
