### ISSUE TITLE
Consider adding Eastwood linting

### ISSUE THREAD

**Issue by lread** [cljdoc/cljdoc#682]
## Currently
We lint with clj-kondo. I love it.

## But..
[Eastwood](https://github.com/jonase/eastwood) can sometimes find a thing or two that clj-kondo does not.

It is quite nice, for example, for finding reflection calls. If we care to find those.
It will also point out calls to deprecated Java.

## Soo...
I think I might add Eastwood to our listing suite.

**Comment by lread** [comment]
The Clojure docs [advise](https://clojure.org/reference/java_interop#typehints):

> Normally, one should avoid the use of type hints until there is a known performance bottleneck.

But when I've added new code to cljdoc I've often included `*warn-on-reflection*` and the resulting type hints. I do find they help, with more than performance. Not only do they tell Clojure what Java class to operate on, but they also remind me what 3rd party Java class I'm operating on.

**Comment by corasaurus-hex** [comment]
![](https://media.giphy.com/media/XuBJvrKHutnkQ/giphy.gif)
