### ISSUE TITLE
Consider indicating when a var differs between platforms in var list

### ISSUE THREAD

**Issue by lread** [cljdoc/cljdoc#702]
## Currently
Cljdoc indicates the dominant platform for a namespace and annotates all vars that differ from the dominant platform.

For example, if most functions are in defined in both Clojure and Clojure it will indicate such, and annotate each var that differs. If a var is only defined in Clojure, it will mark it as such and if a var is only defined in ClojureScript it will mark it as such.

Example presentation:

![image](https://user-images.githubusercontent.com/967328/203148624-dfe26350-6e62-497e-aa10-218222c64d83.png)

## But...
When a var is defined in both Clojure and ClojureScript there is no indication in the var index when the var's arglists and/or docstrings differ for those platforms.  

Note that the difference is shown when viewing var details. Example presentation when both arglists and docstrings differ:
![image](https://user-images.githubusercontent.com/967328/203150253-e7118a3e-cc42-4c3f-8e6d-2c443d8c253e.png)

This will not come up terribly often in a lib, but when it does, it is very useful information to see at-a-glance.

## Proposal
Indicate vars that differ for platforms with superscript of something like: clj!=cljs

This will sometimes override the current annotation of: clj/s (which indicates a var is defined for  both clj and cljs).

**Comment by lread** [comment]
I've been playing with this a bit.
I think maybe `diff` is easier to glance at than`clj!=cljs`.

Also: Repeating the platform annotation superscript in the var details would be helpful.
I'll probably scope that in.

I'll plunk screenshots here for review sometime soon.

**Comment by lread** [comment]
Ok. I've decided `diff` for the annotation text is not a good choice.
It is too vague and therefore likely confusing.

For a var that is available in both Clojure and ClojureScript platforms, we currently annotate with `clj/s`. I think when there are any rendered differences for those platforms I'll instead show `cljs/s*`. The `*` is subtle but does indicate a closer look is warranted.

Examples are from [cljdoc-exerciser](https://cljdoc.org/d/org.cljdoc/cljdoc-exerciser/1.0.90).

## Var index list
![plat-diff-var-list](https://user-images.githubusercontent.com/967328/204105479-c887dbcd-54b9-4961-9d73-f7debb57b630.png)

The new rule is if an item in the index has differences across platforms it will always be annotated with `clj/s*`.

You'll perhaps notice the annotation:
- looks a bit awkward for the wrapped `docs-and-args-differ-bigger` fn
- is visually truncated for the `ProtoDocsAndMembersDiffer` protocol.

These are pre-existing issues, and will not be addressed as part of this issue.

## Var details
The detail view currently does not annotate vars with their supported platform.
Since protocol members are not (yet) listed in the var list, cljdoc does not currently convey the platform for protocol members.

To solve this my original plan was to include the platform annotation to the var detail view for only protocol members. After giving it a whirl, I decided that always including the platform annotation for all vars offered a nice subtle reminder of what platforms are supported for a specific var.

### A Clojure-only namespace
As you can see the difference is subtle but, I think, useful.

![plat-diff-detail-clj-only](https://user-images.githubusercontent.com/967328/204106139-2808d2ff-f460-4d5b-9bbb-85b1c8bae21e.png)

## A Protocol with platform differences
A contrived test example, but useful to illustrate:

![plat-diff-detail-protocol](https://user-images.githubusercontent.com/967328/204106409-35cea70e-c753-449c-a175-cffabdc8ccec.png)

### A single-platform protocol
I'll grab an example from clj-yaml for this one.
Notice we will now always show the platform annotation in the var detail view.

![plat-diff-detail-protocol-clj-only](https://user-images.githubusercontent.com/967328/204106579-cba27bd4-a04c-4309-8b63-ee8aaf0c7963.png)

**Comment by corasaurus-hex** [comment]
What do you think about using a diff icon from fontawesome instead of a `*`?

<img width="680" alt="Monosnap Font Awesome 2022-11-26 15-25-01" src="https://user-images.githubusercontent.com/130/204109574-83c65117-bbbb-469f-bb39-21db3cb6a84c.png">

It might not look very good or it might look great? I think for developers, at least, that would be meaningful in the context of `clj/s`

**Comment by corasaurus-hex** [comment]
Oh, it's probably helpful if I include a link https://fontawesome.com/search?q=diff&o=r&s=thin%2Clight%2Cregular%2Csolid

**Comment by lread** [comment]
Ah... @corasaurus-hex! Thanks so much for taking the time to review and for the idea!

I'll give the diff icon a whirl soon and share what it looks like.

**Comment by lread** [comment]
@corasaurus-hex, yoiks, I'm confused by [allowable usages of fontawesome](https://fontawesome.com/plans).
I think the diff icons you found are part of the "pro plan".

Maybe I'll hunt around a bit for something that seems more understandably free.

**Comment by lread** [comment]
Ah... maybe this will do for an experiment: https://icons.getbootstrap.com/icons/file-earmark-diff/

**Comment by corasaurus-hex** [comment]
This might help: https://github.com/FortAwesome/Font-Awesome#license

**Comment by corasaurus-hex** [comment]
And in the case of the icons: https://creativecommons.org/licenses/by/4.0/

**Comment by lread** [comment]
So what's with the confusing messaging around a pro plan fee and pro icons?
As a fontawesome newb, the messaging makes me shy away from fontawesome for sure.

Anyhoo... let's carry on with the experiment.
I'll use [bootstrap icons](https://icons.getbootstrap.com/), they are very similar.
I've used default coloring for icons, just trying to get a feel for how they look before any fine tuning.

## Option 1: Current rendering with clj/s*

![image](https://user-images.githubusercontent.com/967328/204162862-28508bff-4833-415b-9d61-9d2d3e332fc1.png)

## Option 2: With docdiff icon

With this one:
![image](https://user-images.githubusercontent.com/967328/204163248-63474f7f-142e-453c-bdf7-5ed692b8a1b0.png)

![image](https://user-images.githubusercontent.com/967328/204163049-35d5f225-39cf-4ac5-bc7e-3b53ecc6a073.png)

I think the docdiff icon has too much detail so such a small representation.
At-a-glance, it almost looks like a missing img.

## Option 3: With slash plus minus icon

With this one:
![image](https://user-images.githubusercontent.com/967328/204163294-e736246a-937b-4ade-b762-f64d550731ca.png)

![image](https://user-images.githubusercontent.com/967328/204163370-6b533ec5-1593-41a1-8626-c7da82caa40f.png)

This is better, but looks a bit askew to me. Maybe still too much detail.

## Option 4: With unicode clj/s≠
![image](https://user-images.githubusercontent.com/967328/204163514-41cf4f2f-608b-4be5-a6e4-16de65c49dd0.png)

I think this last one is probably better than clj/s*, what do you think?

## Option 5: One last variant: clj≠s

![image](https://user-images.githubusercontent.com/967328/204163765-70969a54-333c-42dd-8ee9-e5db03c52301.png)

Here we reduce text by 1 char, but I think it looks a bit odd, probably because the not equal character is rendered a bit low on the line (at least on my linux box here).

## Proposal
Out of the above, I think I prefer option 4 over option 1.
Whatcha think?

**Comment by lread** [comment]
Fwiw, rendering of ≠ on macOS seems more reasonable to me:

![image](https://user-images.githubusercontent.com/967328/204164413-ecd70c6e-65d8-4358-bc07-344623eadd64.png)

**Comment by corasaurus-hex** [comment]
sorry I missed all of this since my comments 😅

**Comment by lread** [comment]
> sorry I missed all of this since my comments 😅

Hey, no problemo at all, and, as always, your feedback and ideas are very much appreciated!
