### ISSUE TITLE
Cljdoc should undertand that not all listed artifacts are resolvable

### ISSUE THREAD

**Issue by lread** [cljdoc/cljdoc#716]
## Sentry logs

I'm taking a random peek at the cljdoc server logs through Sentry and discovering some things.

## Oddly versioned artifacts not found
I'm seeing that cljdoc is trying to build [the SNAPSHOT version of com.gitlab.vise890/parseq](https://clojars.org/com.gitlab.vise890/parseq/versions/SNAPSHOT). 

Typically I'd expect to see a version of `1.2.3-SNAPSHOT` and not just `SNAPSHOT`. 
So, to me, this is strange.

## Diagnosis
I can see the SNAPSHOT release on clojars:
https://repo.clojars.org/com/gitlab/vise890/parseq/SNAPSHOT/

But I also see that cljdoc is only recognizing versions that end in `-SNAPSHOT` as snapshot builds.

### What does clojure cli do?
A sanity check with clojure cli:
```
$ clojure -Sdeps '{:deps {com.gitlab.vise890/parseq {:mvn/version "SNAPSHOT"}}}'
Error building classpath. Could not find artifact com.gitlab.vise890:parseq:jar:SNAPSHOT in central (https://repo1.maven.org/maven2/)
```
Hmm... so tools deps cli is also not finding this artifact either.

### What does leiningen do?
Out of curiosity, what about leiningen? A `project.clj`:
```clojure
(defproject my-project "0.0.1"
  :description "testing 123"
  :dependencies [[com.gitlab.vise890/parseq "SNAPSHOT"]])
```
And ok, same result:
```
$ lein repl
Could not find artifact com.gitlab.vise890:parseq:jar:SNAPSHOT in clojars (https://repo.clojars.org/)
This could be due to a typo in :dependencies, file system permissions, or network issues.
If you are behind a proxy, try setting the 'http_proxy' environment variable.
Could not resolve dependencies
```

## So...
Is `SNAPSHOT` a technically valid version?
Should it be treated as a snapshot build?

I don't think it technically is a snapshot version: https://maven.apache.org/guides/getting-started/index.html#What_is_a_SNAPSHOT_version
Snapshot is described as a version with the `-SNAPSHOT` suffix.

## Next steps...
I'll ask on clojars about this case.

We can adapt cljdoc to ignore these specific artifacts from clojars if need be.

**Comment by puredanger** [comment]
```clojure
  (def v (org.apache.maven.artifact.versioning.DefaultArtifactVersion. "SNAPSHOT"))
  [(.getMajorVersion v)
   (.getMinorVersion v)
   (.getIncrementalVersion v)
   (.getQualifier v)
   (.getBuildNumber v)]
  ;;=> [0 0 0 "SNAPSHOT" 0]
```

**Comment by lread** [comment]
Thanks @puredanger!

Since neither lein nor clojure cli can seem to resolve these `SNAPSHOT` versions, I think I might just have cljdoc skip them.

**Comment by lread** [comment]
## New Discovery
This is not limited to artifacts versioned `SNAPSHOT`.
Exhibit b: a version that uses `+` instead of `-`

- desc: https://clojars.org/com.mouryaravi/faraday/versions/1.11.1+protocol
- repository: https://repo.clojars.org/com/mouryaravi/faraday/1.11.1%2Bprotocol/

This seems to be unresolvable with clojure cli:
```
$ clojure -Sdeps '{:deps {com.mouryaravi/faraday {:mvn/version "1.11.1+protocol"}}}'   
Error building classpath. Could not find artifact com.mouryaravi:faraday:jar:1.11.1+protocol in central (https://repo1.maven.org/maven2/)
```

## New sketch of a plan (I may drift/simply/reduce-scope as I learn more while implementing)
Have cljdoc understand that not all clojars listed artifacts are resolvable.
This means that when attempting to build docs for an artifact, it is expected that it might not be resolvable.

So if we get a not-found result when trying to resolve a listed artifact we'll simply fail the build and not automatically retry it. Otherwise, for auto-queued builds, it is probably worth automatically retrying, but not before other queued artifacts.  

As for db migrations, I'll add something to support sending builds to be retried to the back of the queue.
