### ISSUE TITLE
Broken cross-project link in docstring

### ISSUE THREAD

**Issue by serioga** [cljdoc/cljdoc#735]
I want to put a cljdoc link to another project in docstring.

So I have now a link between two projects:
- to https://cljdoc.org/d/com.github.strojure/undertow/CURRENT/api/strojure.undertow.server#start
- from https://cljdoc.org/d/com.github.strojure/ring-undertow/1.0.41-beta6/api/strojure.ring-undertow.server

The first link with CURRENT works fine as standalone, I can open it in browser.
But when I click it on the source page (the second link) the `CURRENT` is replaced with `1.0.41-beta6` (that is wrong) and I hit non-existing page.

**Comment by lread** [comment]
Thanks for raising this issue @serioga! I'll restate to gel my understanding:

So undertow is currently at 1.0.64-beta9
And ring-undertow is currently at 1.0.45-beta7

When using from ring-undertow to a CURRENT api link in undertow, you'd like to link to the current version of undertow but cljdoc is linking to the current version of ring-undertow.

Ya, I think that's a bug.

Some projects deploy a set of libraries with versions synchronized.
These libraries might expect CURRENT to behave as it does today... but I still think CURRENT, [as we've described](https://github.com/cljdoc/cljdoc/blob/master/doc/userguide/for-library-authors.adoc#link-to-api-docs) it clearly states it will link to the current release of a library. 

Thanks, I'll follow up with a fix sometime soon.

**Comment by lread** [comment]
I had a look at the code.

It looks at the referer header.
If a URL has CURRENT, it will use the version found in the referer header URL (hence the reported behaviour). 

I'm guessing the intent was, within the scope of navigating within library x version y, to stick to version y even when encountering a CURRENT URL. That seems reasonable. 

I'll add in a check to not use referer if the referer library is different from the URL library.

**Comment by lread** [comment]
The use case of a release version y of a set of libraries and the user wanting to remain at version y while navigating across that set of libraries still might come back as an issue in the future, but we can try to deal with that if/when it does arise.
