### ISSUE TITLE
no-doc metadata not fully respected

### ISSUE THREAD

**Issue by kkinnear** [cljdoc/cljdoc#74]
I'm trying to get my libraries ready for cljdoc, and I have a bunch of stuff that isn't part of the API that I don't want documented.  Looks like cljdoc uses codox, so I assume that the `^:no-doc` metadata on the namespace or a function definition will work.  My question though, is whether or not the codox configuration in the project.clj is recognized by cljdoc.  I would guess that it isn't, but wanted to check.

I'm only asking this because trying out cljdoc seems to only work on things pushed to github.  I have figured out how to run it myself, locally, but it is still operating on code on github.  If there were some way to have cljdoc operate on code locally on my machine, then I could just try out a bunch of things without pushing new things to try to github repeatedly.  Is there a way to do this?

Thanks much!

**Comment by martinklepsch** [comment]
@kkinnear There's no support for `project.clj` at this point. We provide a mechanism to provide some configuration (articles for now, more in the future) via `doc/cljdoc.edn` see the [articles userguide](https://github.com/martinklepsch/cljdoc/blob/master/doc/userguide/articles.md).

As for trying stuff out: cljdoc looks at jars to extract any API information and only looks at Git repositories for additional stuff like Markdown files, etc. A jar is a little more predictable to work with and versions are clearly labelled/immutable (unless SNAPSHOT).

Assuming you used `boot build-docs ...` to try things locally, I just pushed a minor change that allows you to specify the jar and pom used: 
```
boot build-docs -p reagent -v 0.8.1 --pom ~/.m2/repository/reagent/reagent/0.8.1/reagent-0.8.1.pom --jar ~/.m2/repository/reagent/reagent/0.8.1/reagent-0.8.1.jar target
```

It's not the shortest but it should get the job done I guess :) 

After this you can run `script/serve.sh` which will start a basic HTTP server serving your documentation.

It would also be nice to make the regular server (i.e. `boot run`) use local jars but right now it mostly gets jars from Maven Central/Clojars.

Feel free to hit me up on Slack if this doesn't help.

**Comment by kkinnear** [comment]
Thanks for this change, I really appreciate it.  It works great, and I've learned a lot from being able to run thing locally.   Really a great help!

I've managed to get the cljdoc.edn file to work for me to gather up my documentation.  I noticed that in the reitit example, there was other information in the cljdoc.edn file.  What I was hoping for was a way to say to cljdoc "just do these namespaces and nothing more".  I've tried to put the `^:no-doc` meta-data in the `ns` declaration, which keeps codox out of the namespace, but doesn't seem to affect cljdoc. I do see that `^:no-doc` works for individual function definitions for cljdoc, which is great!  But I have lots of namespaces that are not part of my API, and for which I don't wish to use `defn-`.  I was hoping that `^no-doc` in the `ns` declaration would keep cljdoc out of those namespaces.  But if there were a way to specify either the namespaces that I want (or that I don't want) in the cljdoc.edn file, that would be fine.  Is this already there (or coming), or is there some other way I can just get cljdoc to ignore some namespaces?  Thanks much!

**Comment by martinklepsch** [comment]
`^:no-doc` should work and if it doesn't that can be considered a bug. Which library have you tried this with? I searched zprint and zpst for `no-doc` but couldn't find any usages.

Would be happy to look into this/fix it, and a repro case would help a lot already 🙂 

> Is this already there (or coming), or is there some other way I can just get cljdoc to ignore some namespaces? Thanks much!

The `include-namespaces` stuff and similar is "dream code" i.e. it may exist in the future but doesn't yet. As you point out there should probably be ways to whitelist but also to exclude namespaces. Will try to open an issue for this later.

**Comment by kkinnear** [comment]
I've been trying this locally (since you fixed it so I could) with modifications to zprint for codox.  I will tidy that up a bit, and push a set of sources which have `:no-doc` in the proper places for codox in the next day or two, so you can see what is (and isn't) working.  Thanks!

**Comment by martinklepsch** [comment]
@kkinnear So I just added `^:no-doc` to a namespace and can reproduce the problem. It seems there is an issue with that metadata being respected when reading ClojureScript namespaces. In Clojure everything works fine but with rendered docs being a mix of both platforms the CLJS ones still show up.

I'm investigating and will update as soon as I know more :) 

I'll also update the title of this ticket to be about the no-doc issue and we can open another one to discuss/outline alternative approaches using `cljdoc.edn`.

**Comment by kkinnear** [comment]
The other thing about using `^:no-doc` in a namespace -- codox has to read and analyze the namespace before it looks at the meta-data.  Or I expect that it is going to do so, based on some issues I found in codox.  

I'm wondering if simply letting people tell cljdoc about which source files they want analyzed would be better than tying it to the namespace.  But that would require that cljdoc be able to either specify file names to codox, or just feed codox the relevant source files.  At present there is (near as I can tell), no way to tell codox "do this file, don't do that file".  It seems to digest all available files, and then decide what to do.  So unless cljdoc feeds the files to codox (and can make decisions about which ones to send and not to send), I don't know that this is going to be possible.

**Comment by martinklepsch** [comment]
> Which would explain what we both are seeing. So, maybe that route isn't going to solve the "don't document this namespace" request.

I opened a PR for Codox to fix this, which got merged already: https://github.com/weavejester/codox/issues/177

I agree that it would be useful to exclude certain namespaces or provide a selection of namespaces that should be included. If codox is preventing us from doing this we can open more PRs, fork or replace codox. Our usage of it is limited to the two reader namespaces I believe which would be acceptable to maintain on our own.

**Comment by martinklepsch** [comment]
I pushed some tweaks to `boot build-docs --help` yesterday allowing you to provide a custom (local) git repo and revision to use for the build. 

You can use this in combination with `boot run` to view docs and re-import them after adjustments. (`build-docs` imports the data into the same backing store that is used by the server.)

**Comment by martinklepsch** [comment]
@kkinnear I'm now using codox via tools deps / git which should have the fix for this.

https://github.com/cljdoc/cljdoc/blob/2d19bb4b1b39cfb2856ff61f29e275b18af5f469/modules/shared-utils/src/cljdoc/util/deps.clj#L40-L44

I'll close this issue for now but don't hesitate to re-open/reply if there are any further issues. Thanks :v:

**Comment by kkinnear** [comment]
Wow, you are amazing!  Thanks for making all of this work, it is very impressive.   Only the namespaces that I want are showing up now.
