### ISSUE TITLE
API Analysis failed "Permission denied"

### ISSUE THREAD

**Issue by somecho** [cljdoc/cljdoc#741]
https://cljdoc.org/builds/65010

Somehow my docs aren't building because of a permission issue. The docs were building for my library at version 0.2.1. Unfortunately, I'm not able to understand the error message to figure out whether it's an error on my end or not.

**Comment by lread** [comment]
Thanks for raising this issue @somecho.

It seems that CircleCI invalidated API tokens in response to [their recent security breach](https://circleci.com/blog/january-4-2023-security-alert/).
This is causing the permission denied error you are seeing.

@martinklepsch is aware of this and will reconfigure cljdoc.

**Comment by somecho** [comment]
Ah, okay, thanks for investigating!

**Comment by lread** [comment]
You are most welcome! We'll leave this one open until it is fixed.

**Comment by lread** [comment]
@martinklepsch has gotten things rolling again, :tada:
