### ISSUE TITLE
Not sure why this is trying to use Clojure 1.9.0 for tools.deps

### ISSUE THREAD

**Issue by puredanger** [cljdoc/cljdoc#742]
Tried to gen the docs for org.clojure/tools.deps 0.16.1264 and it failed.

Here's the build logs:

* https://cljdoc.org/builds/65082
* https://app.circleci.com/pipelines/github/cljdoc/builder/39001/workflows/01e5af56-79d3-4ea9-b62c-369702d65fbe/jobs/55375

It's clearly trying to use Clojure 1.9.0 as a dep but the deps.edn specifies 1.10.3, so not sure where that's coming from?

The pom at https://repo1.maven.org/maven2/org/clojure/tools.deps/0.16.1264/tools.deps-0.16.1264.pom declares a dependency on 1.10.3, but via a Maven property - is that problematic for cljdoc?

**Comment by lread** [comment]
Thanks for raising this issue @puredanger, I'll take a peek and report back.

**Comment by lread** [comment]
Ah. Although I've worked on cljdoc-analyzer, I don't know the rationale or history for this issue, but here is what is happening:

The cljdoc-analyzer is trying to bump an analyzed lib to a recent-ish version of Clojure.
At the time of this writing, it considers v1.9.0 recentish. 

It finds the analyzed lib's Clojure version by naively parsing the pom XML.

In this case, it literally sees `${clojure.version}` in the pom and does a version compare against `1.9.0` and `1.9.0` wins. 

I'll try to understand why cljdoc-analyzer thinks it needs to bump the Clojure version.
And if it still makes sense to do so, have it determine the version less naively (it already uses tools deps so probably via tools deps).

**Comment by lread** [comment]
Thanks @martinklepsch, that seems like a reasonable-sounding rationale.

I can leave in the recent-ish check and override, but update cljdoc-analyzer to determine the version in use less naively.

Another option would be to simply use the current version of Clojure (and ClojureScript) for analysis. But maybe recent-ish is better for some reason?

**Comment by puredanger** [comment]
1. there are lots of ways for naive parsing to go wrong (super poms, properties, etc) so my experience has it been that it is generally not sufficient
2. not an option- this is an intentional design choice
3. maybe an option and I could possibly carve out some stable paths
4. would be perfectly fine of course (that stuff is super annoying to use w/o their dependency injection frameworks) but I'm fine with you borrowing my work :)
5. not an option- this is an intentional design choice

Another option would be to use something like pomegranate which is more of a wrapper and less opinionated, but I'm not sure how well it's maintained.

**Comment by lread** [comment]
Thanks @puredanger, much appreciated and very helpful! 

Thanks for ruling out 5.

For 2, I was thinking of a strategic `alter-var-root` to monkey patch. Yes, gross, but worth mentioning. Maybe.

I think I'll avoid pomegranate for now. I'd like to stay closer to the tools-deps-way.

I think 3 might be nice. I could explore what I might use from that namespace.
If you decide that maintaining stable paths is not interesting to you, I could easily fall back to option 4 and ~~steal~~ borrow the fruits of your labour.

**Comment by lread** [comment]
Update: Seems like [pomegranate is getting at least some love at clj-commons](https://github.com/clj-commons/pomegranate). It has also switched from Aether to maven resolver libs, so that's good. So maybe worth exploring.

**Comment by lread** [comment]
Of interest: Had a look at clojars site to see what it is doing. It is using maven libs to parse poms, but it is not using maven libs to resolve/evaluate. As an example [pomegranate](https://clojars.org/clj-commons/pomegranate/versions/1.2.1), notice `${clojure.version}`, `${mavenVersion}`, etc, instead of actual versions.

![image](https://user-images.githubusercontent.com/967328/212150341-bcf5f47e-91a4-4582-ada7-b143d7477e97.png)

**Comment by lread** [comment]
@puredanger, fyi: tools.deps docs now build successfully on cljdoc.
