### ISSUE TITLE
Add asciidoc document attribute for cljdoc

### ISSUE THREAD

**Issue by gnl** [cljdoc/cljdoc#76]
...in order to be able to do stuff like this:

```
ifdef::env-github[]
:imagesdir: https://external-server/images
endif::[]
ifndef::env-github[]
:imagesdir: ../local-dir/images
endif::[]
```

https://asciidoctor.org/docs/user-manual/#conditional-preprocessor-directives

**Comment by martinklepsch** [comment]
@gnl are you using that somewhere or could point me to a library that does? We do some postprocessing of Markdown/Asciidoc output (grep `fixref`) to fix broken references to files/images which this seems to be related to?

For what it's worth Asciidoc is a very mature project, providing much more than just text formatting and and supporting all it's features while providing a consistent UX for end users may be challenging...

**Comment by gnl** [comment]
https://raw.githubusercontent.com/gnl/ghostwheel/master/README.adoc

I'm no asciidoc(-tor) expert, but I think you probably just have to pass your own document attribute (env-cljdoc or something) when calling asciidoctor to generate the HTML and then people can do whatever they need based on that.

**Comment by gnl** [comment]
Yup, seems to be as simple as that:

`asciidoctor --attribute env-cljdoc`

**Comment by martinklepsch** [comment]
Interesting, I think I see what you mean now. Guess it's a matter of passing that attribute in our Asciidoctor usage then: https://github.com/martinklepsch/cljdoc/blob/master/src/cljdoc/render/rich_text.clj

@gnl Do you want to take a stab at this? 🙂

**Comment by gnl** [comment]
Sure, just don't make me give you a timeframe, cause it's a busy week. :) But considering that this is just a convenience thing and that asciidoc isn't nearly as popular as it should be, I think it can probably wait a week or two.

Feel free to assign me to the issue.

**Comment by martinklepsch** [comment]
Oh, yeah, no rush. We could also consider just passing `env-github` since most URIs that work on GitHub should also work on cljdoc (relative and absolute ones). Thanks in advance!

**Comment by martinklepsch** [comment]
Hey @gnl, this came up recently again so I just wanted to check in if you maybe might any progress/insights hat could be built upon?

Don’t worry if not! 🙂
