### ISSUE TITLE
"Namespaces:  None Found"

### ISSUE THREAD

**Issue by cloojure** [cljdoc/cljdoc#763]
The above is the error message when I build a the last few versions of the Tupelo library.  I have made no changes that should result in such an error.  Any ideas?

https://cljdoc.org/d/tupelo/tupelo/23.03.16/doc/readme

**Comment by lread** [comment]
@cloojure, I'll take a peek and get back to ya.

**Comment by lread** [comment]
@cloojure, if I download tupelo 23.03.16 from clojars from here: 
https://repo.clojars.org/tupelo/tupelo/23.03.16/tupelo-23.03.16.jar

And then I take a peek at its contents like so:
```Shell
❯ unzip -l ~/Downloads/tupelo-23.03.16.jar 
Archive:  /home/lee/Downloads/tupelo-23.03.16.jar
  Length      Date    Time    Name
---------  ---------- -----   ----
       82  2023-04-24 14:46   META-INF/MANIFEST.MF
        0  2023-04-24 17:46   META-INF/
        0  2022-05-05 17:24   .dummy
        0  2023-04-24 17:46   META-INF/maven/
        0  2023-04-24 17:46   META-INF/maven/tupelo/
        0  2023-04-24 17:46   META-INF/maven/tupelo/tupelo/
      119  2023-04-24 17:46   META-INF/maven/tupelo/tupelo/pom.properties
     4133  2023-04-24 17:46   META-INF/maven/tupelo/tupelo/pom.xml
---------                     -------
     4334                     8 files
```
Cljdoc analyzes a library's API from Clojure sources found in its jar, but there don't seem to be any Clojure sources in this jar.

**Comment by lread** [comment]
@cloojure do my findings make sense to you too?
Shall we close this issue?

**Comment by cloojure** [comment]
Hi - It looks like JAR file creation is broken somehow.  I'll look into it.
Thanks for the review,
Alan

**Comment by cloojure** [comment]
OK, I fixed the problem with the JAR and the docs build correctly again.
Thanks,
Alan

**Comment by lread** [comment]
Cool, thanks for following up @cloojure!
