### ISSUE TITLE
Render asciidoc captions like GitHub

### ISSUE THREAD

**Issue by gnl** [cljdoc/cljdoc#77]
```
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
```

The result looks like this:

:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:

**Comment by martinklepsch** [comment]
Not sure what you mean, here... can you point me to an example file (Gist maybe)? Supporting emojis would definitely be nice but I think that's not the only thing you're suggesting 🙂

**Comment by gnl** [comment]
Yup, this one:
https://github.com/gnl/ghostwheel/blob/master/README.adoc#how-to-read-a-readme

GitHub seems to have those predefined and mapped to `:bulb:`, etc.

**Comment by martinklepsch** [comment]
Ahh, interesting, got it.

**Comment by martinklepsch** [comment]
Maybe this is as easy as prepending the following to every Asciidoc document we're rendering:

```
ifdef::env-cldjoc[]
:tip-caption: 💡
:note-caption: ℹ
:important-caption: ❗️
:caution-caption: 🔥
:warning-caption: ⚠️
endif::[]
```

Note that I used the unicode representations of these icons since cljdoc does not yet support GitHub style `:emoji:`.

**Comment by martinklepsch** [comment]
While icons are nice they always require some more setup (image files etc) so I just went with something that stands out and works with plain CSS for now.

Below are some examples from [nrepl's server usage documentation](https://cljdoc.org/d/nrepl/nrepl/0.5.3/doc/usage/server).

<img width="806" alt="screenshot 2019-01-15 at 12 16 41" src="https://user-images.githubusercontent.com/97496/51177326-98a0b580-18bf-11e9-882e-bf97e362bec2.png">
<img width="792" alt="screenshot 2019-01-15 at 12 16 49" src="https://user-images.githubusercontent.com/97496/51177325-98a0b580-18bf-11e9-8e3f-7c1980f344d6.png">
<img width="787" alt="screenshot 2019-01-15 at 12 16 58" src="https://user-images.githubusercontent.com/97496/51177323-98081f00-18bf-11e9-85c5-b48caf07bd57.png">
