### ISSUE TITLE
Improve the readability of the IMPORTANT 

### ISSUE THREAD

**Issue by tengstrand** [cljdoc/cljdoc#791]
Today when showing an important note:

```
====
IMPORTANT: Some problem
====
```
The background is a bit too "loud":

<img width="330" alt="image" src="https://github.com/cljdoc/cljdoc/assets/631272/566a2609-46d4-44bd-b999-227f4cb83566">

I also think it's more harmonious if both the "bar" and the background are red, e.g. ffc9c9:

<img width="323" alt="image" src="https://github.com/cljdoc/cljdoc/assets/631272/e13b0ab8-7298-4eb3-836c-6c0b6517bc5b">

This will also improve the contrast and the readability.

**Comment by lread** [comment]
Thanks for the feedback @tengstrand, much appreciated.

Here's the current stylings for all [adoc admonitions](https://cljdoc.org/d/org.cljdoc/cljdoc-exerciser/1.0.94/doc/document-tests/asciidoctor-features#_admonitions):
<img width="791" alt="image" src="https://github.com/cljdoc/cljdoc/assets/967328/ffa03ee5-7ad0-4857-a398-43b8dcc63df4">

I think your proposed styling for IMPORTANT would now be the same or similar to WARNING.

The current design is a bit challenging:
1. we've limited ourselves to the [Tachyons colours](https://tachyons.io/docs/themes/skins/)
2. choosing distinct and meaningful background colours for admonitions is... tricky.

We could break rule 1 if IMPORTANT is really too garish.

Thoughts/ideas?

This [old issue comment](https://github.com/cljdoc/cljdoc/issues/327#issuecomment-512615555) might help.

**Comment by tengstrand** [comment]
Ohh, should have checked the other colors first!

My suggestion is that we break rule 1 and change it to something like this:
<img width="475" alt="image" src="https://github.com/cljdoc/cljdoc/assets/631272/2be5d52a-a357-45f8-b18c-78f4741560d2">

The colors are:
- background: f8cfe8
- left bar: c783aa
- heading: 762a55

This is of course just an example, but I tried to maximise the contrast and make the colors look more similar to the others!

**Comment by lread** [comment]
Thanks, ya, I think that looks better too!

I can make it so after @martinklepsch helps me to figure out why with cljdoc deployment is not currently working.

**Comment by tengstrand** [comment]
Okay, cool! Thanks.

**Comment by tengstrand** [comment]
Looks good! And the scrolling to the selected page in the left menu also works now. Thank!

**Comment by lread** [comment]
> Looks good! 

Thanks for your help on this!

> And the scrolling to the selected page in the left menu also works now. Thank!

That I did nothing for yet, so maybe it sometimes works and sometimes doesn't?
It's still on my todo list to have a peek at.

**Comment by tengstrand** [comment]
Okay, interesting (about the scrolling)!

**Comment by tengstrand** [comment]
When I tested the scrolling again, it didn't work. Maybe it has to do with which browser we use.
