### ISSUE TITLE
ops: automatic deploy is failing

### ISSUE THREAD

**Issue by lread** [cljdoc/cljdoc#795]
## Sometimes
We fix ops issues without a GitHub issue, but I thought it might be useful to log the symptom and eventual solution. This might help us in the future for similar problems.

## Currently
Automatic deployment to production from the `deploy-to-nomad` CircleCI job is failing with:

```
INFO [2023-08-07 14:52:17,439] main - cljdoc.deploy check for existence of docker tag 0.0.2255-5259ef1 returned 200
INFO [2023-08-07 14:52:17,440] main - cljdoc.deploy Deploying to Nomad server at *************:4646
** ERROR: **
Exception: #error {
 :cause Auth fail
 :via
 [{:type com.jcraft.jsch.JSchException
   :message Auth fail
   :at [com.jcraft.jsch.Session connect Session.java 519]}]
 :trace
 [[com.jcraft.jsch.Session connect Session.java 519]
  [cljdoc.deploy$cli_deploy_BANG_ invokeStatic deploy.clj 161]
  [cljdoc.deploy$cli_deploy_BANG_ invoke deploy.clj 157]
  [cli_matic.core$invoke_subcmd invokeStatic core.cljc 546]
  [cli_matic.core$invoke_subcmd invoke core.cljc 525]
  [cli_matic.core$run_cmd_STAR_ invokeStatic core.cljc 589]
  [cli_matic.core$run_cmd_STAR_ invoke core.cljc 560]
  [cli_matic.core$run_cmd invokeStatic core.cljc 601]
  [cli_matic.core$run_cmd invoke core.cljc 591]
  [cljdoc.deploy$_main invokeStatic deploy.clj 177]
  [cljdoc.deploy$_main doInvoke deploy.clj 175]
  [clojure.lang.RestFn applyTo RestFn.java 137]
  [clojure.lang.Var applyTo Var.java 705]
  [clojure.core$apply invokeStatic core.clj 667]
  [clojure.main$main_opt invokeStatic main.clj 514]
  [clojure.main$main_opt invoke main.clj 510]
  [clojure.main$main invokeStatic main.clj 664]
  [clojure.main$main doInvoke main.clj 616]
  [clojure.lang.RestFn applyTo RestFn.java 137]
  [clojure.lang.Var applyTo Var.java 705]
  [clojure.main main main.java 40]]}

Exited with code exit status 255
```

## My first guess
was that I had broken CI deployment. I was moving several dev tasks over to babashka tasks and I thought I had maybe gotten something wrong.

But I reverted my changes and the deploy still failed with the same symptom.

## So I reached out to our ops team
which is currently @martinklepsch! 

He mentioned that he had updated the ssh authorized keys on the cljdoc server recently and this might be the cause.

## Then I did what exploring I could...
I had a peek at our authorized key file on the cljdoc server and it has a file date of 2 Aug.
Our last auto-deploy was on 26-July-2023 so Martin's guess is gaining some real credibility!

I looked at our CirclCI settings for cljdoc, and we do have an extra ssh key setup, [which our config is using for deployment](https://github.com/cljdoc/cljdoc/blob/5259ef128e91177656c87642a2aa4499356c6fe0/.circleci/config.yml#L271-L276), and... which our cljdoc server does not seem to have in its authorized keys list.

Here's my guess at a fix:
1. CircleCI lets us ssh into a job. Do that to discover public key.
2. Copy that key to the cljdoc server authorized key file.
3. Celebrate extreme success

**Comment by martinklepsch** [comment]
I was able to generate the public key using the following command after logging into the CircleCI build box:
```
ssh-keygen -y -f ~/.ssh/id_rsa_75fb981ff6217fbfccc90eb29ebe5ce8
```
After adding the output to the `authorized_keys` file on the cljdoc instance the build appears to be working again 🥳

**Comment by martinklepsch** [comment]
Sorry for breaking this, my bad really! 

While investigating I'm also painfully reminded that my Terraform setup has some bit rot and just doesn't seem to be working anymore. 🙈 I remember trying to upgrade this before but wasn't able to complete it before losing my pace...

**Comment by lread** [comment]
Hey stuff happens, this does not diminish our ❤️ for you @martinklepsch!

I'd love to help with understanding maintaining ops infra. 
I now vaguely remember you being in a middle of a Terraform upgrade that was not ready to be committed. 

How can I help? The only thing I can think of is setting up a parallel infrastructure and getting this working there. But maybe there is some lighter approach that would work.

**Comment by lread** [comment]
I just double-checked extreme success by pushing an empty commit to force a deploy.

Thanks for the fix @martinklepsch!
