### ISSUE TITLE
A link to an anchor named `version` within an article does not work

### ISSUE THREAD

**Issue by lread** [cljdoc/cljdoc#803]
## On Slack
@tengstrand was asking why the equivalent of the following was not working for an AsciiDoc file.

```adoc
link:#version[link text]

[#version]
== Version
```
When he clicked on `link text` nothing seemed to be happening.

## Diagnosis
I reproduced the issue locally.

I dropped to the browser console and ran the following:
```Javascript
> document.getElementById('version')
<input id="version" class="pa2 mr2 br2 ba outline-0 blue" name="version" type="hidden" value="0.2.18-issue318-02">
```
This is a cljdoc generated hidden `input` element with an `id` of `version` to support the hidden rebuild button. So a link to `#version` is hitting that instead of the section header.

## Does cljdoc generate other tags with an id attribute?
If I run the following from the browser console:
```JavaScript
document.querySelectorAll('[id]')
```
I do also see cljdoc generated
- another hidden `input` with an `id` of `project`
- `js--mobile-nav` and `js--single-docset-search`
- `doc-html`
- `prev-article-page-link`, `next-article-page-link`
- `js--meta-icon`
- `js--meta-dialog`
- `js--meta-close`
- `no-js-warning`
- `cljdoc-switcher`

And these seem to come from the adoc converter:
- `toc`
- `toctitle`
- `preamble`

I think I won't bother addressing adoc generated `id` attributes at this point.

I'm not too concerned with the `js--*` ids. They are obscure enough not to conflict with user anchors. But I'll review all `id` attributes that cljdoc generates, I expect I can turf most, if not all of them.

**Comment by tengstrand** [comment]
I have verified that it works now. Thanks!
