### ISSUE TITLE
Code blocks within tables are not rendered consistently

### ISSUE THREAD

**Issue by tengstrand** [cljdoc/cljdoc#805]
If I surround one or several words with a backtick like `this` in a table, the grey background is not always displayed.

This works [here](https://github.com/polyfy/polylith/blob/11ed024316ec74ee79b9bc40b7f919875eabef99/doc/libraries.adoc?plain=1#L9-L16):
<img width="865" alt="image" src="https://github.com/cljdoc/cljdoc/assets/631272/b1d7dad9-adb3-4933-a431-94f3ddddd33e">

But not [here](https://github.com/polyfy/polylith/blob/11ed024316ec74ee79b9bc40b7f919875eabef99/doc/flags.adoc?plain=1#L14-L16):
<img width="381" alt="image" src="https://github.com/cljdoc/cljdoc/assets/631272/f779b214-15cb-4593-82e5-f4222133ac57">

It would be nice if this could be rendered more consistently.

**Comment by lread** [comment]
That does seem odd. I shall take a peek sometime soon.

**Comment by lread** [comment]
Tracked it down: https://github.com/asciidoctor/asciidoctor/issues/3384#issuecomment-1676405772

I think it would be safe for me to change our CSS, and then if we discover there actually was a good rationale for this rule, then adapt.

**Comment by tengstrand** [comment]
FYI. I removed the backticks for the status column that had only one word, because it was more readable without it, so the fix is will not affect me any more, but may be worth fixing anyway.

**Comment by lread** [comment]
Thanks for the update! I agree it is still worth a fix if only to avoid future confusion.

**Comment by lread** [comment]
We did get a [clear rationale back from the author of asciidoctor](https://github.com/asciidoctor/asciidoctor/issues/3384#issuecomment-1679337314), I'll re-open this one.

For users of cljdoc this is probably an edge case, I don't know how many folks use the `m` style operator.  Example:

```asciidoctor
|===
m| I am monospace and should not have a background colour   
|===
```

But now that we have a clear rationale, I'll reverse my styling change here to stay in synch with default adoc styling.

If this comes up in the future we can recommend the workaround of using the `a` style operator to force a background on code elements.

Example:

```asciidoctor
|===
| `no background`    | also `no background`    
a| `got background` a| also `got background`
|===
```
