### ISSUE TITLE
tools.build cookbook link is 404-ing

### ISSUE THREAD

**Issue by tylernisonoff** [cljdoc/cljdoc#817]
The [Building Projects: tools.build and the Clojure CLI](https://clojure-doc.org/articles/cookbook/cli_build_projects/) link on [Tutorials and Cookbooks](https://clojure-doc.org/articles/content/#tutorials-and-cookbooks) page is 404-ing.

**Comment by lread** [comment]
Hi @tylernisonoff nice catch but wrong repo! You want to be raising this issue here: https://github.com/clojure-doc/clojure-doc.github.io

**Comment by tylernisonoff** [comment]
ahh sorry about that!

**Comment by lread** [comment]
No prob! It is great that you are finding and reporting issues!
