### ISSUE TITLE
Can't download the CURRENT version of the doc

### ISSUE THREAD

**Issue by tengstrand** [cljdoc/cljdoc#818]
I can download the latest version of the polylith documentation by using the link https://cljdoc.org/download/polylith/clj-poly/0.2.17-alpha.

Unfortunately the link https://cljdoc.org/download/polylith/clj-poly/CURRENT doesn't work.

It would be convenient if it did, so that I don't have to hard code a version in the documentation.

**Comment by lread** [comment]
Hi @tengstrand! You've piqued my curiosity here. 
I don't know of many users who use offline docs.
This is currently kind of a hidden, but documented, feature.
My understading is that folks who use this feature often do so via [Dash](https://kapeli.com/dash), but Dash does the downloading for them.

Do you anticipate polylith users will be interested in downloading docs to read offline?

All that said, you request seems reasonable to me, and I am happy to do it, I just want to make sure I need to do it.

**Comment by tengstrand** [comment]
Okay, I see! 

I had an idea of showing a `download` badge at the top of the page: 

![image](https://github.com/cljdoc/cljdoc/assets/631272/bf5daedb-924d-4a5a-b758-fcf0fbc25a7f)

The reason I thought that could be useful, was because some users wanted the previous Gitbook based documentation as a PDF.

I can have a look at Dash and see if that solves my problems and come back to you!

**Comment by lread** [comment]
Ah, I see! Thanks for sharing the problem you are trying to solve.

It would be interesting to know why users wanted a PDF version. What problem are they trying to solve? Maybe they want to read offline. Maybe they want to read on an eReader. Maybe they want to print docs in a book-type form.

Note that Dash is macOS only and not expensive, but not free.

**Comment by tengstrand** [comment]
I can ask in the polylith Slack channel to see how big the need it.

**Comment by tengstrand** [comment]
I only got two replies to my question and both said they had no need for offline documentation, so I think we can close this one!

**Comment by lread** [comment]
Thank you for following up @tengstrand!
