### ISSUE TITLE
TypeError: NetworkError when attempting to fetch resource

### ISSUE THREAD

**Issue by j-cr** [cljdoc/cljdoc#82]
When I input something into the "NEW! Jump to docs..." textbox and press enter, nothing happens and the following message is printed to the console: `TypeError: NetworkError when attempting to fetch resource`.

Firefox 60.0.2

**Comment by j-cr** [comment]
Edit: `Blocked loading mixed active content...` actually doesn't happen after a forced (ctrl-f5) refresh - my bad! - so I've removed that from the description; the issue is not affected.

**Comment by j-cr** [comment]
Any input. Looks like it happens on firefox only with Privacy Badger extension enabled. Google tells me it's probably related to CORS and wrong headers from the server. Sorry, that's all I've got so far.

**Comment by martinklepsch** [comment]
I'll close this to keep issues clean, if anyone has suggestions on how to fix this feel free to reopen.
