### ISSUE TITLE
UI to quickly switch between recently viewed project's docs

### ISSUE THREAD

**Issue by aviflax** [cljdoc/cljdoc#83]
As per [this discussion](https://clojurians.slack.com/archives/C8V0BQ0M6/p1532371435000460?thread_ts=1532371365.000484&cid=C8V0BQ0M6):

* There are some docsets to which I frequently refer that are hosted in Maven and not Clojars and thus don’t (currently) show up in the cljdoc search results.
* Those docsets _are_ accessible via manually-constructed URLs, [like so](https://cljdoc.xyz/d/org.clojure/spec.alpha/0.2.168/)
* Such URLs are somewhat inconvenient to build and then save.
* Therefore, it’d be cool if the site:
   1. Kept track of my recently and/or frequently visited docsets
      * In a secure, private, and convenient fashion
           * Where by “convenient” we mean that this feature would ideally not require any kind of logging in or signing in
           * e.g. via [The Web Storage API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API) or [IndexedDB](https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API)
   1. Made links to those docsets readily and conveniently available and at-hand
      * e.g. in some kind of a sidebar and/or in a pop-up “quick navigator” UI similar to a file/symbol finder in an IDE or GitHub (press `t` when viewing any file in a repo) or the channel picker in Slack (press `cmd-k` or `ctrl-k` in the native app).
   1. (Stretch goal) Enabled users to manually add/remove docsets from the list
      * This might make it more like a “favorites” list … which might be great… or might be confusing!

**Comment by martinklepsch** [comment]
Made some progress on this today, demo here: https://imgur.com/a/8Z1bwm5

It's also live on cljdoc.xyz, just it <kbd>k</kbd> to bring it up. Note that you need to navigate around a few projects for a list of projects to be available. 

Keyboard shortcut isn't final, happy about feedback in that regard and just haven't looked up what practices exist around that stuff. 

Also this UI may also be expanded to switch between namespaces, find vars and articles within a project. Imagining this similar to how GitHub's search works (either scoped to project or global).

**Comment by aviflax** [comment]
Looks fantastic!

**Comment by martinklepsch** [comment]
I'll close this as the basic feature has been shipped, lets open new tickets for further improvements.
