### ISSUE TITLE
Implement proper search for cljdoc database to replace use of Clojars API

### ISSUE THREAD

**Issue by martinklepsch** [cljdoc/cljdoc#85]
The search on the cljdoc.xyz homepage currently only searches Clojars using Clojars' own API. This may result in surprising search results when search for artefacts like Clojure itself, clojure.spec or similar.

---

#### Option 2: Use some search API for Maven Central and filter the result

---

There are pros and cons to each option. May expand on this later.

Related to some issues outlined in #83

**Comment by holyjak** [comment]
Isn't nr. 1 a quick fix and thus worth doing before eventually implementing nr 2? 

Also, since there already is documentation for (some of?) these libraries in cljdoc (e.g. https://cljdoc.org/d/org.clojure/data.json/), cannot we query cljdoc's own metadata (instead of talking to maven central)? Any pointers to the relevant code? Thanks!

**Comment by martinklepsch** [comment]
@holyjak yes, doing **#1** first would definitely make sense, especially since Clojure artefacts on Maven Central are fairly well known and mostly under `org.clojure/`. 

#### As for how things work currently:

- cljdoc does not have any built in search capabilities. The search on the front page and the search that Dash is using is both powered by Clojars, coming down to essentially this: https://github.com/cljdoc/cljdoc/blob/7eb4fbf9696acaffceb714f3593c9cf8ff97e7ef/js/search.js#L23-L28
- This is problematic because it 
  1. doesn't include stuff from Maven Central and
  2. will often show unexpected results before the thing you're actually looking for, see
    
       ```
       curl 'https://clojars.org/search?q=re-frame&format=json' | jq
       ```

#### How to improve this

(This is just an idea, totally open to other approaches.)

- Set up Lucene to index all projects on Clojars as well as the ones from the manually created list (e.g. for Maven Central)
- Use Lucene for the search on the homepage & work with Dash maintainer to use that as well
- Currently cljdoc's `versions` table **does not contain all artifacts** on Clojars but only the ones that documentation has been built for. So there might be some things to be figured out as to what data sources to use to feed into the index.
- I wrote some code that has been parked in #233 that we could use as input to sort by downloads/popularity (arguably a stretch goal)

If you're interested in helping with this I'd be happy to pair and/or provide more direction as needed.

**Comment by holyjak** [comment]
### 1. Search engine

Any specific reason why you want to set up and run Lucene yourself? Wouldn't it be easier (and "cheaper" in Ops time) to use an existing service such as AWS ElasticSearch or, perhaps optimally, https://www.algolia.com/ which is free for "small" non-comercial projects ([docs](https://www.algolia.com/doc/guides/getting-started/how-algolia-works/in-depth/implementation-process/), [data entry](https://www.algolia.com/doc/guides/sending-and-managing-data/prepare-your-data/), REST/[java client](https://www.algolia.com/doc/api-client/getting-started/install/java/)/[JS client](https://www.algolia.com/doc/api-client/getting-started/install/javascript/))? 

I could give Algolia a spin, trying to index Clojars & some maven with custom ranking (boost clojure core/contrib?, # downloads, ...) and get back to you with results & follow up with integration? 

1. BTW, where/when would we run this? A scheduled AWS lambda 1/d???
2. Should we, at least in version 1, just use the JS client to replace the current JS search with algolia backed one?
3. What about the versions table, should we filter results by using it ?

**Comment by avichalp** [comment]
Great idea! 
If we can use Algolia's free tier that will save us a lot of effort creating and maintaining a Lucene index.

**Comment by martinklepsch** [comment]
@holyjak Algolia and similar tools are certainly an option! I think Algolias community plan might be a little bit too constrained with 10K records but maybe it's just enough.

http://clojars.org/repo/all-poms.txt contains 180K entries but this includes multiple versions and we'd probably get away with having just one version in the index. 

All that said Lucene can be embedded within cljdoc. In contrast to ElasticSearch (which is based on Lucene) it does not require it's own process/server. The [various](https://github.com/weavejester/clucy) [Lucene](https://github.com/federkasten/clucie) [libraries](https://github.com/jaju/lucene-clj) all seem fairly easy to work with.

One reason I'm also leaning towards Lucene is that developers will just be able to work with it locally without creating an Algolia account, getting API keys and so on. With Lucene embedded you'd not even need to know it's there. To me that's a big deal in terms of developer experience and ease of setup. 

> If we can use Algolia's free tier that will save us a lot of effort creating and maintaining a Lucene index.

@avichalp We'll need to create and maintain the Algolia index too. What Algolia would get us is it's very nice UI components but I think what's there currently is actually pretty alright.

> BTW, where/when would we run this? A scheduled AWS lambda 1/d???

There's a bunch of background jobs on the cljdoc server already. For instance there is a piece of code which monitors Clojars for new releases: https://github.com/cljdoc/cljdoc/blob/7eb4fbf9696acaffceb714f3593c9cf8ff97e7ef/src/cljdoc/server/release_monitor.clj#L74-L78

I reckon we could just use the same approach for feeding new data into Algolia or Lucene.

**Comment by avichalp** [comment]
@martinklepsch You are right we need to create and maintain the index on Algolia too. Sorry, my wrong choice of words. What I meant earlier was, with Algolia or other such tools we don't have to think about storage. Making sure the index doesn't get too large and files are not corrupted. If that is not an issue on the ops side then I am sold on Lucene. Also as you mentioned development will be easier with Lucene without worrying about Algolia account and API keys etc.

Just thinking out loud. Would it make sense to have Lucene for development and Algolia or some other tool for production? 🤔

**Comment by martinklepsch** [comment]
> Just thinking out loud. Would it make sense to have Lucene for development and Algolia or some other tool for production? 🤔

I'm not seeing much of an upside to this but happy to be convinced otherwise. 🙂

**Comment by danielcompton** [comment]
Ideally Clojars would fix search in such a way that it works for both of us. I’ll try and take a look soon, as the results are pretty bad in some cases.

**Comment by martinklepsch** [comment]
It would be great to see Clojars' search improved but due to the fact that cljdoc also has some stuff from Maven Central I think we'll need to implement our own search one way or another...

**Comment by holyjak** [comment]
FYI Here is the search code for Clojars https://github.com/clojars/clojars-web/blob/master/src/clojars/search.clj 

I think it would be ideal to fix it so that Clojars gets better search (so that searching for "clj-con" returns "clj-concordion" as the first match instead of "clj-hash" & many others). Then we can use the ± same code in cljdoc to index Clojars and Maven Central.

**Comment by holyjak** [comment]
FYI I got indexing and searching working and am now working at fine-tuning it. Next step will be to integrate it into cljdoc (data retrieval -> indexing, web -> search). See https://github.com/holyjak/tmp-clj-artifact-search

**Comment by holyjak** [comment]
FYI I am quite happy with my search results now, though I want to keep on improving them later. But now I want to figure out how to integrate it into cljdoc. A next step will be the addition of Maven Central.

**Comment by martinklepsch** [comment]
Awesome! I’ll be free from Monday if you have questions/want to pair. Looking forward 🙌
