### ISSUE TITLE
re-frame build broken since 1.4.0 (current version is 1.4.2)

### ISSUE THREAD

**Issue by aviad** [cljdoc/cljdoc#853]
Looking at the docs for `re-frame`, starting at [version 1.4.0](https://cljdoc.org/d/re-frame/re-frame/1.4.0/doc/readme) docs are broken, saying:
[API import failed in build #73467](https://cljdoc.org/builds/73467)

I'm happy to try and help, just need some pointers about where to start looking and fixing.

CC @kimo-k (publisher of latest re-frame version)

**Comment by lread** [comment]
Thanks for the sleuthing @corasaurus-hex!

> I'm not sure but I don't _think_ there's a way to specify a specific profile to use. @lread ?

That is correct, there is no way to specify a profile. Cljdoc always analyzes from the API from the jar sources. 

Our current solution for satisfying optional dependencies for API analysis is [specifying them as provided in your deployed pom](https://github.com/cljdoc/cljdoc/blob/master/doc/userguide/for-library-authors.adoc#getting-dependencies-right).

**Comment by kimo-k** [comment]
Hey, thanks for waiting 3 weeks. I think it's okay now - https://cljdoc.org/d/re-frame/re-frame/1.4.3

**Comment by martinklepsch** [comment]
Great news, thank you for investigating and fixing the build 🙌

**Comment by lread** [comment]
Congrats!
