### ISSUE TITLE
Sort vars by occurrence (line number)

### ISSUE THREAD

**Issue by martinklepsch** [cljdoc/cljdoc#89]
Currently vars are sorted by name, this is the most basic way of sorting stuff but we also have line numbers and the order functions are defined can often provide some useful context.

Let's sort stuff by line number instead of name.

**Question** Should this also apply to ["index listings"](https://cljdoc.xyz/d/compojure/compojure/1.6.1/api/compojure)?

**Comment by lread** [comment]
To summarize our chat on Slack: we agreed that users could be confused if library a sorted one way and library b sorted another.

Let's go over some options for implementation.

I've marked my thinking/proposal for an initial release.

1. User sets sort order via UI (design TBD)
2. Library author: choices:
   1. :heavy_check_mark: has no control over sort order
   2. :heavy_multiplication_x: can specify default for their library in `cljdoc.edn`
3. Sort order choices are: alphabetical, by line number.
4. Sort order defaults to current order: alphabetical.
5. Sort affects vars listed in: choices:
   1. :heavy_check_mark: namespaces summary page
   2. :heavy_check_mark: namespace detail page
6. User sort order preference is: choices:
   1. :heavy_multiplication_x: not retained
   1. :heavy_check_mark: retained globally
   1. :heavy_multiplication_x: retained for each library
7. Sort order change requires:
   1. :heavy_check_mark: page reload
   2. :heavy_multiplication_x: immediately applied in-page
8. Sort order does not affect offline (downloaded) docsets. Vars will remain alphabetically sorted.
8. Sort order does not affect namespace order.

**Comment by martinklepsch** [comment]
Hey @lread 👋  Your proposal makes a lot of sense to me. I feel fairly strongly that this should be a user choice, not a library author choice. A consistent documentation viewing experience is a main pillar of cljdoc :)

**Comment by corasaurus-hex** [comment]
It absolutely should be a user choice and not a library author's choice, and the default should be what's most predictable and consistent. An author could recommend different sorting in some way, perhaps, but defaults should be what users expect.

**Comment by lread** [comment]
I think we discussed this on Slack a while back and decided against doing this.
