### ISSUE TITLE
No longer-existant :scope "test" dependency breaks analysis

### ISSUE THREAD

**Issue by plexus** [cljdoc/cljdoc#90]
Currently building docs for kixi.stats fails

https://circleci.com/gh/martinklepsch/cljdoc-builder/3024

The reason is kixi.stats has a dev-dependency on Incanter, and Incanter uses an old version of itextpdf, which relies on a version of bouncycastle that no longer exists.

https://github.com/MastodonC/kixi.stats/issues/17
https://github.com/incanter/incanter/issues/388#issuecomment-409518543

However since this is only a `:dev` dependency I would think cljdoc could ignore it. Poking around the source it seems cljdoc currently grabs all dependencies in the library's pom, regardless of their `<scope>`

- is it necessary to grab those dependencies from the pom? why not only add the library itself and let `clj` resolve its dependencies?
- would it be possible to exclude dependencies with `<scope>test</scope>`?

**Comment by martinklepsch** [comment]
Thanks for reporting this @plexus! Unfortunately dependencies are a tricky aspect. 😃

Some libraries contain namespaces that use additional dependencies the library user is expected to provide. Without those dependencies analysing the namespace will fail. Yet other libraries are like what you described — their "extended dependencies" are invalid in some way. Library authors don't necessarily use scopes, `:dev` dependencies and related features in a consistent manner making it even harder to accurately predict what dependencies to load.

cljdoc currently loads all dependencies it finds in a projects `.pom` regardless of their scope, simply hoping that all required libraries are mentioned there.

To solve this particular issue there are a few things we can do:

1. Only include dependencies with `:scope "provided"`, not `"test"` and see how that affects builds
2. Make it easier to hardcode exceptions in cljdoc code (i.e. dropping/replacing a specific old bouncy castle dependency if it is found) 
3. Ideally we should not fail hard when a namespace can't be analysed but instead track that namespace name and the exception. That information can then be presented to a user to indicate namespaces that couldn't be analysed / might need some tweaks. 

1 & 2 are relatively easy to do, the code is in [`deps.clj`](https://github.com/cljdoc/cljdoc/blob/f62ca5732676430a28c087691ce6fab313d0aea4/modules/shared-utils/src/cljdoc/util/deps.clj) if anyone feels like hacking on this. 2 is also a bit of a hack really but I think there will always be strange edge cases and in this case I would like to make it as easy as possible (and minimally intrusive) to customise cljdoc to handle those edge cases.

**Comment by martinklepsch** [comment]
PS. "Failing hard" when a namespace can't be analysed has been a deliberate choice in order to be more aware of failing builds and clearly indicate to users when something didn't go according to plan.

**Comment by martinklepsch** [comment]
Incanter has been removed from kixi.stats and `0.4.2` is now available on cljdoc: https://cljdoc.xyz/d/kixi/stats/0.4.2/api/kixi.stats.core

I figure we could close this and see if a similar issue pops up again? As far as I can tell builds fail more often because of missing dips than they fail due to invalid deps.

**Comment by plexus** [comment]
Sounds good!
