### ISSUE TITLE
Support Table of Contents/TOC for Markdown files

### ISSUE THREAD

**Issue by NoahTheDuke** [cljdoc/cljdoc#910]
Asciidoc shows a top level table of contents by looking for `:toc:`. Markdown by default doesn't support this, but Flexmark has a [Table of Contents Extention](https://github.com/vsch/flexmark-java/wiki/Table-of-Contents-Extension) that supports a similar syntax: `[TOC]` or `[TOC style]` where `style` is configuration as noted in the page for the extension.

Related to #20, but that's very old and seems to be obsolete?

**Comment by lread** [comment]
Hi @NoahTheDuke!

We try to support a reasonable subset of GitHub-flavored Markdown for articles.

Supporting extensions not included in GitHub-flavored Markdown is not a road we want to travel at this time.

Asciidoc's `:toc:` feature is one of the many reasons I prefer AsciiDoc over Markdown.

**Comment by NoahTheDuke** [comment]
Well, that sucks. Thanks anyway.

**Comment by lread** [comment]
Issues and ideas are always welcome! I hope you get the rationale for a nogo on this one!

**Comment by NoahTheDuke** [comment]
I see the reasoning for mirroring Github's markdown (so readmes look the same as the website) but I think that's a pretty severe limit, given that this is aiming to be a documentation website, not a "render github readmes" website. Cljdoc already goes far beyond what Github renders with the API documentation.

I won't belabor the point as you've made up your mind. I'll figure something else out.

**Comment by lread** [comment]
> I won't belabor the point as you've made up your mind. I'll figure something else out.

So for changes to cljdoc I have to ask:
1. Is the change benefiting many cljdoc users? You are the only one I know of who has asked for this
2. Is the change in the spirit of cljdoc? Not currently, we don't support any markdown extensions beyond what github supports (with the exception of wikilinks in docstrings).
3. Do I want to support and maintain the change forever? (I'm the only current active maintainer of cljdoc) - given 1 and 2 above, no!

Also submitting a PR before any discussion will never help your cause! :slightly_smiling_face:

**Comment by NoahTheDuke** [comment]
hah Yeah, I jumped the gun on the PR. I thought, "He already did all the work to implement the markdown alerts for me, no need to ask him to do this one, which should be much easier." but checking in first was the smart move.

**Comment by NoahTheDuke** [comment]
I reached out to lread in a private message, but I'd also like to make it clear in public: I was rude and demanding in this issue, and I'm sorry for it. Open source work is hard enough without people like me being an asshole, and I can and should do better. Thanks for cljdoc, lread.

**Comment by lread** [comment]
@NoahTheDuke, this is one of the reasons that I really appreciate and value the Clojure community. Such decent folks!
