### ISSUE TITLE
Build step failing because of a missing test library on a test wrapper function

### ISSUE THREAD

**Issue by rafaeldelboni** [cljdoc/cljdoc#951]
This is an function wrapper over a lib that is declared only in the [deps test alias](https://github.com/parenthesin/components/blob/main/deps.edn#L30)

Is there a way to point this alias on this step? What is the best approach to solve this build error?

https://app.circleci.com/pipelines/github/cljdoc/builder/56926/workflows/358c1aa3-f76e-4059-9bba-7bdbaf1aa154/jobs/73301/parallel-runs/0/steps/0-105

**Comment by lread** [comment]
Hi @rafaeldelboni, thanks for reaching out! I'll take a look and respond soon.

**Comment by lread** [comment]
Cljdoc discovers a library's public API by analyzing its deployed jar.
It does so by dynamically loading each namespace it finds in the jar.
 
If we forget about cljdoc for a moment and try to use `parenthesin/components` `v0.4.0` as a regular user, we can see that a regular user will run into the same problem that cljdoc does:

```clojure
$ clj -Sdeps '{:deps {com.github.parenthesin/components {:mvn/version "0.4.0"}}}'
Clojure 1.12.0
user=> (require '[parenthesin.helpers.state-flow.db :as foo])
Execution error (FileNotFoundException) at parenthesin.helpers.state-flow.db/eval138$loading (db.clj:1).
Could not locate state_flow/api__init.class, state_flow/api.clj or state_flow/api.cljc on classpath. Please check that namespaces with dashes use underscores in the Clojure file name.
```

If we take a peek at the deployed pom:
https://repo.clojars.org/com/github/parenthesin/components/0.4.0/components-0.4.0.pom
, we can see there is no dependency on `nubank/state-flow`

But maybe you expect users of your library to depend on state-flow themselves? If so, let me know, and I can give you some tips on how to handle that case.

**Comment by rafaeldelboni** [comment]
Thanks all your points make sense!

> But maybe you expect users of your library to depend on state-flow themselves? If so, let me know, and I can give you some tips on how to handle that case.

Yeah that's the current case, but I'm really open to suggestions, I would be fine to add it on the main deps list, I just don't like test code being bundled on the production main jar.

Maybe I should split libs.

**Comment by NoahTheDuke** [comment]
In my test framework [Lazytest](https://github.com/NoahTheDuke/lazytest), I support an extension with Nubank's [matcher-combinators](https://github.com/nubank/matcher-combinators), but I don't include it in the library itself. I have a dev-only deps.edn alias `:provided` ([seen here](https://github.com/NoahTheDuke/lazytest/blob/90be3015da1aa07fa5966c6e9883f72fbe9065c3/deps.edn#L14)) which includes it, and then in all of my development invocations, I write `clojure -M:provided:dev:test` etc. I include the library in the `pom.xml`'s dependencies I generate when I cut a new release, so it gets picked up by cljdoc. I don't know if that's optimal, but it works for me.

**Comment by rafaeldelboni** [comment]
The [services that use it](https://github.com/parenthesin/microservice-boilerplate-malli/blob/main/deps.edn), they have state-flow in their :dev / :test alias, so never had a problem with that, but this is a "happy coincidence" , maybe someone in the future can have a problem with that.

Yeah I think I will meditate over this, this lib is mainly used by me and friends to bootstrap some backend services, the error makes sense to me since I don't load the library.
