### ISSUE TITLE
Links are case sensitive

### ISSUE THREAD

**Issue by bbatsov** [cljdoc/cljdoc#96]
This link doesn't work [![cljdoc badge](https://cljdoc.xyz/badge/nrepl/nREPL)](https://cljdoc.xyz/d/nrepl/nREPL/CURRENT)

This, however, works just fine [![cljdoc badge](https://cljdoc.xyz/badge/nrepl/nrepl)](https://cljdoc.xyz/d/nrepl/nREPL/CURRENT)

**Comment by martinklepsch** [comment]
We can sure fix this by just lower-casing any group and artifact IDs in paths but it actually seems like Maven is case-sensitive (didn't find anything authoritative but did cursory googling).

Also Clojars returns a 404 for the group/artifact ID combination you provided: https://clojars.org/nrepl/nREPL

I think we should probably keep stuff case sensitive for now. Please close if you agree.

**Comment by bbatsov** [comment]
Fine by me.
