### ISSUE TITLE
Better separate Readme & Changelog from other articles

### ISSUE THREAD

**Issue by bbatsov** [cljdoc/cljdoc#99]
It'd be nice if there was some horizontal rule (or some other separator) to visually distinguish where the manual/articles for a project begin. Right now the README and the changelog are put in front (which makes a lot of sense), but they are not separated from the articles.

![image](https://user-images.githubusercontent.com/103882/44073989-1e0050b6-9f97-11e8-8827-c36b4a90065f.png)

**Comment by martinklepsch** [comment]
Maybe we should move the Readme and Articles outside the "ARTICLES" section, just above it?

**Comment by bbatsov** [comment]
Yeah, I think that'd actually be better. 👍

**Comment by jdhorwitz** [comment]
Agreed 👍

**Comment by dawran6** [comment]
Hi @bbatsov, @martinklepsch, in version [0.4.5](https://cljdoc.org/d/nrepl/nrepl/0.4.5/doc/readme) the articles are missing. Is this intentional?

![image](https://user-images.githubusercontent.com/4307599/48721234-55370d00-ebd6-11e8-8000-f5c6aec22e60.png)

**Comment by martinklepsch** [comment]
@dawran6 I think this is expected, yes. At the time this release was tagged [the cljdoc.edn](https://github.com/nrepl/nrepl/blob/6d7e7e4a90b0e42cdf4d595e3c06cb70132e3335/doc/cljdoc.edn) only contained those two entries.

**Comment by martinklepsch** [comment]
yes that sounds reasonable 👍
